/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2015-08-12 02:46:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.action.print;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import javax.sql.*;
import javax.naming.*;
import com.Trustwin.Admin.Project.Category.*;
import com.Trustwin.Admin.Project.Language.*;

public final class DevicePrint_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	CategoryFunc func = new CategoryFunc();
	LanguageFunc Lanfunc = new LanguageFunc();
	
	String lan = (String)session.getAttribute("nation");
	String ControllerName = (String)request.getParameter("searchControllerName");
	if(ControllerName != null){
		ControllerName = new String(ControllerName.getBytes("8859_1"), "UTF-8");	
	}
	String Address = (String)request.getParameter("searchAddress");
	if(Address != null){
		Address = new String(Address.getBytes("8859_1"), "UTF-8");	
	}
	
	String ID = (String)request.getParameter("searchID");
	if(ID != null){
		ID = new String(ID.getBytes("8859_1"), "UTF-8");	
	}
	
	String UniqueID = (String)request.getParameter("searchUniqueID");
	if((String)request.getParameter("searchUniqueID")!=null){
		UniqueID = new String(UniqueID.getBytes("8859_1"), "UTF-8");
	}

      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("\t<div class=\"printPage\">\r\n");
      out.write("\t\t<div class=\"Title\">");
      out.print(Lanfunc.language(lan, 176));
      out.write("</div>\r\n");
      out.write("\t\t<hr width=\"100%\" hieght=\"2px;\">\r\n");
      out.write("\t\t<form name=\"devicelist\" id=\"devicelist\" method=\"post\" action=\"\">\r\n");
      out.write("\t\t\t<div class=\"selectBox\">\r\n");
      out.write("\t\t\t\t<div class=\"smallTitle\">");
      out.print(Lanfunc.language(lan, 177));
      out.write(" <input type=\"checkbox\" name=\"allcheck\" onclick=\"allDeviceCheck();\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"ListBox\">\r\n");
      out.write("\t\t\t\t\t<div><input type=\"checkbox\" name=\"info\" value=\"devicename/1\"> ");
      out.print(Lanfunc.language(lan, 1));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t<div><input type=\"checkbox\" name=\"info\" value=\"ID/2\"> ");
      out.print(Lanfunc.language(lan, 2));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t<div><input type=\"checkbox\" name=\"info\" value=\"Address/3\"> ");
      out.print(Lanfunc.language(lan, 3));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t<div><input type=\"checkbox\" name=\"info\" value=\"Port Number/4\"> ");
      out.print(Lanfunc.language(lan, 4));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t<div><input type=\"checkbox\" name=\"info\" value=\"Password/5\"> ");
      out.print(Lanfunc.language(lan, 5));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t<div><input type=\"checkbox\" name=\"info\" value=\"UniqueID/6\"> ");
      out.print(Lanfunc.language(lan, 6));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t<div><input type=\"checkbox\" name=\"info\" value=\"Server Port/7\"> ");
      out.print(Lanfunc.language(lan, 7));
      out.write("</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"buttom\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#in\" onclick=\"DeviceList(document.getElementById('devicelist'),'");
      out.print(ControllerName);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(Address);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(ID);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(UniqueID);
      out.write("')\">");
      out.print(Lanfunc.language(lan, 179));
      out.write("</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"printShow\">\r\n");
      out.write("\t\t<div class=\"Title\">");
      out.print(Lanfunc.language(lan, 178));
      out.write("</div>\r\n");
      out.write("\t\t<div class=\"buttom\">\r\n");
      out.write("\t\t\t<a href=\"#in\" onclick=\"ieExecWB()\">print</a> / <a href=\"#in\" onclick=\"DeviceExcel(document.getElementById('devicelist'),'");
      out.print(ControllerName);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(Address);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(ID);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(UniqueID);
      out.write("');\">excel</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"DeviceList\" class=\"tableList\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write(" </div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
