/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2015-10-06 04:50:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.action.print;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import javax.sql.*;
import javax.naming.*;
import com.Trustwin.Admin.Project.Category.*;
import com.Trustwin.Admin.Project.Language.*;

public final class EventPrint_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	CategoryFunc func = new CategoryFunc();
	LanguageFunc Lanfunc = new LanguageFunc();
	
	String lan = (String)session.getAttribute("nation");
	String SDate = (String)request.getParameter("SDate");
	String EDate = (String)request.getParameter("EDate");
	String STime = (String)request.getParameter("STime");
	String ETime = (String)request.getParameter("ETime");
	
	String Name = (String)request.getParameter("Name");
	if(Name != null){
		Name = new String(Name .getBytes("8859_1"), "UTF-8");	
	}
	
	String User = (String)request.getParameter("User");
	if(User != null){
		User = new String(User .getBytes("8859_1"), "UTF-8");	
	}
	String Top = (String)request.getParameter("Num");

      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("\t<div class=\"printPage\">\r\n");
      out.write("\t\t<div class=\"Title\">");
      out.print(Lanfunc.language(lan, 176));
      out.write("</div>\r\n");
      out.write("\t\t<hr width=\"100%\" hieght=\"2px;\">\r\n");
      out.write("\t\t<form name=\"eventlist\" id=\"eventlist\" method=\"post\" action=\"\">\r\n");
      out.write("\t\t\t<div class=\"selectBox\">\r\n");
      out.write("\t\t\t\t<div class=\"smallTitle\">");
      out.print(Lanfunc.language(lan, 177));
      out.write(" <input type=\"checkbox\" name=\"allcheck\" onclick=\"allEventCheck();\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"ListBox\">\r\n");
      out.write("\t\t\t\t\t<div><input type=\"checkbox\" name=\"info\" value=\"EventType/72\"> ");
      out.print(Lanfunc.language(lan, 72));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t<div><input type=\"checkbox\" name=\"info\" value=\"EventDate/73\"> ");
      out.print(Lanfunc.language(lan, 73));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t<div><input type=\"checkbox\" name=\"info\" value=\"EventTime/74\"> ");
      out.print(Lanfunc.language(lan, 74));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t<div><input type=\"checkbox\" name=\"info\" value=\"EventPlace/75\"> ");
      out.print(Lanfunc.language(lan, 75));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t<div><input type=\"checkbox\" name=\"info\" value=\"EventName/76\"> ");
      out.print(Lanfunc.language(lan, 76));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t<div><input type=\"checkbox\" name=\"info\" value=\"EventUserID/77\"> ");
      out.print(Lanfunc.language(lan, 77));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t<div><input type=\"checkbox\" name=\"info\" value=\"EventUserName/78\"> ");
      out.print(Lanfunc.language(lan, 78));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t<div><input type=\"checkbox\" name=\"info\" value=\"EventDoorState/79\"> ");
      out.print(Lanfunc.language(lan, 79));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t<div><input type=\"checkbox\" name=\"info\" value=\"EventCompanyID/80\"> ");
      out.print(Lanfunc.language(lan, 80));
      out.write("</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"buttom\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#in\" onclick=\"EventList(document.getElementById('eventlist'),'");
      out.print(SDate);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(EDate);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(STime);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(ETime);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(Name);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(User);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(Top);
      out.write("')\">");
      out.print(Lanfunc.language(lan, 179));
      out.write("</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"printShow\">\r\n");
      out.write("\t\t<div class=\"Title\">");
      out.print(Lanfunc.language(lan, 178));
      out.write("</div>\r\n");
      out.write("\t\t<div class=\"buttom\">\r\n");
      out.write("\t\t\t<a href=\"#in\" onclick=\"ieExecWB()\">print</a> / <a href=\"#in\" onclick=\"EventExcel(document.getElementById('eventlist'),'");
      out.print(SDate);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(EDate);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(STime);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(ETime);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(Name);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(User);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(Top);
      out.write("');\">excel</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"EventList\" class=\"tableList\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write(" </div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
