/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2015-08-12 02:46:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.action.print;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import javax.sql.*;
import javax.naming.*;
import com.Trustwin.Admin.Project.Category.*;

public final class ManagePrint_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	CategoryFunc func = new CategoryFunc();
	String div = (String)request.getParameter("div");

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=8\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/TrustWinPro/action/css/common.css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"/TrustWinPro/action/js/common.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/TrustWinPro/action/js/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/TrustWinPro/action/js/calendar.js\"></script>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=euc-kr\" />\r\n");
      out.write("<title>Print Page</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function UserList(form,FN,MN,LN,DP){\r\n");
      out.write("\tvar arrayObj = \"\";\r\n");
      out.write("\tvar count = 0;\r\n");
      out.write("\tfor(i=0;i<form.info.length;i++){\r\n");
      out.write("\t\tif(form.info[i].checked){\r\n");
      out.write("\t\t\tarrayObj = arrayObj + form.info[i].value + \",\";\r\n");
      out.write("\t\t\tcount++;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tif(count==0){\r\n");
      out.write("\t\talert(\"항목을 선택하세요\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\t$.ajax({      \r\n");
      out.write("\t\t    type:\"post\",  \r\n");
      out.write("\t\t    url:\"/TrustWinPro/action/ajax/PrintUserList.jsp\",   \r\n");
      out.write("\t\t    data: \"array=\" + arrayObj + \"&FN=\"+FN+\"&MN=\"+MN+\"&LN=\"+LN+\"&DP=\"+DP,\r\n");
      out.write("\t\t    success:function(args){   \r\n");
      out.write("\t\t        $(\"#UserList\").html(args);      \r\n");
      out.write("\t\t    },   \r\n");
      out.write("\t\t    error:function(e){  \r\n");
      out.write("\t\t        alert(e.responseText);  \r\n");
      out.write("\t\t    }  \r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function DeviceList(form,CN,Add,ID,UID){\r\n");
      out.write("\tvar arrayObj = \"\";\r\n");
      out.write("\tvar count = 0;\r\n");
      out.write("\tfor(i=0;i<form.info.length;i++){\r\n");
      out.write("\t\tif(form.info[i].checked){\r\n");
      out.write("\t\t\tarrayObj = arrayObj + form.info[i].value + \",\";\r\n");
      out.write("\t\t\tcount++;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tif(count==0){\r\n");
      out.write("\t\talert(\"항목을 선택하세요\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\t$.ajax({      \r\n");
      out.write("\t\t    type:\"post\",  \r\n");
      out.write("\t\t    url:\"/TrustWinPro/action/ajax/PrintDeviceList.jsp\",\r\n");
      out.write("\t\t    data: \"array=\" + arrayObj + \"&CN=\"+CN+\"&Add=\"+Add+\"&ID=\"+ID+\"&UID=\"+UID,\r\n");
      out.write("\t\t    success:function(args){   \r\n");
      out.write("\t\t        $(\"#DeviceList\").html(args);      \r\n");
      out.write("\t\t    },   \r\n");
      out.write("\t\t    error:function(e){  \r\n");
      out.write("\t\t        alert(e.responseText);  \r\n");
      out.write("\t\t    }  \r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function EventList(form,SDate,EDate,STime,ETime,Name,User,Top){\r\n");
      out.write("\tvar arrayObj = \"\";\r\n");
      out.write("\tvar count = 0;\r\n");
      out.write("\tfor(i=0;i<form.info.length;i++){\r\n");
      out.write("\t\tif(form.info[i].checked){\r\n");
      out.write("\t\t\tarrayObj = arrayObj + form.info[i].value + \",\";\r\n");
      out.write("\t\t\tcount++;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tif(count==0){\r\n");
      out.write("\t\talert(\"항목을 선택하세요\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\t$.ajax({      \r\n");
      out.write("\t\t    type:\"post\",  \r\n");
      out.write("\t\t    url:\"/TrustWinPro/action/ajax/PrintEventList.jsp\",   \r\n");
      out.write("\t\t    data: \"array=\" + arrayObj + \"&SDate=\"+SDate+\"&EDate=\"+EDate+\"&STime=\"+STime+\"&ETime=\"+ETime+\"&Name=\"+Name+\"&User=\"+User+\"&Num=\"+Top,\r\n");
      out.write("\t\t    success:function(args){   \r\n");
      out.write("\t\t        $(\"#EventList\").html(args);      \r\n");
      out.write("\t\t    },   \r\n");
      out.write("\t\t    error:function(e){  \r\n");
      out.write("\t\t        alert(e.responseText);  \r\n");
      out.write("\t\t    }  \r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("var Uchange = 0;\r\n");
      out.write("function allUserCheck(){\r\n");
      out.write("\tvar check = document.userlist.info;\r\n");
      out.write("\tif(Uchange == 0){\r\n");
      out.write("\t\tfor(var i = 0 ; i < check.length;i++ ){\r\n");
      out.write("\t\t\tcheck[i].checked = true;\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\tUchange = 1;\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tfor(var i = 0 ; i < check.length;i++ ){\r\n");
      out.write("\t\t\tcheck[i].checked = false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tUchange = 0;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("var Dchange = 0;\r\n");
      out.write("function allDeviceCheck(){\r\n");
      out.write("\tvar check = document.devicelist.info;\r\n");
      out.write("\tif(Dchange == 0){\r\n");
      out.write("\t\tfor(var i = 0 ; i < check.length;i++ ){\r\n");
      out.write("\t\t\tcheck[i].checked = true;\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\tDchange = 1;\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tfor(var i = 0 ; i < check.length;i++ ){\r\n");
      out.write("\t\t\tcheck[i].checked = false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tDchange = 0;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("var Echange = 0;\r\n");
      out.write("function allEventCheck(){\r\n");
      out.write("\tvar check = document.eventlist.info;\r\n");
      out.write("\tif(Echange == 0){\r\n");
      out.write("\t\tfor(var i = 0 ; i < check.length;i++ ){\r\n");
      out.write("\t\t\tcheck[i].checked = true;\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\tEchange = 1;\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tfor(var i = 0 ; i < check.length;i++ ){\r\n");
      out.write("\t\t\tcheck[i].checked = false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tEchange = 0;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"printContent\">\r\n");

	if(div.equals("User")){ 

      out.write("\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/action/print/UserPrint.jsp", out, false);
      out.write('\r');
      out.write('\n');

	}else if(div.equals("Device")){

      out.write("\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/action/print/DevicePrint.jsp", out, false);
      out.write('\r');
      out.write('\n');
		
	}else if(div.equals("Event")){

      out.write("\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/action/print/EventPrint.jsp", out, false);
      out.write('\r');
      out.write('\n');
			
	}

      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
