/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2015-12-07 05:03:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.action.print;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import javax.sql.*;
import javax.naming.*;
import com.Trustwin.Admin.Project.Language.*;

public final class UserPrint_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	LanguageFunc Lanfunc = new LanguageFunc();
	String lan = (String)session.getAttribute("nation");
	String FirstName = (String)request.getParameter("searchFirstName");
	if(FirstName != null){
		FirstName = new String(FirstName .getBytes("8859_1"), "UTF-8");	
	}
	String MiddleName = (String)request.getParameter("searchMiddleName");
	if(MiddleName != null){
		MiddleName = new String(MiddleName .getBytes("8859_1"), "UTF-8");	
	}
	
	String LastName = (String)request.getParameter("searchLastName");
	if(LastName != null){
		LastName = new String(LastName .getBytes("8859_1"), "UTF-8");	
	}
	
	int Department = 0;
	if((String)request.getParameter("searchDepartment")!=null){
		String temp = (String)request.getParameter("searchDepartment");
		if(!temp.equals("")){
	Department = Integer.parseInt((String)request.getParameter("searchDepartment"));
		}
	}

      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("\t<div class=\"printPage\">\r\n");
      out.write("\t\t<div class=\"Title\">");
      out.print(Lanfunc.language(lan, 176));
      out.write("</div>\r\n");
      out.write("\t\t<hr width=\"100%\" hieght=\"2px;\">\r\n");
      out.write("\t\t<form name=\"userlist\" id=\"userlist\" method=\"post\" action=\"\">\r\n");
      out.write("\t\t\t<div class=\"selectBox\">\r\n");
      out.write("\t\t\t\t<div class=\"smallTitle\">");
      out.print(Lanfunc.language(lan, 177));
      out.write(" <input type=\"checkbox\" name=\"allcheck\" onclick=\"allUserCheck();\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"ListBox\">\r\n");
      out.write("\t\t\t\t\t<div><input type=\"checkbox\" name=\"info\" value=\"FirstName/26\"> ");
      out.print(Lanfunc.language(lan, 26));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t<div><input type=\"checkbox\" name=\"info\" value=\"MiddleName/27\"> ");
      out.print(Lanfunc.language(lan, 27));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t<div><input type=\"checkbox\" name=\"info\" value=\"LastName/28\"> ");
      out.print(Lanfunc.language(lan, 28));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t<div><input type=\"checkbox\" name=\"info\" value=\"UserID/29\"> ");
      out.print(Lanfunc.language(lan, 29));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t<div><input type=\"checkbox\" name=\"info\" value=\"UserClass/30\"> ");
      out.print(Lanfunc.language(lan, 30));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t<div><input type=\"checkbox\" name=\"info\" value=\"ID/2\"> ");
      out.print(Lanfunc.language(lan, 2));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t<div><input type=\"checkbox\" name=\"info\" value=\"Password/5\"> ");
      out.print(Lanfunc.language(lan, 5));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t<div><input type=\"checkbox\" name=\"info\" value=\"Department/39\"> ");
      out.print(Lanfunc.language(lan, 39));
      out.write("</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"buttom\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#in\" onclick=\"UserList(document.getElementById('userlist'),'");
      out.print(FirstName);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(MiddleName);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(LastName);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(Department);
      out.write("')\">");
      out.print(Lanfunc.language(lan, 179));
      out.write("</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"printShow\">\r\n");
      out.write("\t\t<div class=\"Title\">");
      out.print(Lanfunc.language(lan, 178));
      out.write("</div>\r\n");
      out.write("\t\t<div class=\"buttom\">\r\n");
      out.write("\t\t\t<a href=\"#in\" onclick=\"ieExecWB()\">print</a> / <a href=\"#in\" onclick=\"UserExcel(document.getElementById('userlist'),'");
      out.print(FirstName);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(MiddleName);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(LastName);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(Department);
      out.write("');\">excel</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"UserList\" class=\"tableList\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write(" </div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
