/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2016-03-03 02:06:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.action.ajax;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import javax.sql.*;
import javax.naming.*;
import com.Trustwin.Admin.Project.Device.*;
import com.Trustwin.Admin.Project.Language.*;

public final class DeviceList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	int group= Integer.parseInt(request.getParameter("group"));
	int[] num = new int[1000];
	DeviceFunc Devfunc = new DeviceFunc();
	LanguageFunc Lanfunc = new LanguageFunc();
	num[0] = group;
	Devfunc.setCount();
	num = Devfunc.DeviceGroupIdx(group,num);
	String lan = (String)session.getAttribute("nation");

      out.write("\r\n");
      out.write("\t<table border=1 cellspacing=\"0\"  class=\"titleEx1\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>");
      out.print(Lanfunc.language(lan, 124) );
      out.write("</th>\r\n");
      out.write("\t\t\t<th>");
      out.print(Lanfunc.language(lan, 2) );
      out.write("</th>\r\n");
      out.write("\t\t\t<th>");
      out.print(Lanfunc.language(lan, 3) );
      out.write("</th>\r\n");
      out.write("\t\t\t<th>");
      out.print(Lanfunc.language(lan, 67) );
      out.write("</th>\r\n");
      out.write("\t\t\t<th>");
      out.print(Lanfunc.language(lan, 5) );
      out.write("</th>\r\n");
      out.write("\t\t\t<th>");
      out.print(Lanfunc.language(lan, 6) );
      out.write("</th>\r\n");
      out.write("\t\t\t<th>");
      out.print(Lanfunc.language(lan, 7) );
      out.write("</th>\r\n");
      out.write("\t\t\t<th>");
      out.print(Lanfunc.language(lan, 70) );
      out.write("</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<table cellspacing=\"0\"  class=\"ex1\">\r\n");
      out.write("\t\t<tbody>\r\n");
      out.write("\t\r\n");

	int count = 0;
	for(int i=0;i<num.length;i++){
		Device[] device = Devfunc.DeviceSelect2(num[i]);
		for(int j=0;j<device.length;j++){
			if(count%2==0){
				out.println("<tr  class='odd'>");
			}else{
				out.println("<tr>");	
			}
			out.println("<td class='date1'>" + device[j].getControllerName() + "</td>");
			out.println("<td class='date1'>" + device[j].getID() + "</td>");
			out.println("<td class='date1'>" + device[j].getAddress() + "</td>");
			out.println("<td class='date1'>" + device[j].getPort() + "</td>");
			out.println("<td class='date1'>" + device[j].getPassword() + "</td>");
			out.println("<td class='date1'>" + device[j].getUniqueID() + "</td>");
			out.println("<td class='date1'>" + device[j].getServerPort() + "</td>");
			out.println("<td class='date1'>" + device[j].getGroupIdx() + "</td>");
			out.println("</tr>");
			count++;
		}
	}


      out.write("\r\n");
      out.write("\t\t</tbody>\r\n");
      out.write("\t</table>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
