/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2015-02-25 06:52:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.action.ajax;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import javax.sql.*;
import javax.naming.*;
import com.Trustwin.Admin.Project.Event.*;
import com.Trustwin.Admin.Project.Language.*;

public final class LogA_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String SDate = (String)request.getParameter("searchStartDate");
	String EDate = (String)request.getParameter("searchEndDate");
	String SHour = (String)request.getParameter("searchStartHour");
	String SMin = (String)request.getParameter("searchStartMinute");
	String SSec = (String)request.getParameter("searchStartSec");
	String EHour = (String)request.getParameter("searchEndHour");
	String EMin = (String)request.getParameter("searchEndMinute");
	String ESec = (String)request.getParameter("searchEndSec");
	String Name = (String)request.getParameter("searchName");
	String User = (String)request.getParameter("searchUser");
	String Num = (String)request.getParameter("num");
	EventFunc Evtfunc = new EventFunc();
	LanguageFunc Lanfunc = new LanguageFunc();
	String lan = (String)session.getAttribute("nation");
	if(Num == null){
		Num = "30";
	}
	Connection conn = null;
	String sql = "select EventType,EventDate,EventTime,EventPlace,EventName,EventUserID,EventUserName,EventDoorState,EventCompanyID from dbo.History"; 
	
	String Year = (String)request.getParameter("year");
	String where = " where 1=1 ";
	
	if(SDate == null || EDate ==null){
		SDate = "";
		EDate = "";
	}else{
		if((!SDate.equals("")&&!SDate.equals("null"))||(!EDate.equals("")&&!EDate.equals("null"))){
	where = where + " and EventDate between '" + SDate + "' and '"+EDate+"'";
		}
	} 
	
	if(SHour == null || SMin == null || SSec == null || EHour == null || EMin == null || ESec == null){
		SHour = "";
		SMin = "";
		SSec = "";
		EHour = "";
		EMin = "";
		ESec = "";
	}else{
		if((!SHour.equals("")&&!SHour.equals("null"))||(!SMin.equals("")&&!SMin.equals("null"))||(!SSec.equals("")&&!SSec.equals("null"))||(!EHour.equals("")&&!EHour.equals("null"))||(!EMin.equals("")&&!EMin.equals("null"))||(!ESec.equals("")&&!ESec.equals("null"))){
	if((!SHour.equals("0")&&!EHour.equals("0"))){
		if(Integer.parseInt(SHour)<10){
	SHour = "0" + SHour;
		}
		if(Integer.parseInt(SMin)<10){
	SMin = "0" + SMin;
		}
		if(Integer.parseInt(SSec)<10){
	SSec = "0" + SSec;
		}
		if(Integer.parseInt(EHour)<10){
	EHour = "0" + EHour;
		}
		if(Integer.parseInt(EMin)<10){
	EMin = "0" + EMin;
		}
		if(Integer.parseInt(ESec)<10){
	ESec = "0" + ESec;
		}
		where = where + " and EventTime between '" + SHour + ":"+SMin+":"+SSec+"' and '" + EHour + ":"+EMin+":"+ESec+"'";
	}
		}
	}
	
	if(Name == null){
		Name = "";
	}else{
		if(!Name.equals("")&&!Name.equals("null")){
	where = where + " and EventName = '" + Name + "'";
		}
	}
	
	if(User == null){
		User = "";		
	}else{
		if(!User.equals("")&&!User.equals("null")){
	where = where + " and EventUserName = '" + User + "'";
		}
	}
	
	sql = sql + where;
	sql = sql + " order by EventDate desc,EventTime desc; ";
		try {
		Context init = new InitialContext();
		DataSource ds = (DataSource)init.lookup("java:comp/env/jdbc/MssqlDB");
		conn = ds.getConnection();
		Statement pstmt = conn.createStatement();
		ResultSet rs = pstmt.executeQuery(sql);

      out.write("\r\n");
      out.write("\t<table cellspacing=\"0\"  class=\"titleEx1\">\r\n");
      out.write("\t\t<colgroup>\r\n");
      out.write("\t\t\t<col width=\"9%\">\r\n");
      out.write("\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t<col width=\"14%\">\r\n");
      out.write("\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t<col width=\"12%\">\r\n");
      out.write("\t\t\t<col width=\"12%\">\r\n");
      out.write("\t\t\t<col width=\"13%\">\r\n");
      out.write("\t\t</colgroup>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>");
      out.print(Lanfunc.language(lan, 72) );
      out.write("</th>\r\n");
      out.write("\t\t\t<th>");
      out.print(Lanfunc.language(lan, 73) );
      out.write("</th>\r\n");
      out.write("\t\t\t<th>");
      out.print(Lanfunc.language(lan, 74) );
      out.write("</th>\r\n");
      out.write("\t\t\t<th>");
      out.print(Lanfunc.language(lan, 75) );
      out.write("</th>\r\n");
      out.write("\t\t\t<th>");
      out.print(Lanfunc.language(lan, 76) );
      out.write("</th>\r\n");
      out.write("\t\t\t<th>");
      out.print(Lanfunc.language(lan, 77) );
      out.write("</th>\r\n");
      out.write("\t\t\t<th>");
      out.print(Lanfunc.language(lan, 78) );
      out.write("</th>\r\n");
      out.write("\t\t\t<th>");
      out.print(Lanfunc.language(lan, 79) );
      out.write("</th>\r\n");
      out.write("\t\t\t<th>");
      out.print(Lanfunc.language(lan, 80) );
      out.write("</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<table cellspacing=\"0\"  class=\"ex1\">\r\n");
      out.write("\t\t<colgroup>\r\n");
      out.write("\t\t\t<col width=\"9%\">\r\n");
      out.write("\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t<col width=\"14%\">\r\n");
      out.write("\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t<col width=\"12%\">\r\n");
      out.write("\t\t\t<col width=\"12%\">\r\n");
      out.write("\t\t\t<col width=\"13%\">\r\n");
      out.write("\t\t</colgroup>\r\n");
      out.write("\t\t<tbody>\r\n");
      out.write("\t\r\n");

				int count = 0;
				for(int i=0;;){
					if(!rs.next()){
						break;
					}
					if(Integer.parseInt(Num) == i){
						break;
					}
					
					EventOption eo = Evtfunc.selOptionType(rs.getString(5));
					String color = eo.getColor();
					if(eo.getDisplay()!=null){
						if(eo.getDisplay().equals("1")){
							if(color != null){
								if(i%2==0){
									out.println("<tr  class='odd' style='color:#"+eo.getColor()+";'>");
								}else{
									out.println("<tr style='color:#"+eo.getColor()+";'>");	
								}
							}else{
								if(i%2==0){
									out.println("<tr  class='odd'>");
								}else{
									out.println("<tr>");	
								}
							}
							out.println("<td class='date1'>" + rs.getString(1) + "</td>");
							out.println("<td class='date1'>" + rs.getString(2) + "</td>");
							out.println("<td class='date1'>" + rs.getString(3) + "</td>");
							out.println("<td class='date1'>" + rs.getString(4) + "</td>");
							out.println("<td class='date1'>" + rs.getString(5) + "</td>");
							out.println("<td class='date1'>" + rs.getString(6) + "</td>");
							out.println("<td class='date1'>" + rs.getString(7) + "</td>");
							out.println("<td class='date1'>" + rs.getString(8) + "</td>");
							out.println("<td class='date1'>" + rs.getString(9) + "</td>");
							out.println("</tr>");
							i++;
						}else{
							
						}
					}else{
						
					}
				}

      out.write("\r\n");
      out.write("\t\t</tbody>\r\n");
      out.write("\t</table>\r\n");

				rs.close();
				conn.close();
		}catch(Exception e){
			out.println("DB error!!.");
			e.printStackTrace();
		}

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
