/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2015-12-23 06:42:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.action.page;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import javax.sql.*;
import javax.naming.*;
import com.Trustwin.Admin.Project.Access.*;
import com.Trustwin.Admin.Project.Language.*;
import com.Trustwin.Admin.Project.Device.*;
import com.Trustwin.Admin.Project.User.*;

public final class AccessGroup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=euc-kr");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	AccessFunc Accfunc = new AccessFunc();
	LanguageFunc Lanfunc = new LanguageFunc();
	DeviceFunc Devfunc = new DeviceFunc();
	UserFunc Userfunc = new UserFunc();
	
	String idxs = "";
	int value = 0;
	int idx = 0;
	if(request.getParameter("num") == null || request.getParameter("num").equals("")){
		AccessGroup[] group =  Accfunc.AccessGroupMenu();
		if(group.length != 0){
			idx = group[0].getIdx();
		}else{
			value = 1;
		}
	}else{
		idx = Integer.parseInt(request.getParameter("num"));
	}
	if(value == 0){
		AccessGroup access = Accfunc.SelAccessGroup(idx);
		AccessDevice[] ad = Accfunc.SelAccessDevice(idx);
		AccessUser[] au = Accfunc.SelAccessUser(idx);
		String lan = (String)session.getAttribute("nation");

      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction displayInfo(z){\r\n");
      out.write("\t\tfor(var i=1;i<3;i++){\r\n");
      out.write("\t\t\tif(i==z){\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"tab0\"+i).className = \"here\";\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"tab\"+i).style.display = \"block\";\t\t\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"tab0\"+i).className = \"\";\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"tab\"+i).style.display = \"none\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction DeviceAdd(){\r\n");
      out.write("\t\tdocument.getElementById(\"postitDevice\").style.display = \"block\";\r\n");
      out.write("\t\tdocument.getElementById(\"postitDevice\").style.top = \"200px\";\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction DeviceDel(){\r\n");
      out.write("\t\tdocument.getElementById(\"deviceInfo\").submit();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction UserAdd(){\r\n");
      out.write("\t\tdocument.getElementById(\"postitUser\").style.display = \"block\";\r\n");
      out.write("\t\tdocument.getElementById(\"postitUser\").style.top = \"200px\";\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction UserDel(){\r\n");
      out.write("\t\tdocument.getElementById(\"userInfo\").submit();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction GroupUpdate(){\r\n");
      out.write("\t\tdocument.getElementById(\"groupInfo\").submit();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction GroupDel(){\r\n");
      out.write("\t\tdocument.getElementById(\"groupInfo\").action = \"/TrustWinPro/action/page/AccessGroupDel.jsp\";\r\n");
      out.write("\t\tdocument.getElementById(\"groupInfo\").submit();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction allDeviceInfoCheck(){\r\n");
      out.write("\t\tvar check = document.deviceInfo.check;\r\n");
      out.write("\t\tif(change == 0){\r\n");
      out.write("\t\t\tfor(var i = 0 ; i < check.length;i++ ){\r\n");
      out.write("\t\t\t\tcheck[i].checked = true;\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\tchange = 1;\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tfor(var i = 0 ; i < check.length;i++ ){\r\n");
      out.write("\t\t\t\tcheck[i].checked = false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tchange = 0;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction allUserInfoCheck(){\r\n");
      out.write("\t\tvar check = document.userInfo.check;\r\n");
      out.write("\t\tif(change == 0){\r\n");
      out.write("\t\t\tfor(var i = 0 ; i < check.length;i++ ){\r\n");
      out.write("\t\t\t\tcheck[i].checked = true;\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\tchange = 1;\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tfor(var i = 0 ; i < check.length;i++ ){\r\n");
      out.write("\t\t\t\tcheck[i].checked = false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tchange = 0;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("\t<section class = \"sectionji\">\r\n");
      out.write("\t\t\t<ul class = \"ulji\">\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("<div id=\"Access\">\r\n");
      out.write("\t<div class=\"basic\">\r\n");
      out.write("\t\t<form action=\"/TrustWinPro/action/page/AccessGroupUpdate.jsp\" name=\"groupInfo\" id=\"groupInfo\" method=\"post\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"idx\" value=\"");
      out.print(idx);
      out.write("\" >\r\n");
      out.write("\t\t\t<div class=\"block\">\r\n");
      out.write("\t\t\t\t<div class=\"header\">");
      out.print(Lanfunc.language(lan, 81));
      out.write("</div>\r\n");
      out.write("\t\t\t\t<div class=\"main\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"name\" value=\"");
      out.print(access.getName() );
      out.write("\" >\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"header\">\r\n");
      out.write("\t\t\t\t");
      out.print(Lanfunc.language(lan, 82));
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"main\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"info\" value=\"");
      out.print(access.getInfo() );
      out.write("\" >\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</section>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id = \"Access\">\r\n");
      out.write("<div class=\"tab\">\r\n");
      out.write("\t\t\t<ul id=\"globalnav\">\r\n");
      out.write("\t\t\t\t<li class=\"tab1\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#content\" onclick=\"displayInfo(1)\" class=\"here\" id=\"tab01\">");
      out.print(Lanfunc.language(lan, 107));
      out.write("</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"tab2\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#content\" onclick=\"displayInfo(2)\" id=\"tab02\">");
      out.print(Lanfunc.language(lan, 108));
      out.write("</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("</div>\r\n");
      out.write("\t<div class=\"info\">\r\n");
      out.write("\t\t<div class=\"device\" id=\"tab1\">\r\n");
      out.write("\t\t\t<div class=\"InfoBox\">\r\n");
      out.write("\t\t\t\t<form action=\"/TrustWinPro/action/page/AccessDeviceDel.jsp\" name=\"deviceInfo\" id=\"deviceInfo\" method=\"post\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"idx\" value=\"");
      out.print(access.getIdx() );
      out.write("\" >\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class = \"tablebor\">\r\n");
      out.write("\t\t\t\t\t<table cellspacing=\"0\" class=\"titleEx1\">\r\n");
      out.write("\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"20%\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"40%\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"40%\">\r\n");
      out.write("\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>");
      out.print(Lanfunc.language(lan, 85));
      out.write("<input type=\"checkbox\" name=\"allcheck\" onclick=\"allDeviceInfoCheck();\"></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>");
      out.print(Lanfunc.language(lan, 35));
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>");
      out.print(Lanfunc.language(lan, 109));
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t<table cellspacing=\"0\"  class=\"ex1\">\r\n");
      out.write("\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"20%\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"40%\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"40%\">\r\n");
      out.write("\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");

	for(int i=0;i<ad.length;i++){
		Device device = Devfunc.selDevice(Integer.parseInt(ad[i].getDevice()));

      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class='date1'><input type=\"checkbox\" name=\"check\" value=\"");
      out.print(ad[i].getIdx());
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class='date1'>");
      out.print(device.getControllerName() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class='date1'>");
      out.print(ad[i].getTimezone().equals("0") ? "" : ad[i].getTimezone() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");

	}

      out.write("\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"buttom\">\r\n");
      out.write("\t\t\t\t<div class=\"image\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#DeviceInfo\" onclick=\"DeviceAdd();\"><img src=\"/TrustWinPro/action/image/interface/submit.png\"></a>\r\n");
      out.write("\t\t\t\t\t<a href=\"#DeviceInfo\" onclick=\"DeviceDel();\"><img src=\"/TrustWinPro/action/image/interface/delete.png\"></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"user\" id=\"tab2\" style=\"display:none;\">\r\n");
      out.write("\t\t\t<div class=\"InfoBox\">\r\n");
      out.write("\t\t\t\t<form action=\"/TrustWinPro/action/page/AccessUserDel.jsp\" name=\"userInfo\" id=\"userInfo\" method=\"post\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"idx\" value=\"");
      out.print(access.getIdx() );
      out.write("\" >\r\n");
      out.write("\t\t\t\t<div class = \"tablebor\">\r\n");
      out.write("\t\t\t\t\t<table cellspacing=\"0\" class=\"titleEx1\">\r\n");
      out.write("\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"20%\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"40%\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"40%\">\r\n");
      out.write("\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>");
      out.print(Lanfunc.language(lan, 85));
      out.write("<input type=\"checkbox\" name=\"allcheck\" onclick=\"allUserInfoCheck();\"></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>");
      out.print(Lanfunc.language(lan, 108));
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>");
      out.print(Lanfunc.language(lan, 39));
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t<table cellspacing=\"0\"  class=\"ex1\">\r\n");
      out.write("\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"20%\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"40%\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"40%\">\r\n");
      out.write("\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");

	for(int i=0;i<au.length;i++){
		String name = Userfunc.SelUserName(au[i].getUserId());

      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class='date1'><input type=\"checkbox\" name=\"check\" value=\"");
      out.print(au[i].getIdx());
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class='date1'>");
      out.print(name );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class='date1'>");
      out.print(au[i].getDeviceGroup() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");

	}

      out.write("\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"buttom\">\r\n");
      out.write("\t\t\t\t<div class=\"image\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#DeviceInfo\" onclick=\"UserAdd();\"><img src=\"/TrustWinPro/action/image/interface/submit.png\"></a>\r\n");
      out.write("\t\t\t\t\t<a href=\"#DeviceInfo\" onclick=\"UserDel();\"><img src=\"/TrustWinPro/action/image/interface/delete.png\"></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"mainButtom\">\r\n");
      out.write("\t\t<div class=\"image\">\r\n");
      out.write("\t\t\t<a href=\"#DeviceInfo\" onclick=\"GroupUpdate();\"><img src=\"/TrustWinPro/action/image/interface/submit.png\"></a>\r\n");
      out.write("\t\t\t<a href=\"#DeviceInfo\" onclick=\"GroupDel();\"><img src=\"/TrustWinPro/action/image/interface/delete.png\"></a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"postitDevice\" id=\"postitDevice\">\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "AccessDevice.jsp", out, false);
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"postitUser\" id=\"postitUser\">\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "AccessUser.jsp", out, false);
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<form action=\"/TrustWinPro/action/page/TimeZoneDel.jsp\" name=\"TimeZoneDel\" id=\"TimeZoneDel\" method=\"post\">\r\n");
      out.write("\t<input type=\"hidden\" value=\"\" name=\"num\" id=\"num\" />\r\n");
      out.write("</form>\r\n");

	}else{
		
	}

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
