/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2015-12-22 05:59:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.action.page;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import javax.sql.*;
import javax.naming.*;
import com.Trustwin.Admin.Project.Access.*;
import com.Trustwin.Admin.Project.Category.*;
import com.Trustwin.Admin.Project.Language.*;

public final class AccessUser_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=euc-kr");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	CategoryFunc Catafunc = new CategoryFunc();
	AccessFunc Accfunc = new AccessFunc();
	LanguageFunc Lanfunc = new LanguageFunc();
	
	int idxs = 0;
	if(request.getParameter("num") == null || request.getParameter("num").equals("")){
		AccessGroup[] group =  Accfunc.AccessGroupMenu();
		idxs = group[0].getIdx();
	}else{
		idxs = Integer.parseInt(request.getParameter("num"));
	}
	String lan = (String)session.getAttribute("nation");

      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\tvar change = 0;\r\n");
      out.write("\r\n");
      out.write("\tfunction accessUserList(v){\r\n");
      out.write("\t\tif(v!=0){\r\n");
      out.write("\t\t\t$.ajax({      \r\n");
      out.write("\t\t\t    type:\"post\",  \r\n");
      out.write("\t\t\t    url:\"/TrustWinPro/action/ajax/AccessUserList.jsp\",   \r\n");
      out.write("\t\t\t    data: \"group=\" + v,\r\n");
      out.write("\t\t\t    success:function(args){   \r\n");
      out.write("\t\t\t        $(\"#userlist\").html(args);      \r\n");
      out.write("\t\t\t    },   \r\n");
      out.write("\t\t\t    error:function(e){  \r\n");
      out.write("\t\t\t        alert(e.responseText);  \r\n");
      out.write("\t\t\t    }  \r\n");
      out.write("\t\t\t}); \r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction allUserCheck(){\r\n");
      out.write("\t\tvar check = document.getElementsByName(\"checkU\");\r\n");
      out.write("\t\tif(change == 0){\r\n");
      out.write("\t\t\tfor(var i = 0 ; i < check.length;i++ ){\r\n");
      out.write("\t\t\t\tcheck[i].checked = true;\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\tchange = 1;\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tfor(var i = 0 ; i < check.length;i++ ){\r\n");
      out.write("\t\t\t\tcheck[i].checked = false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tchange = 0;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction accessUser(){\r\n");
      out.write("\t\tdocument.getElementById(\"AccessUser\").submit();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction accessUserClose(){\r\n");
      out.write("\t\tdocument.getElementById(\"postitUser\").style.display = \"none\";\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<div class=\"accessUser\">\r\n");
      out.write("\t<form name=\"AccessUser\" id=\"AccessUser\" method=\"post\" action=\"/TrustWinPro/action/page/AccessUserAdd.jsp\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"idx\" id=\"idx\" value=\"");
      out.print(idxs );
      out.write("\" >\r\n");
      out.write("\t\t<table >\r\n");
      out.write("\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t<col width=\"20%\" align=\"center\" >\r\n");
      out.write("\t\t\t\t<col width=\"80%\">\r\n");
      out.write("\t\t\t</colgroup>\r\n");
      out.write("\t\t\t<tr class=\"block\">\r\n");
      out.write("\t\t\t\t<td class=\"header\">");
      out.print(Lanfunc.language(lan, 134) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td class=\"main\">\r\n");
      out.write("\t\t\t\t\t<select name=\"User\" onchange=\"accessUserList(this.value);\" onload=\"accessUserList(this.value);\">\r\n");
      out.write("\t\t\t\t\t\t<option value = \"0\" >-- ");
      out.print(Lanfunc.language(lan, 65) );
      out.write(" --</option>\r\n");

	Category[] category = null;
	category = Catafunc.CategoryDefind();
	
	int lengthC = category.length;
	Category[] cate = new Category[lengthC];	
	cate = Catafunc.SortCategoryOne(category);
	for(int i=0;i < cate.length;i++){

      out.write("\r\n");
      out.write("\t\t\t\t\t\t<option value = \"");
      out.print(cate[i].getIdx());
      out.write('"');
      out.write('>');
      out.print(cate[i].getName() );
      out.write("</option>\r\n");

	}

      out.write("\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t<div id=\"userlist\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<div class=\"buttom\">\r\n");
      out.write("\t\t\t<a href=\"#DeviceInfo\" onclick=\"accessUser();\"><img src=\"/TrustWinPro/action/image/interface/submit.png\"></a>\r\n");
      out.write("\t\t\t<a href=\"#DeviceInfo\" onclick=\"accessUserClose();\"><img src=\"/TrustWinPro/action/image/interface/delete.png\"></a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
