/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2015-12-21 07:57:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.action.page;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import javax.sql.*;
import javax.naming.*;
import java.util.*;
import com.Trustwin.Admin.Project.Category.*;
import com.Trustwin.Admin.Project.Device.*;
import com.Trustwin.Admin.Project.Language.*;

public final class AllDeviceList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var change = 0;\r\n");
      out.write("function allDeviceInfoCheck(){\r\n");
      out.write("\tvar check = document.deviceInfo.check;\r\n");
      out.write("\tif(check.value != 'undefine'){\r\n");
      out.write("\t\tif(change == 0){\r\n");
      out.write("\t\t\tcheck.checked = true;\t\r\n");
      out.write("\t\t\tchange = 1;\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tcheck.checked = false;\r\n");
      out.write("\t\t\tchange = 0;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tif(change == 0){\r\n");
      out.write("\t\t\tfor(var i = 0 ; i < check.length;i++ ){\r\n");
      out.write("\t\t\t\tcheck[i].checked = true;\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\tchange = 1;\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tfor(var i = 0 ; i < check.length;i++ ){\r\n");
      out.write("\t\t\t\tcheck[i].checked = false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tchange = 0;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function checkedF(num,v){\r\n");
      out.write("\tvar count = 0;\r\n");
      out.write("\tvar array = new Array();\r\n");
      out.write("\tvar check = document.deviceInfo.check;\r\n");
      out.write("\tfor(var i = 0; i< check.length; i++){\r\n");
      out.write("\t\tif(check[i].checked){\r\n");
      out.write("\t\t\tarray[count] = check[i].value;\r\n");
      out.write("\t\t\tcount++;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif(v==1){ // 전송\r\n");
      out.write("\t\tif(num==count){\r\n");
      out.write("\t\t\tEnroll('S,D,E,0,E');\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tvar value = 'S,D,E,1,';\r\n");
      out.write("\t\t\tfor(var i=0;i<count;i++){\r\n");
      out.write("\t\t\t\tvalue = value + array[i] + ',';\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tvalue = value + 'E';\r\n");
      out.write("\t\t\tEnroll(value);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}else{\t// 삭제\r\n");
      out.write("\t\tif(num==count){\r\n");
      out.write("\t\t\tDelete('S,D,D,0,E');\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tvar value = 'S,D,D,1,';\r\n");
      out.write("\t\t\tfor(var i=0;i<count;i++){\r\n");
      out.write("\t\t\t\tvalue = value + array[i] + ',';\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tvalue = value + 'E';\r\n");
      out.write("\t\t\tDelete(value);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<div id=\"userdata\">\r\n");

	request.setCharacterEncoding("utf-8");
	Connection conn = null;
	String ControllerName = (String)request.getParameter("searchControllerName");
	if(ControllerName != null){
		ControllerName = new String(ControllerName.getBytes("8859_1"), "UTF-8");	
	}
	String Address = (String)request.getParameter("searchAddress");
	if(Address != null){
		Address = new String(Address.getBytes("8859_1"), "UTF-8");	
	}
	
	String ID = (String)request.getParameter("searchID");
	if(ID != null){
		ID = new String(ID.getBytes("8859_1"), "UTF-8");	
	}
	
	String UniqueID = (String)request.getParameter("searchUniqueID");
	if((String)request.getParameter("searchUniqueID")!=null){
		UniqueID = new String(UniqueID.getBytes("8859_1"), "UTF-8");
	}
	
	CategoryFunc Catefunc = new CategoryFunc();
	LanguageFunc Lanfunc = new LanguageFunc();
	DeviceFunc Devfunc = new DeviceFunc();
	Device[] devices = Devfunc.searchDevice(ControllerName,Address,ID,UniqueID);
	String lan = (String)session.getAttribute("nation");

      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<section class = \"sectionji\">\r\n");
      out.write("\t\t\t\t<ul class = \"ulji\">\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<form action=\"/TrustWinPro/action/index.jsp\" name=\"allDevice\" id=\"allDevice\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" value=\"Device\" name=\"left\"/>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" value=\"AllDevice\" name=\"content\" />\r\n");
      out.write("\t\t\t\t\t\t<p><div class = \"headerji\">\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(Lanfunc.language(lan, 1));
      out.write(" : \r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"searchControllerName\"\r\n");
      out.write("\t\t\t\t\t\tclass = \"inputt\" value=\"");
      out.print(LangUtil.Empty(ControllerName));
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<p><div class = \"headerji\">\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(Lanfunc.language(lan, 3));
      out.write(" : \r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"searchAddress\" class = \"inputt\" value=\"");
      out.print(LangUtil.Empty(Address));
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<p><div class = \"headerji\">\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(Lanfunc.language(lan, 2));
      out.write(" : \r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"searchID\" class = \"inputt\" value=\"");
      out.print(LangUtil.Empty(ID));
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<p><div class = \"headerji\">\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(Lanfunc.language(lan, 6));
      out.write(" : \r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"searchUniqueID\" class = \"inputt\" value=\"");
      out.print(LangUtil.Empty(UniqueID));
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" name=\"submit\" value=\"");
      out.print(Lanfunc.language(lan, 182));
      out.write("\" \r\n");
      out.write("\t\t\t\t\t\tclass=\"ct-btn white\" style =\"margin-left:160px\"/>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div style=\"float:right; margin-right:20px\"\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#a\" onclick=\"DevicePrint();\"><img src=\"/TrustWinPro/action/image/interface/printImage.jpg\" alt=\"\" ></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t<!--<div class=\"searchForm\">\r\n");
      out.write("\t</div> !-->\r\n");
      out.write("\r\n");
      out.write("\t<form action=\"\" name=\"deviceInfo\" id=\"deviceInfo\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("\t<div class = \"tablebor\">\r\n");
      out.write("\t\t<table cellspacing=\"0\" class=\"titleEx1\">\r\n");
      out.write("\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t<col width=\"14%\">\r\n");
      out.write("\t\t\t\t<col width=\"12%\">\r\n");
      out.write("\t\t\t\t<col width=\"12%\">\r\n");
      out.write("\t\t\t</colgroup>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>");
      out.print(Lanfunc.language(lan, 85));
      out.write("<input type=\"checkbox\" name=\"allcheck\" onclick=\"allDeviceInfoCheck();\" value=\"\"></th>\r\n");
      out.write("\t\t\t\t<th>");
      out.print(Lanfunc.language(lan, 1));
      out.write("</th>\r\n");
      out.write("\t\t\t\t<th>");
      out.print(Lanfunc.language(lan, 2));
      out.write("</th>\r\n");
      out.write("\t\t\t\t<th>");
      out.print(Lanfunc.language(lan, 3));
      out.write("</th>\r\n");
      out.write("\t\t\t\t<th>");
      out.print(Lanfunc.language(lan, 4));
      out.write("</th>\r\n");
      out.write("\t\t\t\t<th>");
      out.print(Lanfunc.language(lan, 5));
      out.write("</th>\r\n");
      out.write("\t\t\t\t<th>");
      out.print(Lanfunc.language(lan, 6));
      out.write("</th>\r\n");
      out.write("\t\t\t\t<th>");
      out.print(Lanfunc.language(lan, 7));
      out.write("</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<table cellspacing=\"0\"  class=\"ex1\">\r\n");
      out.write("\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t<col width=\"14%\">\r\n");
      out.write("\t\t\t\t<col width=\"12%\">\r\n");
      out.write("\t\t\t\t<col width=\"12%\">\r\n");
      out.write("\t\t\t</colgroup>\r\n");
      out.write("\t\t\t<tbody>\r\n");

		for(int i=0;i<devices.length;i++){

      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"checkbox\" name=\"check\" value=\"");
      out.print(devices[i].getID());
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t<td class='date1'><a href=\"#a\" onclick=\"submitDevice('Device','");
      out.print(devices[i].getID() );
      out.write("')\">");
      out.print(devices[i].getControllerName() );
      out.write("</a></td>\r\n");
      out.write("\t\t\t\t\t<td class='date1'>");
      out.print(devices[i].getID() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td class='date1'>");
      out.print(devices[i].getAddress() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td class='date1'>");
      out.print(devices[i].getPort() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td class='date1'>");
      out.print(devices[i].getPassword() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td class='date1'>");
      out.print(devices[i].getUniqueID() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td class='date1'>");
      out.print(devices[i].getServerPort() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");

		}

      out.write("\t\r\n");
      out.write("\t\t\t</tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"bottom\" id=\"web-buttons-idrmij3\">\r\n");
      out.write("\t\t\t<a href=\"#\" title=\"Enroll\" onclick=\"checkedF(");
      out.print(devices.length );
      out.write(",2);\">");
      out.print(Lanfunc.language(lan, 88));
      out.write("</a>\r\n");
      out.write("\t\t\t<a href=\"#\" title=\"Delete\" onclick=\"checkedF(");
      out.print(devices.length );
      out.write(",1);\">");
      out.print(Lanfunc.language(lan, 183));
      out.write("</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>\r\n");
      out.write("<form action=\"/TrustWinPro/action/index.jsp\" name=\"Device\" id=\"Device\" method=\"post\">\r\n");
      out.write("\t<input type=\"hidden\" value=\"Device\" name=\"left\" />\r\n");
      out.write("\t<input type=\"hidden\" value=\"\" name=\"deviceID\" />\r\n");
      out.write("\t<input type=\"hidden\" value=\"DeviceInfo\" name=\"content\" />\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
