/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2015-12-10 06:51:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.action.page;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.Trustwin.Admin.Project.Device.*;
import com.Trustwin.Admin.Project.Event.*;

public final class barChart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://www.google.com/jsapi\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    \r\n");
      out.write("    google.load('visualization', '1', {packages: ['corechart'],'language':'ko'});\r\n");
      out.write("     \r\n");
      out.write("    \tfunction fn_submit() { \r\n");
      out.write("    \tdocument.chartOption.submit(); \r\n");
      out.write("    \t} \r\n");
      out.write("    \r\n");
      out.write("    function drawVisualization(dataFromAjax) {\r\n");
      out.write("         var data = google.visualization.arrayToDataTable(dataFromAjax);\r\n");
      out.write("         var options = {\r\n");
      out.write("                 title: '출입 인원',\r\n");
      out.write("                 vAxis: {title: 'device',  titleTextStyle: {color: 'black'}}\r\n");
      out.write("               };\r\n");
      out.write("         \r\n");
      out.write("         var chart = new google.visualization.BarChart(document.getElementById('chart_div'));\r\n");
      out.write("         chart.draw(data, options);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function drawInit()\r\n");
      out.write("    {\r\n");
      out.write("         var data = null;\r\n");
      out.write("         var table_data = null;\r\n");
      out.write("\r\n");
      out.write("         $.ajax({\r\n");
      out.write("             url:'/TrustWinPro/action/ajax/barChartProc.jsp',\r\n");
      out.write("             data: 'idx=',\r\n");
      out.write("             success: function(res) {\r\n");
      out.write("                 table_data = eval(\"(\" + res + \")\");\r\n");
      out.write("                 drawVisualization(table_data);\r\n");
      out.write("             }\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function statusBar()\r\n");
      out.write("    {\r\n");
      out.write("    \tvar array = document.barChart.check;\r\n");
      out.write("    \tvar val = \"\";\r\n");
      out.write("    \tfor(var i=0;i<array.length;i++){\r\n");
      out.write("    \t\tif(array[i].checked == true){\r\n");
      out.write("    \t\t\tval = val + array[i].value + \",\";\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t}\r\n");
      out.write("    \talert(val);\r\n");
      out.write("         $.ajax({\r\n");
      out.write("             url:'/TrustWinPro/action/ajax/barStatusProc.jsp',\r\n");
      out.write("             data: 'val='+val,\r\n");
      out.write("             success: function(res) {\r\n");
      out.write("            \t document.getElementById(\"barChart\").submit();\r\n");
      out.write("             }\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function statusWindowBar(){\r\n");
      out.write("    \tif(document.getElementById(\"chart_div\").style.display == \"none\"){\r\n");
      out.write("    \t\tdocument.getElementById(\"chart_div\").style.display = \"block\";\t\r\n");
      out.write("    \t\tdocument.getElementById(\"chart_div_S\").style.display = \"none\";\t\r\n");
      out.write("    \t}else{\r\n");
      out.write("    \t\tdocument.getElementById(\"chart_div\").style.display = \"none\";\r\n");
      out.write("    \t\tdocument.getElementById(\"chart_div_S\").style.display = \"block\";\t\r\n");
      out.write("    \t}\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    google.setOnLoadCallback(drawInit);\r\n");
      out.write(" \r\n");
      out.write("   drawInit();\r\n");
      out.write("</script> \r\n");
      out.write("\r\n");
      out.write("<div  style=\"width:100%; height:6px; font-size:0;  padding:2;\" >\r\n");
      out.write("\t\r\n");
      out.write("\t<a href=\"#a\" onclick=\"statusWindowBar()\"><input type=\"image\" src=\"/TrustWinPro/action/image/setting.png\" style=\"width:20px; height:20px; float:right\"/></a>\r\n");
      out.write("</div>\r\n");
      out.write("<br>\r\n");
      out.write("<div>\r\n");
      out.write("\t<section style = \"overflow: hidden;border: 2px solid #46bebe; border-radius: 6px;-webkit-box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.15);\r\n");
      out.write("\t\tbox-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.15);background: #fff; width: 100%;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t<ul style = \"height: 45px;\r\n");
      out.write("\t\tborder-bottom: 1px solid #f2f2f2;\r\n");
      out.write("\t\tposition: relative;\r\n");
      out.write("\t\theight: 44px;\r\n");
      out.write("\t\tbackground: #72c8cd;\r\n");
      out.write("\t\tlist-style: none;\r\n");
      out.write("\t\tmargin: 0;\r\n");
      out.write("\t\tpadding: 0;\r\n");
      out.write("\t\tcolor: #5a5a5a;\r\n");
      out.write("\t\tfont: normal 12px/0.9 Roboto, 'Nanum Gothic', '돋움', Dotum, '굴림', Gulim, sans-serif;\r\n");
      out.write("\t\tletter-spacing: 0.03em;\">\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"chart_div\" ></div>\r\n");
      out.write("\t</section>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"chart_div_S\" id=\"chart_div_S\" style = \"position: relative;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 200px;\r\n");
      out.write("    padding: 0 0 20px 0;\r\n");
      out.write("    margin: 0 0 20px 0;\r\n");
      out.write("    border: 1px solid #b4b4b4;\r\n");
      out.write("    border-radius: 6px;\r\n");
      out.write("    -webkit-box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.15);\r\n");
      out.write("    box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.15);\r\n");
      out.write("    background: #fff;\">\r\n");
      out.write("\t<form action=\"/TrustWinPro/action/index.jsp\" name=\"barChart\" id=\"barChart\" method=\"post\">\r\n");
      out.write("\t\t<div class=\"chart_table\">\r\n");
      out.write("\t\t\t<table cellspacing=\"0\"  class=\"titleEx1\">\r\n");
      out.write("\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t<col width=\"50%\">\r\n");
      out.write("\t\t\t\t\t<col width=\"50%\">\r\n");
      out.write("\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>DeviceName</th>\r\n");
      out.write("\t\t\t\t\t<th>Select</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<table cellspacing=\"0\"  class=\"ex1\">\r\n");
      out.write("\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t<col width=\"50%\">\r\n");
      out.write("\t\t\t\t\t<col width=\"50%\">\r\n");
      out.write("\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t<tbody>\r\n");

	DeviceFunc DFunc = new DeviceFunc();
	Device[] dev = DFunc.searchDevice(null,null,null,null);
	EventFunc EFunc = new EventFunc();
	String barchart = EFunc.barChartVal();
	String[] barcharts = barchart.split(",");
	for(int i=0;i<dev.length;i++){
		String status = "";
		for(int j=0;j<barcharts.length;j++){
			if(dev[i].getUniqueID().equals(barcharts[j])){
				status = "checked";
				break;
			}
		}

      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(dev[i].getControllerName());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"checkbox\" id=\"check\" name=\"check\" value=\"");
      out.print(dev[i].getUniqueID() );
      out.write('"');
      out.write(' ');
      out.print(status );
      out.write("></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");

	}

      out.write("\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<div class=\"bottom\" id=\"web-buttons-idrmij3\">\r\n");
      out.write("\t\t\t\t<a href=\"#\" title=\"Enroll\" onclick=\"statusBar()\">submit</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
