/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2015-12-24 05:07:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.action.page;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import javax.sql.*;
import javax.naming.*;
import com.Trustwin.Admin.Project.Category.*;
import com.Trustwin.Admin.Project.Holiday.*;
import com.Trustwin.Admin.Project.Language.*;

public final class HoliDay_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	HoliDayFunc Holfunc = new HoliDayFunc();
	CategoryFunc Catefunc = new CategoryFunc();
	LanguageFunc Lanfunc = new LanguageFunc();
	HoliDay[] holi = Holfunc.selHoliDay();
	String lan = (String)session.getAttribute("nation");

      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var change = 0;\r\n");
      out.write("\r\n");
      out.write("function HoliDayAdd(){\r\n");
      out.write("\tvar name = document.getElementById(\"AddName\").value;\r\n");
      out.write("\tvar date = document.getElementById(\"AddDate\").value;\r\n");
      out.write("\tif(name == \"\" || date == \"\"){\r\n");
      out.write("\t\talert(\"");
      out.print(Lanfunc.language(lan, 118) );
      out.write("\");\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tvar used = 1;\r\n");
      out.write("\t\t$.ajax({      \r\n");
      out.write("\t\t    type:\"post\",  \r\n");
      out.write("\t\t    url:\"/TrustWinPro/action/ajax/HoliDayAdd.jsp\",   \r\n");
      out.write("\t\t    data: \"name=\"+name + \"&date=\"+date+\"&used=\" + used ,\r\n");
      out.write("\t\t    success:function(args){\r\n");
      out.write("\t\t    \tdocument.getElementById(\"Holiday\").submit();\r\n");
      out.write("\t\t    },   \r\n");
      out.write("\t\t    error:function(e){  \r\n");
      out.write("\t\t        alert(e.responseText);  \r\n");
      out.write("\t\t    }  \r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function HoliDayDel(){\r\n");
      out.write("\tdocument.getElementById(\"HoliDay\").submit();\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function HoliDayAllDel(){\r\n");
      out.write("\tdocument.getElementById(\"AllDelHoliday\").submit();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function HoliDayModify(){\r\n");
      out.write("\tdocument.getElementById(\"HoliDay\").action = \"page/HoliDayChange.jsp\";\r\n");
      out.write("\tdocument.getElementById(\"HoliDay\").submit();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function allCheck(){\r\n");
      out.write("\tvar check = document.HoliDay.check;\r\n");
      out.write("\tif(check.value != 'undefine'){\r\n");
      out.write("\t\tif(change == 0){\r\n");
      out.write("\t\t\tcheck.checked = true;\t\r\n");
      out.write("\t\t\tchange = 1;\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tcheck.checked = false;\r\n");
      out.write("\t\t\tchange = 0;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tif(change == 0){\r\n");
      out.write("\t\t\tfor(var i = 0 ; i < check.length;i++ ){\r\n");
      out.write("\t\t\t\tcheck[i].checked = true;\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\tchange = 1;\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tfor(var i = 0 ; i < check.length;i++ ){\r\n");
      out.write("\t\t\t\tcheck[i].checked = false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tchange = 0;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\t\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");


      out.write("\r\n");
      out.write("<div id=\"HoliInfo\">\r\n");
      out.write("\t<div class=\"basic\">\r\n");
      out.write("\r\n");
      out.write("\t<section class = \"sectionji\">\r\n");
      out.write("\t\t\t<ul class = \"ulji\">\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"basicInfo\">\r\n");
      out.write("\t\t\t<form name=\"HoliDay\" id=\"HoliDay\" method=\"post\" action=\"page/HoliDayDel.jsp\">\r\n");
      out.write("\t\t\t\t<div class=\"left\">\r\n");
      out.write("\t\t\t\t\t<div class=\"block\">\r\n");
      out.write("\t\t\t\t\t\t<table border=1 cellspacing=\"0\" class=\"titleEx1\">\r\n");
      out.write("\t\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"25%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"25%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"25%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"25%\">\r\n");
      out.write("\t\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>");
      out.print(Lanfunc.language(lan, 83) );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>");
      out.print(Lanfunc.language(lan, 71) );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>");
      out.print(Lanfunc.language(lan, 84) );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>");
      out.print(Lanfunc.language(lan, 167) );
      out.write("<input type=\"checkbox\" name=\"allcheck\" id=\"allcheck\" onclick=\"allCheck();\" ></th>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t<table cellspacing=\"0\"  class=\"ex1\">\r\n");
      out.write("\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"25%\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"25%\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"25%\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"25%\">\r\n");
      out.write("\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");

	for(int i=0;i<holi.length;i++){
		if(i%2==0){
			out.println("<tr  class='odd'>");
		}else{
			out.println("<tr>");	
		}

      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class='date1'>");
      out.print(holi[i].getHolidayName() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class='date1'>");
      out.print(holi[i].getHolidayDate() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class='date1'>");
      out.print(holi[i].getUsed().equals("1")?Lanfunc.language(lan, 168):Lanfunc.language(lan, 169) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class='date1'><input type=\"checkbox\" name=\"check\" id=\"check\" value=\"");
      out.print(holi[i].getHolidayDate());
      out.write("\" ></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");

	}

      out.write("\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"right\">\r\n");
      out.write("\t\t\t\t<div class=\"buttom\"><a href=\"#content\" onclick=\"HoliDayDel();\"><img src=\"/TrustWinPro/action/image/interface/statusbar.png\" style=\"width:100px;\"><span style=\"position:absolute;left:35px;top:15px;\">");
      out.print(Lanfunc.language(lan, 88) );
      out.write("</span></a></div>\r\n");
      out.write("\t\t\t\t<div class=\"buttom\"><a href=\"#content\" onclick=\"HoliDayModify();\"><img src=\"/TrustWinPro/action/image/interface/statusbar.png\" style=\"width:100px;position:absolute;\"><span class=\"text\">");
      out.print(Lanfunc.language(lan, 89) );
      out.write("</span></a></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"dataAdd\">\r\n");
      out.write("\t\t\t<div class=\"text\">");
      out.print(Lanfunc.language(lan, 83) );
      out.write("</div>\r\n");
      out.write("\t\t\t<div class=\"input\"><input type=\"text\" name=\"AddName\" id=\"AddName\" value=\"\" size=\"40um\" ></div>\r\n");
      out.write("\t\t\t<div class=\"text\">");
      out.print(Lanfunc.language(lan, 71) );
      out.write("</div>\r\n");
      out.write("\t\t\t<div class=\"input\"><input type=\"text\" name=\"AddDate\" id=\"AddDate\" readonly=\"readOnly\" value=\"\" size=\"40um\" onclick=\"fnPopUpCalendar(AddDate,AddDate,'yyyy-mm-dd')\"></div>\r\n");
      out.write("\t\t\t<div class=\"buttom\" ><a href=\"#content\" onclick=\"HoliDayAdd();\"><img src=\"/TrustWinPro/action/image/interface/statusbar.png\" style=\"width:80px;position:absolute;\"><span class=\"text\">");
      out.print(Lanfunc.language(lan, 90) );
      out.write("</span></a></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<form name=\"AllDelHoliday\" id=\"AllDelHoliday\" method=\"post\" action=\"page/HoliDayAllDel.jsp\" >\r\n");
      out.write("</form>\r\n");
      out.write("<form action=\"/TrustWinPro/action/index.jsp\" name=\"Holiday\" id=\"Holiday\" method=\"post\">\r\n");
      out.write("\t<input type=\"hidden\" value=\"Time\" name=\"left\" />\r\n");
      out.write("\t<input type=\"hidden\" value=\"Holiday\" name=\"content\" />\r\n");
      out.write("</form>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
