/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2015-10-06 04:50:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.action.page;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import javax.sql.*;
import javax.naming.*;
import com.Trustwin.Admin.Project.Event.*;
import com.Trustwin.Admin.Project.Language.*;
import com.Trustwin.Admin.Project.Category.*;

public final class Log_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String SDate = (String)request.getParameter("searchStartDate")==null?"":request.getParameter("searchStartDate");
	String EDate = (String)request.getParameter("searchEndDate")==null?"":request.getParameter("searchEndDate");
	String SHour = (String)request.getParameter("searchStartHour")==null?"":request.getParameter("searchStartHour");
	String SMin = (String)request.getParameter("searchStartMinute")==null?"":request.getParameter("searchStartMinute");
	String SSec = (String)request.getParameter("searchStartSec")==null?"":request.getParameter("searchStartSec");
	String EHour = (String)request.getParameter("searchEndHour")==null?"":request.getParameter("searchEndHour");
	String EMin = (String)request.getParameter("searchEndMinute")==null?"":request.getParameter("searchEndMinute");
	String ESec = (String)request.getParameter("searchEndSec")==null?"":request.getParameter("searchEndSec");
	String Name = (String)request.getParameter("searchName");
	String User = (String)request.getParameter("searchUser");
	String Month = (String)request.getParameter("month");
	
	String Num = "30";
	LanguageFunc Lanfunc = new LanguageFunc();
	EventFunc Evtfunc = new EventFunc();
	
	if(request.getParameter("Num")!=null){
		if(!request.getParameter("Num").equals("")){
			Num = (String)request.getParameter("Num");
		}
	}
	String lan = (String)session.getAttribute("nation");
	
	String STime = "";
	String ETime = "";
	
	if(SHour == null || SMin == null || SSec == null || EHour == null || EMin == null || ESec == null){
		SHour = "";
		SMin = "";
		SSec = "";
		EHour = "";
		EMin = "";
		ESec = "";
	}else{
		if((!SHour.equals("")&&!SHour.equals("null"))||(!SMin.equals("")&&!SMin.equals("null"))||(!SSec.equals("")&&!SSec.equals("null"))||(!EHour.equals("")&&!EHour.equals("null"))||(!EMin.equals("")&&!EMin.equals("null"))||(!ESec.equals("")&&!ESec.equals("null"))){
	if((!SHour.equals("0")&&!EHour.equals("0"))){
		if(Integer.parseInt(SHour)<10){
	SHour = "0" + SHour;
		}
		if(Integer.parseInt(SMin)<10){
	SMin = "0" + SMin;
		}
		if(Integer.parseInt(SSec)<10){
	SSec = "0" + SSec;
		}
		if(Integer.parseInt(EHour)<10){
	EHour = "0" + EHour;
		}
		if(Integer.parseInt(EMin)<10){
	EMin = "0" + EMin;
		}
		if(Integer.parseInt(ESec)<10){
	ESec = "0" + ESec;
		}
		STime = SHour+":"+SMin+":"+SSec;
		ETime = EHour+":"+EMin+":"+ESec;
	}
		}
	}

      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("function refresh(){\r\n");
      out.write("\t$.ajax({      \r\n");
      out.write("\t    type:\"post\",  \r\n");
      out.write("\t    url:\"/TrustWinPro/action/ajax/LogA.jsp\",   \r\n");
      out.write("\t    data: \"num=");
      out.print(Num);
      out.write("&searchStartDate=");
      out.print(SDate);
      out.write("&searchEndDate=");
      out.print(EDate);
      out.write("&searchStartHour=");
      out.print(SHour);
      out.write("&searchStartMinute=");
      out.print(SMin);
      out.write("&searchStartSec=");
      out.print(SSec);
      out.write("&searchEndHour=");
      out.print(EHour);
      out.write("&searchEndMinute=");
      out.print(EMin);
      out.write("&searchEndSec=");
      out.print(ESec);
      out.write("&searchName=");
      out.print(Name);
      out.write("&searchUser=");
      out.print(User);
      out.write("&month=");
      out.print(Month);
      out.write("\",\r\n");
      out.write("\t    success:function(args){   \r\n");
      out.write("\t        $(\"#logdata\").html(args);      \r\n");
      out.write("\t    },   \r\n");
      out.write("\t    error:function(e){  \r\n");
      out.write("\t        alert(e.responseText);  \r\n");
      out.write("\t    }  \r\n");
      out.write("\t});  \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function optionSubmit(){\r\n");
      out.write("\tvar count = 0;\r\n");
      out.write("\tvar array = \"\";\r\n");
      out.write("\tvar arrayName = \"\";\r\n");
      out.write("\tvar check = document.colorO.check;\r\n");
      out.write("\tvar name = document.colorO.colorName;\r\n");
      out.write("\tfor(var i = 0; i< check.length; i++){\r\n");
      out.write("\t\tif(check[i].checked){\r\n");
      out.write("\t\t\tarray = array + \"1\" + check[i].value + \",\";\r\n");
      out.write("\t\t\tarrayName = arrayName + name[i].value + \",\";\r\n");
      out.write("\t\t\tcount++;\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tarray = array + \"0\" + check[i].value + \",\"\r\n");
      out.write("\t\t\tarrayName = arrayName + name[i].value + \",\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({      \r\n");
      out.write("\t    type:\"post\",  \r\n");
      out.write("\t    url:\"/TrustWinPro/action/ajax/ColorOption.jsp\",   \r\n");
      out.write("\t    data: \"array=\" + array + \"&color=\"+arrayName,\r\n");
      out.write("\t    success:function(args){   \r\n");
      out.write("\t    \tdocument.getElementById(\"colorO\").submit();\r\n");
      out.write("\t    },   \r\n");
      out.write("\t    error:function(e){  \r\n");
      out.write("\t        alert(e.responseText);  \r\n");
      out.write("\t    }  \r\n");
      out.write("\t});  \r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function closeColor(){\r\n");
      out.write("\tdocument.getElementById(\"colorOption\").style.display = \"none\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function openColor(){\r\n");
      out.write("\tif(document.getElementById(\"colorOption\").style.display == \"none\"){\r\n");
      out.write("\t\tdocument.getElementById(\"colorOption\").style.display = \"block\";\t\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tdocument.getElementById(\"colorOption\").style.display = \"none\";\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("refresh();\r\n");
      out.write("$(document).attr(\"timer\",setInterval(refresh,1000));\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<div id=\"userdata\">\r\n");
      out.write("\t<div class=\"searchForm\">\r\n");
      out.write("\t\t<form action=\"/TrustWinPro/action/index.jsp\" name=\"allEvent\" id=\"allEvent\" method=\"post\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" value=\"realLog\" name=\"logtype\" />\r\n");
      out.write("\t\t\t<input type=\"hidden\" value=\"Log\" name=\"content\" />\r\n");
      out.write("\t\t\t<input type=\"hidden\" value=\"");
      out.print(STime );
      out.write("\" name=\"STime\" />\r\n");
      out.write("\t\t\t<input type=\"hidden\" value=\"");
      out.print(ETime );
      out.write("\" name=\"ETime\" />\r\n");
      out.write("\t\t\t<input type=\"hidden\" value=\"");
      out.print(SDate );
      out.write("\" name=\"SDate\" />\r\n");
      out.write("\t\t\t<input type=\"hidden\" value=\"");
      out.print(EDate );
      out.write("\" name=\"EDate\" />\r\n");
      out.write("\t\t\t");
      out.print(Lanfunc.language(lan, 71));
      out.write(" : <input type=\"text\" name=\"searchStartDate\" id=\"searchStartDate\" readonly=\"readOnly\" value=\"");
      out.print(LangUtil.Empty(SDate));
      out.write("\" readonly=\"readOnly\" onclick=\"fnPopUpCalendar(searchStartDate,searchStartDate,'yyyy-mm-dd')\" /> \r\n");
      out.write("\t\t\t~ <input type=\"text\" name=\"searchEndDate\" id=\"searchEndDate\" readonly=\"readOnly\" value=\"");
      out.print(LangUtil.Empty(EDate));
      out.write("\" readonly=\"readOnly\" onclick=\"fnPopUpCalendar(searchEndDate,searchEndDate,'yyyy-mm-dd')\" />\r\n");
      out.write("\t\t\t");
      out.print(Lanfunc.language(lan, 106));
      out.write(" : \r\n");
      out.write("\t\t\t<select name=\"searchStartHour\" id=\"searchStartHour\">\r\n");
      out.write("\t\t\t\t<option value=\"0\" >0</option>\r\n");

	for(int i=1;i<25;i++){

      out.write("\r\n");
      out.write("\t\t\t\t<option value=\"");
      out.print(i);
      out.write('"');
      out.write(' ');
      out.print(SHour.equals(Integer.toString(i)) ?"selected":"");
      out.write(' ');
      out.write('>');
      out.print(i);
      out.write("</option>\r\n");

	}

      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t<select name=\"searchStartMinute\" id=\"searchStartMinute\">\r\n");
      out.write("\t\t\t\t<option value=\"0\" >00</option>\r\n");

	for(int i=1;i<61;i++){

      out.write("\r\n");
      out.write("\t\t\t\t<option value=\"");
      out.print(i);
      out.write('"');
      out.write(' ');
      out.print(SMin.equals(Integer.toString(i)) ?"selected":"");
      out.write(' ');
      out.write('>');
      out.print(i);
      out.write("</option>\r\n");

	}

      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<select name=\"searchStartSec\" id=\"searchStartSec\">\r\n");
      out.write("\t\t\t\t<option value=\"0\" >00</option>\r\n");

	for(int i=1;i<61;i++){

      out.write("\r\n");
      out.write("\t\t\t\t<option value=\"");
      out.print(i);
      out.write('"');
      out.write(' ');
      out.print(SSec.equals(Integer.toString(i)) ?"selected":"");
      out.write(' ');
      out.write('>');
      out.print(i);
      out.write("</option>\r\n");

	}

      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t~\r\n");
      out.write("\t\t\t<select name=\"searchEndHour\" id=\"searchEndHour\">\r\n");
      out.write("\t\t\t\t<option value=\"0\" >0</option>\r\n");

	for(int i=1;i<25;i++){

      out.write("\r\n");
      out.write("\t\t\t\t<option value=\"");
      out.print(i);
      out.write('"');
      out.write(' ');
      out.print(EHour.equals(Integer.toString(i)) ?"selected":"");
      out.write(' ');
      out.write('>');
      out.print(i);
      out.write("</option>\r\n");

	}

      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<select name=\"searchEndMinute\" id=\"searchEndMinute\">\r\n");
      out.write("\t\t\t\t<option value=\"0\" >00</option>\r\n");

	for(int i=1;i<61;i++){

      out.write("\r\n");
      out.write("\t\t\t\t<option value=\"");
      out.print(i);
      out.write('"');
      out.write(' ');
      out.print(EMin.equals(Integer.toString(i)) ?"selected":"");
      out.write(' ');
      out.write('>');
      out.print(i);
      out.write("</option>\r\n");

	}

      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<select name=\"searchEndSec\" id=\"searchEndSec\">\r\n");
      out.write("\t\t\t\t<option value=\"0\" >00</option>\r\n");

	for(int i=1;i<61;i++){

      out.write("\r\n");
      out.write("\t\t\t\t<option value=\"");
      out.print(i);
      out.write('"');
      out.write(' ');
      out.print(ESec.equals(Integer.toString(i)) ?"selected":"");
      out.write(' ');
      out.write('>');
      out.print(i);
      out.write("</option>\r\n");

	}

      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t<br/>\r\n");
      out.write("\t\t\t");
      out.print(Lanfunc.language(lan, 81));
      out.write(" : <input type=\"text\" name=\"searchName\" value=\"");
      out.print(LangUtil.Empty(Name));
      out.write("\" /> ");
      out.print(Lanfunc.language(lan, 108));
      out.write(" : <input type=\"text\" name=\"searchUser\" value=\"");
      out.print(LangUtil.Empty(User));
      out.write("\" />\r\n");
      out.write("\t\t\t<input name=\"content\" type=\"hidden\" value=\"Log\" />\r\n");
      out.write("\t\t\t");
      out.print(Lanfunc.language(lan, 91));
      out.write("\r\n");
      out.write("\t\t\t<input name=\"Num\" type=\"text\" value=\"");
      out.print(Num);
      out.write("\" size=\"20\" />\r\n");
      out.write("\t\t\t<input type=\"submit\" name=\"submit\" value=\"");
      out.print(Lanfunc.language(lan, 182));
      out.write("\" class=\"ct-btn white\" />\r\n");
      out.write("\t\t\t<span style=\"position:relative;padding:2px;\"><a href=\"#a\" onclick=\"EventPrint();\"><img src=\"/TrustWinPro/action/image/interface/printImage.jpg\" alt=\"\" style=\"position:absolute;\"></a></span>\r\n");
      out.write("\t\t\t<span><a href=\"#\" onclick=\"openColor();\" ><img src=\"/TrustWinPro/action/image/interface/option.png\" alt=\"\" style=\"width:22px;position:absolute;right:5px;\"/></a></span>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"colorOption\" id=\"colorOption\">\r\n");
      out.write("\t<form action=\"/TrustWinPro/action/index.jsp\" name=\"colorO\" id=\"colorO\" method=\"post\">\r\n");
      out.write("\t\t<table cellspacing=\"0\"  class=\"titleEx1\">\r\n");
      out.write("\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t<col width=\"20%\">\r\n");
      out.write("\t\t\t\t<col width=\"40%\">\r\n");
      out.write("\t\t\t\t<col width=\"40%\">\r\n");
      out.write("\t\t\t</colgroup>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>Type</th>\r\n");
      out.write("\t\t\t\t<th>Display</th>\r\n");
      out.write("\t\t\t\t<th>Color</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<table cellspacing=\"0\"  class=\"ex1\">\r\n");
      out.write("\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t<col width=\"20%\">\r\n");
      out.write("\t\t\t\t<col width=\"40%\">\r\n");
      out.write("\t\t\t\t<col width=\"40%\">\r\n");
      out.write("\t\t\t</colgroup>\r\n");
      out.write("\t\t\t<tbody>\r\n");

	EventOption[] eo = Evtfunc.selOption();
	for(int i=0; i < eo.length;i++){

      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(eo[i].getType() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"checkbox\" value=\"");
      out.print(eo[i].getIdx());
      out.write("\" name=\"check\" ");
      out.print(eo[i].getDisplay().equals("1")?"checked":"" );
      out.write("></td>\r\n");
      out.write("\t\t\t\t<td><input class=\"color\" name=\"colorName\" value=\"");
      out.print(eo[i].getColor() );
      out.write("\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");

	}

      out.write("\r\n");
      out.write("\t\t\t</tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<div class=\"button\" id=\"web-buttons-idrmij3\">\r\n");
      out.write("\t\t\t<a href=\"#\"  onclick=\"closeColor();\">");
      out.print(Lanfunc.language(lan, 185));
      out.write("</a>\r\n");
      out.write("\t\t\t<a href=\"#\"  onclick=\"optionSubmit();\">");
      out.print(Lanfunc.language(lan, 92));
      out.write("</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"logdata\">\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
