/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2015-04-06 01:52:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.action.page;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import javax.sql.*;
import javax.naming.*;
import java.util.*;
import com.Trustwin.Admin.Project.Category.*;
import com.Trustwin.Admin.Project.Language.*;

public final class LogSearch_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"userdata\">\r\n");

	Connection conn = null;
	String SDate = (String)request.getParameter("searchStartDate");
	String EDate = (String)request.getParameter("searchEndDate");
	String SHour = (String)request.getParameter("searchStartHour");
	String SMin = (String)request.getParameter("searchStartMinute");
	String SSec = (String)request.getParameter("searchStartSec");
	String EHour = (String)request.getParameter("searchEndHour");
	String EMin = (String)request.getParameter("searchEndMinute");
	String ESec = (String)request.getParameter("searchEndSec");
	String Name = (String)request.getParameter("searchName");
	String User = (String)request.getParameter("searchUser");
	String Month = (String)request.getParameter("month");
	
	CategoryFunc func = new CategoryFunc();
	LanguageFunc Lanfunc = new LanguageFunc();
	
	String lan = (String)session.getAttribute("nation");
	if(Month != null){
		if(Integer.parseInt(Month) > 9){
	
		}else{
	Month = "0" + Month;
		}
	}
	String Year = (String)request.getParameter("year");
	String where = " where 1=1 ";
	
	if(SDate == null || EDate ==null){
		SDate = "";
		EDate = "";
	}else{
		if((!SDate.equals("")&&!SDate.equals("null"))||(!EDate.equals("")&&!EDate.equals("null"))){
	where = where + " and EventDate between '" + SDate + "' and '"+EDate+"'";
		}
	} 
	
	if(SHour == null || SMin == null || SSec == null || EHour == null || EMin == null || ESec == null){
		SHour = "0";
		SMin = "0";
		SSec = "0";
		EHour = "0";
		EMin = "0";
		ESec = "0";
	}else{
		if((!SHour.equals("")&&!SHour.equals("null"))||(!SMin.equals("")&&!SMin.equals("null"))||(!SSec.equals("")&&!SSec.equals("null"))||(!EHour.equals("")&&!EHour.equals("null"))||(!EMin.equals("")&&!EMin.equals("null"))||(!ESec.equals("")&&!ESec.equals("null"))){
	if(Integer.parseInt(SHour)<10){
		SHour = "0" + SHour;
	}
	if(Integer.parseInt(SMin)<10){
		SMin = "0" + SMin;
	}
	if(Integer.parseInt(SSec)<10){
		SSec = "0" + SSec;
	}
	if(Integer.parseInt(EHour)<10){
		EHour = "0" + EHour;
	}
	if(Integer.parseInt(EMin)<10){
		EMin = "0" + EMin;
	}
	if(Integer.parseInt(ESec)<10){
		ESec = "0" + ESec;
	}
	where = where + " and EventTime between '" + SHour + ":"+SMin+":"+SSec+"' and '" + EHour + ":"+EMin+":"+ESec+"'";
		}
	}
	
	if(Name == null){
		Name = "";
	}else{
		if(!Name.equals("")){
	where = where + " and EventName = '" + Name + "'";
		}
	}
	
	if(User == null){
		User = "";		
	}else{
		if(!User.equals("")){
	where = where + " and EventUserName = '" + User + "'";
		}
	}
	
	if(Month==null||Year==null){
		
	}else{
		if(!Month.equals("")&&!Year.equals("")){
	where = where + " and EventDate like '" + Year + "-" + Month + "-%' ";
		}
	}
	
	 
	int maxPageNum=-1;                 // 전체 페이지의 수.
	int limitPage,pagerSize = 10;              // limitPage : 마지막 페이지 넘버. pageSize : 페이지 넘버가 보여지는 간격.
	int currentPage = 0;
	if(request.getAttribute("currentPage")!=null){
		currentPage = Integer.parseInt((String)request.getAttribute("currentPage")); // 현재 페이지 
	}
	
	int top = 0;
	
	if(request.getParameter("Num")==null){
		top = 100;
	}else{
	 	top = Integer.parseInt(request.getParameter("Num"));
	}
	
	 
	String sql = "select top "+top+" EventType,EventDate,EventTime,EventPlace,EventName,EventUserID,EventUserName,EventDoorState,EventCompanyID from dbo.History  ";
	sql = sql + where;
	sql = sql +	" order by EventDate desc; ";
		try {
		Context init = new InitialContext();
		DataSource ds = (DataSource)init.lookup("java:comp/env/jdbc/MssqlDB");
		conn = ds.getConnection();
		Statement pstmt = conn.createStatement();
		
		ResultSet rs = pstmt.executeQuery(sql);

      out.write("\r\n");
      out.write("\t<div class=\"searchForm\">\r\n");
      out.write("\t\t<div class=\"\">\r\n");
      out.write("\t\t\t<form action=\"/TrustWinPro/action/index.jsp\" name=\"searchLog\" method=\"post\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" value=\"searchLog\" name=\"logtype\" />\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" value=\"Log\" name=\"content\" />\r\n");
      out.write("\t\t\t\t");
      out.print(Lanfunc.language(lan, 71));
      out.write(" : <input type=\"text\" name=\"searchStartDate\" id=\"searchStartDate\" readonly=\"readOnly\" value=\"");
      out.print(LangUtil.Empty(SDate));
      out.write("\" readonly=\"readOnly\" onclick=\"fnPopUpCalendar(searchStartDate,searchStartDate,'yyyy-mm-dd')\" /> \r\n");
      out.write("\t\t\t\t~ <input type=\"text\" name=\"searchEndDate\" id=\"searchEndDate\" readonly=\"readOnly\" value=\"");
      out.print(LangUtil.Empty(EDate));
      out.write("\" readonly=\"readOnly\" onclick=\"fnPopUpCalendar(searchEndDate,searchEndDate,'yyyy-mm-dd')\" />\r\n");
      out.write("\t\t\t\t");
      out.print(Lanfunc.language(lan, 106));
      out.write(" : \r\n");
      out.write("\t\t\t\t<select name=\"searchStartHour\" id=\"searchStartHour\">\r\n");
      out.write("\t\t\t\t\t<option value=\"0\" >0</option>\r\n");

	for(int i=1;i<25;i++){

      out.write("\r\n");
      out.write("\t\t\t\t\t<option value=\"");
      out.print(i);
      out.write('"');
      out.write(' ');
      out.print(Integer.parseInt(SHour) == i ?"selected":"");
      out.write(' ');
      out.write('>');
      out.print(i);
      out.write("</option>\r\n");

	}

      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<select name=\"searchStartMinute\" id=\"searchStartMinute\">\r\n");
      out.write("\t\t\t\t\t<option value=\"0\" >00</option>\r\n");

	for(int i=1;i<61;i++){

      out.write("\r\n");
      out.write("\t\t\t\t\t<option value=\"");
      out.print(i);
      out.write('"');
      out.write(' ');
      out.print(Integer.parseInt(SMin) == i ?"selected":"");
      out.write(' ');
      out.write('>');
      out.print(i);
      out.write("</option>\r\n");

	}

      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<select name=\"searchStartSec\" id=\"searchStartSec\">\r\n");
      out.write("\t\t\t\t\t<option value=\"0\" >00</option>\r\n");

	for(int i=1;i<61;i++){

      out.write("\r\n");
      out.write("\t\t\t\t\t<option value=\"");
      out.print(i);
      out.write('"');
      out.write(' ');
      out.print(Integer.parseInt(SSec) == i ?"selected":"");
      out.write(' ');
      out.write('>');
      out.print(i);
      out.write("</option>\r\n");

	}

      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t~\r\n");
      out.write("\t\t\t\t<select name=\"searchEndHour\" id=\"searchEndHour\">\r\n");
      out.write("\t\t\t\t\t<option value=\"0\" >0</option>\r\n");

	for(int i=1;i<25;i++){

      out.write("\r\n");
      out.write("\t\t\t\t\t<option value=\"");
      out.print(i);
      out.write('"');
      out.write(' ');
      out.print(Integer.parseInt(EHour) == i ?"selected":"");
      out.write(' ');
      out.write('>');
      out.print(i);
      out.write("</option>\r\n");

	}

      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<select name=\"searchEndMinute\" id=\"searchEndMinute\">\r\n");
      out.write("\t\t\t\t\t<option value=\"0\" >00</option>\r\n");

	for(int i=1;i<61;i++){

      out.write("\r\n");
      out.write("\t\t\t\t\t<option value=\"");
      out.print(i);
      out.write('"');
      out.write(' ');
      out.print(Integer.parseInt(EMin) == i ?"selected":"");
      out.write(' ');
      out.write('>');
      out.print(i);
      out.write("</option>\r\n");

	}

      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<select name=\"searchEndSec\" id=\"searchEndSec\">\r\n");
      out.write("\t\t\t\t\t<option value=\"0\" >00</option>\r\n");

	for(int i=1;i<61;i++){

      out.write("\r\n");
      out.write("\t\t\t\t\t<option value=\"");
      out.print(i);
      out.write('"');
      out.write(' ');
      out.print(Integer.parseInt(ESec) == i ?"selected":"");
      out.write(' ');
      out.write('>');
      out.print(i);
      out.write("</option>\r\n");

	}

      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t<br/>\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");
      out.print(Lanfunc.language(lan, 81));
      out.write(" : <input type=\"text\" name=\"searchName\" value=\"");
      out.print(Name);
      out.write("\" /> ");
      out.print(Lanfunc.language(lan, 108));
      out.write(" : <input type=\"text\" name=\"searchUser\" value=\"");
      out.print(User);
      out.write("\" />\r\n");
      out.write("\t\t\t\t");
      out.print(Lanfunc.language(lan, 91));
      out.write("\r\n");
      out.write("\t\t\t\t<input name=\"content\" type=\"hidden\" value=\"Log\" />\r\n");
      out.write("\t\t\t\t<input name=\"Num\" type=\"text\" value=\"");
      out.print(top );
      out.write("\" size=\"20\" />\r\n");
      out.write("\t\t\t\t<input type=\"submit\" name=\"submit\" value=\"");
      out.print(Lanfunc.language(lan, 182));
      out.write("\" class=\"ct-btn white\" />\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<table border=1 cellspacing=\"0\" class=\"titleEx1\">\r\n");
      out.write("\t\t<colgroup>\r\n");
      out.write("\t\t\t<col width=\"9%\">\r\n");
      out.write("\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t<col width=\"14%\">\r\n");
      out.write("\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t<col width=\"12%\">\r\n");
      out.write("\t\t\t<col width=\"12%\">\r\n");
      out.write("\t\t\t<col width=\"13%\">\r\n");
      out.write("\t\t</colgroup>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>");
      out.print(Lanfunc.language(lan, 72));
      out.write("</th>\r\n");
      out.write("\t\t\t<th>");
      out.print(Lanfunc.language(lan, 73));
      out.write("</th>\r\n");
      out.write("\t\t\t<th>");
      out.print(Lanfunc.language(lan, 74));
      out.write("</th>\r\n");
      out.write("\t\t\t<th>");
      out.print(Lanfunc.language(lan, 75));
      out.write("</th>\r\n");
      out.write("\t\t\t<th>");
      out.print(Lanfunc.language(lan, 76));
      out.write("</th>\r\n");
      out.write("\t\t\t<th>");
      out.print(Lanfunc.language(lan, 77));
      out.write("</th>\r\n");
      out.write("\t\t\t<th>");
      out.print(Lanfunc.language(lan, 78));
      out.write("</th>\r\n");
      out.write("\t\t\t<th>");
      out.print(Lanfunc.language(lan, 79));
      out.write("</th>\r\n");
      out.write("\t\t\t<th>");
      out.print(Lanfunc.language(lan, 80));
      out.write("</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<table cellspacing=\"0\"  class=\"ex1\">\r\n");
      out.write("\t\t<colgroup>\r\n");
      out.write("\t\t\t<col width=\"9%\">\r\n");
      out.write("\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t<col width=\"14%\">\r\n");
      out.write("\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t<col width=\"12%\">\r\n");
      out.write("\t\t\t<col width=\"12%\">\r\n");
      out.write("\t\t\t<col width=\"13%\">\r\n");
      out.write("\t\t</colgroup>\r\n");
      out.write("\t\t<tbody>\r\n");
			
				int i = 0;
				while(rs.next()){
					if(i%2==0){
						out.println("<tr  class='odd'>");
					}else{
						out.println("<tr>");	
					}

      out.write("\r\n");
      out.write("\t\t\t\t<td class='date1'>");
      out.print(rs.getString(1) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td class='date1'>");
      out.print(rs.getString(2) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td class='date1'>");
      out.print(rs.getString(3) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td class='date1'>");
      out.print(rs.getString(4) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td class='date1'>");
      out.print(rs.getString(5) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td class='date1'>");
      out.print(rs.getString(6) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td class='date1'>");
      out.print(rs.getString(7) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td class='date1'>");
      out.print(rs.getString(8) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td class='date1'>");
      out.print(rs.getString(9) );
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");

					i++;
				}
				rs.close();
				conn.close();
				

      out.write("\t\r\n");
      out.write("\t\t</tbody>\r\n");
      out.write("\t</table>\r\n");
      out.write("</div>\r\n");

		}catch(Exception e){
			out.println("DB error!!.");
			e.printStackTrace();
		}

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
