/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2015-12-10 05:52:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.action.page;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import javax.sql.*;
import javax.naming.*;
import com.Trustwin.Admin.Project.Event.*;
import com.Trustwin.Admin.Project.Language.*;
import com.Trustwin.Admin.Project.Category.*;

public final class MainLog_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	
	String Num = "20";
	LanguageFunc Lanfunc = new LanguageFunc();
	EventFunc Evtfunc = new EventFunc();
	
	if(request.getParameter("Num")!=null){
		if(!request.getParameter("Num").equals("")){
			Num = (String)request.getParameter("Num");
		}
	}
	String lan = (String)session.getAttribute("nation");
	
	String STime = "";
	String ETime = "";
	

      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("function refresh(){\r\n");
      out.write("\t$.ajax({      \r\n");
      out.write("\t    type:\"post\",  \r\n");
      out.write("\t    url:\"/TrustWinPro/action/ajax/LogA.jsp\",   \r\n");
      out.write("\t    data: \"num=");
      out.print(Num);
      out.write("\",\r\n");
      out.write("\t    success:function(args){   \r\n");
      out.write("\t        $(\"#logdata\").html(args);      \r\n");
      out.write("\t    },   \r\n");
      out.write("\t    error:function(e){  \r\n");
      out.write("\t        //alert(e.responseText);  \r\n");
      out.write("\t    }  \r\n");
      out.write("\t});  \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function optionSubmit(){\r\n");
      out.write("\tvar count = 0;\r\n");
      out.write("\tvar array = \"\";\r\n");
      out.write("\tvar arrayName = \"\";\r\n");
      out.write("\tvar check = document.colorO.check;\r\n");
      out.write("\tvar name = document.colorO.colorName;\r\n");
      out.write("\tfor(var i = 0; i< check.length; i++){\r\n");
      out.write("\t\tif(check[i].checked){\r\n");
      out.write("\t\t\tarray = array + \"1\" + check[i].value + \",\";\r\n");
      out.write("\t\t\tarrayName = arrayName + name[i].value + \",\";\r\n");
      out.write("\t\t\tcount++;\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tarray = array + \"0\" + check[i].value + \",\"\r\n");
      out.write("\t\t\tarrayName = arrayName + name[i].value + \",\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({      \r\n");
      out.write("\t    type:\"post\",  \r\n");
      out.write("\t    url:\"/TrustWinPro/action/ajax/ColorOption.jsp\",   \r\n");
      out.write("\t    data: \"array=\" + array + \"&color=\"+arrayName,\r\n");
      out.write("\t    success:function(args){   \r\n");
      out.write("\t    \tdocument.getElementById(\"colorO\").submit();\r\n");
      out.write("\t    },   \r\n");
      out.write("\t    error:function(e){  \r\n");
      out.write("\t        //alert(e.responseText);  \r\n");
      out.write("\t    }  \r\n");
      out.write("\t});  \r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function closeColor(){\r\n");
      out.write("\tdocument.getElementById(\"colorOption\").style.display = \"none\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function openColor(){\r\n");
      out.write("\tif(document.getElementById(\"colorOption\").style.display == \"none\"){\r\n");
      out.write("\t\tdocument.getElementById(\"colorOption\").style.display = \"block\";\t\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tdocument.getElementById(\"colorOption\").style.display = \"none\";\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("refresh();\r\n");
      out.write("$(document).attr(\"timer\",setInterval(refresh,1000));\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"userdata\">\r\n");
      out.write("\t<div class=\"colorOption\" id=\"colorOption\">\r\n");
      out.write("\t<form action=\"/TrustWinPro/action/index.jsp\" name=\"colorO\" id=\"colorO\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("\t\t<table cellspacing=\"0\"  class=\"titleEx1\">\r\n");
      out.write("\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t<col width=\"20%\">\r\n");
      out.write("\t\t\t\t<col width=\"40%\">\r\n");
      out.write("\t\t\t\t<col width=\"40%\">\r\n");
      out.write("\t\t\t</colgroup>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>Type</th>\r\n");
      out.write("\t\t\t\t<th>Display</th>\r\n");
      out.write("\t\t\t\t<th>Color</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<table cellspacing=\"0\"  class=\"ex1\">\r\n");
      out.write("\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t<col width=\"20%\">\r\n");
      out.write("\t\t\t\t<col width=\"40%\">\r\n");
      out.write("\t\t\t\t<col width=\"40%\">\r\n");
      out.write("\t\t\t</colgroup>\r\n");
      out.write("\t\t\t<tbody>\r\n");

	EventOption[] eo = Evtfunc.selOption();
	for(int i=0; i < eo.length;i++){

      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(eo[i].getType() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"checkbox\" value=\"");
      out.print(eo[i].getIdx());
      out.write("\" name=\"check\" ");
      out.print(eo[i].getDisplay().equals("1")?"checked":"" );
      out.write("></td>\r\n");
      out.write("\t\t\t\t<td><input class=\"color\" name=\"colorName\" value=\"");
      out.print(eo[i].getColor() );
      out.write("\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");

	}

      out.write("\r\n");
      out.write("\t\t\t</tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"button\" id=\"web-buttons-idrmij3\">\r\n");
      out.write("\t\t\t<a href=\"#\"  onclick=\"closeColor();\">");
      out.print(Lanfunc.language(lan, 185));
      out.write("</a>\r\n");
      out.write("\t\t\t<a href=\"#\"  onclick=\"optionSubmit();\">");
      out.print(Lanfunc.language(lan, 92));
      out.write("</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class = \"tablebor\" style = \"width: 96%; margin:3px\">\r\n");
      out.write("\t\t<div id=\"logdata\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
