/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2015-12-24 06:06:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.action.page;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import javax.sql.*;
import javax.naming.*;
import com.Trustwin.Admin.Project.Language.*;
import com.Trustwin.Admin.Project.Device.*;
import com.Trustwin.Admin.Project.Map.*;

public final class MapSetup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String ID = (String)request.getParameter("mapID");
	DeviceFunc devFunc = new DeviceFunc();
	Device[] dev = devFunc.deviceList();
	MapFunc mapFunc = new MapFunc();
	MapDevice[] mapDev = mapFunc.selMapDev(ID);
	Map map = mapFunc.selMap(ID);

      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function addMapDevice(v){\r\n");
      out.write("\t$.ajax({      \r\n");
      out.write("\t    type:\"post\",  \r\n");
      out.write("\t    url:\"/TrustWinPro/action/ajax/AddMapDevice.jsp\",   \r\n");
      out.write("\t    data: \"id=\"+v,\r\n");
      out.write("\t    success:function(args){\r\n");
      out.write("\t    \tlocation.href = \"/TrustWinPro/action/index.jsp?left=Monitoring&content=MapSetup&mapID=\" + ");
      out.print(ID);
      out.write(";\r\n");
      out.write("\t    },   \r\n");
      out.write("\t    error:function(e){  \r\n");
      out.write("\t        alert(e.responseText);  \r\n");
      out.write("\t    }  \r\n");
      out.write("\t}); \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function delMapDevice(x){\r\n");
      out.write("\t$.ajax({      \r\n");
      out.write("\t    type:\"post\",  \r\n");
      out.write("\t    url:\"/TrustWinPro/action/ajax/DelMapDevice.jsp\",   \r\n");
      out.write("\t    data: \"devid=\"+x,\r\n");
      out.write("\t    success:function(args){\r\n");
      out.write("\t    \tlocation.href = \"/TrustWinPro/action/index.jsp?left=Monitoring&content=MapSetup&mapID=\" + ");
      out.print(ID);
      out.write(";\r\n");
      out.write("\t    },   \r\n");
      out.write("\t    error:function(e){  \r\n");
      out.write("\t        alert(e.responseText);  \r\n");
      out.write("\t    }  \r\n");
      out.write("\t}); \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function updMapDevice(x,v){\r\n");
      out.write("\t$.ajax({      \r\n");
      out.write("\t    type:\"post\",  \r\n");
      out.write("\t    url:\"/TrustWinPro/action/ajax/UpdateMapDevice.jsp\",   \r\n");
      out.write("\t    data: \"idx=\"+v + \"&id=\" + x,\r\n");
      out.write("\t    success:function(args){\r\n");
      out.write("\t    \tlocation.href = \"/TrustWinPro/action/index.jsp?left=Monitoring&content=MapSetup&mapID=\" + ");
      out.print(ID);
      out.write(";\r\n");
      out.write("\t    },   \r\n");
      out.write("\t    error:function(e){\r\n");
      out.write("\t        alert(e.responseText);\r\n");
      out.write("\t    }  \r\n");
      out.write("\t}); \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function MapInfoSubmit(){\r\n");
      out.write("\tMapInfomating.submit();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function MapCancel(){\r\n");
      out.write("\tcanMap.submit();\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div id=\"MapInfo\">\r\n");
      out.write("\t<div class=\"basic\">\r\n");
      out.write("\t\t<form action=\"/TrustWinPro/action/page/MapSetupModify.jsp\" name=\"MapInfomating\" id=\"MapInfomating\" method=\"post\"  enctype=\"multipart/form-data\" >\r\n");
      out.write("\t\t\t<input type=\"hidden\" value=\"");
      out.print(ID);
      out.write("\"  name=\"id\" />\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t<section class = \"sectionji\">\r\n");
      out.write("\t\t\t<ul class = \"ulji\">\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"basicInfo\">\r\n");
      out.write("\t\t\t\t<div class=\"InfoBox\">\r\n");
      out.write("\t\t\t\t\t<div class=\"block\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"header\">MAP 이름</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"main\"><input type=\"text\" name=\"mapName\" value=\"");
      out.print(map.getName() );
      out.write("\" size=\"40um\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"block\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"header\">MAP File</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"main\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"file\" name=\"saveFile\" id=\"saveFile\"  value=\"");
      out.print(map.getImage() );
      out.write("\" >\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<table border=1 cellspacing=\"0\" class=\"titleEx1\">\r\n");
      out.write("\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"40%\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"20%\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"20%\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>번호</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>디바이스 명</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>X 좌표</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Y 좌표</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>추가 <a href=\"#a\" onclick=\"addMapDevice('");
      out.print(ID);
      out.write("')\">+</a></th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t<table cellspacing=\"0\"  class=\"ex1\">\r\n");
      out.write("\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"40%\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"20%\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"20%\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t");

					for(int i=0;i<mapDev.length;i++){
			
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(i+1);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class='date1'>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select name=\"deviceName\" onchange=\"updMapDevice(this.value,");
      out.print(mapDev[i].getIdx());
      out.write(");\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"0\">-- None --</option>\r\n");

						for(int j=0;j<dev.length;j++){
							String device = mapDev[i].getDeviceID(); 
							if(device == null){
								device = "";
							}

      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"");
      out.print(dev[j].getControllerName());
      out.write('"');
      out.write(' ');
      out.print(device.equals(dev[j].getControllerName())?"selected" : "" );
      out.write('>');
      out.print(dev[j].getControllerName());
      out.write("</option>\r\n");

						}

      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class='date1'>");
      out.print(mapDev[i].getX() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class='date1'>");
      out.print(mapDev[i].getY() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class='date1'><a href=\"#a\" onclick=\"delMapDevice(");
      out.print(mapDev[i].getIdx());
      out.write(")\">삭제</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t");

					}
			
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"bottom\" id=\"web-buttons-idrmij3\">\r\n");
      out.write("\t\t\t\t<a href=\"#a\" onclick=\"MapInfoSubmit();\"><img src=\"/TrustWinPro/action/image/interface/submit.png\"></a>\r\n");
      out.write("\t\t\t\t<a href=\"#a\" onclick=\"MapCancel();\" ><img src=\"/TrustWinPro/action/image/interface/delete.png\"></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<form name=\"canMap\" id=\"canMap\" method=\"post\" action=\"/TrustWinPro/action/index.jsp\" >\r\n");
      out.write("\t<input type=\"hidden\" value=\"");
      out.print(ID);
      out.write("\"  name=\"mapID\" />\r\n");
      out.write("\t<input type=\"hidden\" value=\"Monitoring\" name=\"left\" />\r\n");
      out.write("\t<input type=\"hidden\" value=\"Map\" name=\"content\" />\r\n");
      out.write("</form>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
