/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2015-12-10 06:58:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.action.page;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.Trustwin.Admin.Project.Device.*;
import com.Trustwin.Admin.Project.Event.*;

public final class pieChart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t// 구글 파이차트 실시간 출력\r\n");
      out.write("\tgoogle.load(\"visualization\", \"1\", {packages:[\"corechart\"]});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\tfunction drawChart(dataFromAjax){\r\n");
      out.write("\t\tvar data = google.visualization.arrayToDataTable(dataFromAjax);\r\n");
      out.write("\t\tvar option = {title: 'Event Name',is3D: false,};\r\n");
      out.write("\t\tvar chart = new google.visualization.PieChart(document.getElementById('piechart_3d'));\r\n");
      out.write("        chart.draw(data, option);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction drawInit(){\r\n");
      out.write("\t\tvar data = null;\r\n");
      out.write("\t\tvar table_data = null;\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl:'/TrustWinPro/action/ajax/pieChartProc.jsp',\r\n");
      out.write("\t\t\tdata:{},\r\n");
      out.write("\t\t\tsuccess: function(res){\r\n");
      out.write("\t\t\t\ttable_data = eval(\"(\" + res + \")\");\r\n");
      out.write("\t\t\t\tdrawChart(table_data);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction statusPie()\r\n");
      out.write("    {\r\n");
      out.write("    \tvar array = document.pieChart.check;\r\n");
      out.write("    \tvar val = \"\";\r\n");
      out.write("    \tfor(var i=0;i<array.length;i++){\r\n");
      out.write("    \t\tif(array[i].checked == true){\r\n");
      out.write("    \t\t\tval = val + array[i].value + \",\";\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t}\r\n");
      out.write("\r\n");
      out.write("    \t$.ajax({\r\n");
      out.write("\t\t     url:'/TrustWinPro/action/ajax/pieStatusProc.jsp',\r\n");
      out.write("\t\t     data: 'val='+val,\r\n");
      out.write("\t\t     success: function(res) {\r\n");
      out.write("\t\t    \t document.getElementById(\"pieChart\").submit();\r\n");
      out.write("\t\t     }\r\n");
      out.write("\t\t});\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function statusWindowPie(){\r\n");
      out.write("    \tif(document.getElementById(\"piechart_div_S\").style.display == \"none\"){\r\n");
      out.write("    \t\tdocument.getElementById(\"piechart_div_S\").style.display = \"block\";\t\r\n");
      out.write("    \t\tdocument.getElementById(\"piechart_3d\").style.display = \"none\";\t\r\n");
      out.write("    \t}else{\r\n");
      out.write("    \t\tdocument.getElementById(\"piechart_div_S\").style.display = \"none\";\r\n");
      out.write("    \t\tdocument.getElementById(\"piechart_3d\").style.display = \"block\";\t\r\n");
      out.write("    \t}\r\n");
      out.write("    }\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\tgoogle.setOnLoadCallback(drawInit);\r\n");
      out.write("\t\r\n");
      out.write("\t drawInit(); \r\n");
      out.write("</script>\r\n");
      out.write("<div  style=\"width:99%; height:6px; font-size:0; line-height:2; padding:2;\" >\r\n");
      out.write("\r\n");
      out.write("<a href=\"#a\" onclick=\"statusWindowPie()\"><input type=\"image\" src=\"/TrustWinPro/action/image/setting.png\" style=\"width:20px; height:20px; float:right;\"/></a>\r\n");
      out.write("</div>\r\n");
      out.write("<br>\r\n");
      out.write("<div id=\"piechart_3d\" style = \"position: relative;\r\n");
      out.write("    width: 99%;\r\n");
      out.write("    height: 200px;\r\n");
      out.write("    padding: 0 0 20px 0;\r\n");
      out.write("    margin: 0 0 20px 0;\r\n");
      out.write("    border: 1px solid #b4b4b4;\r\n");
      out.write("    border-radius: 6px;\r\n");
      out.write("    -webkit-box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.15);\r\n");
      out.write("    box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.15);\r\n");
      out.write("    background: #fff;\"></div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"chart_div_S\" id=\"piechart_div_S\" style = \"position: relative;\r\n");
      out.write("    width: 97%;\r\n");
      out.write("    height: 200px;\r\n");
      out.write("    padding: 0 0 20px 0;\r\n");
      out.write("    margin: 0 0 20px 0;\r\n");
      out.write("    border: 1px solid #b4b4b4;\r\n");
      out.write("    border-radius: 6px;\r\n");
      out.write("    -webkit-box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.15);\r\n");
      out.write("    box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.15);\r\n");
      out.write("    background: #fff;\">\r\n");
      out.write("\t<form action=\"/TrustWinPro/action/index.jsp\" name=\"pieChart\" id=\"pieChart\" method=\"post\">\r\n");
      out.write("\t\t<div class=\"chart_table\">\r\n");
      out.write("\t\t\t<table cellspacing=\"0\"  class=\"titleEx1\">\r\n");
      out.write("\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t<col width=\"50%\">\r\n");
      out.write("\t\t\t\t\t<col width=\"50%\">\r\n");
      out.write("\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>DeviceName</th>\r\n");
      out.write("\t\t\t\t\t<th>Select</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<table cellspacing=\"0\"  class=\"ex1\">\r\n");
      out.write("\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t<col width=\"50%\">\r\n");
      out.write("\t\t\t\t\t<col width=\"50%\">\r\n");
      out.write("\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t<tbody>\r\n");

	DeviceFunc DFunc = new DeviceFunc();
	Device[] dev = DFunc.searchDevice(null,null,null,null);
	EventFunc EFunc = new EventFunc();
	String piechart = EFunc.pieChartVal();
	String[] piecharts = piechart.split(",");
	for(int i=0;i<dev.length;i++){
		String status = "";
		for(int j=0;j<piecharts.length;j++){
			if(dev[i].getUniqueID().equals(piecharts[j])){
				status = "checked";
				break;
			}else{
				status = "";
			}
		}

      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(dev[i].getControllerName());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"checkbox\" id=\"check\" name=\"check\" value=\"");
      out.print(dev[i].getUniqueID() );
      out.write('"');
      out.write(' ');
      out.print(status );
      out.write("></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");

	}

      out.write("\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<div class=\"bottom\" id=\"web-buttons-idrmij3\">\r\n");
      out.write("\t\t\t\t<a href=\"#\" title=\"Enroll\" onclick=\"statusPie()\">submit</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
