/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2015-12-24 05:19:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.action.page;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import javax.sql.*;
import javax.naming.*;

public final class TimeZoneUpdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("UTF-8");
	if(request.getParameter("result1") == "" || request.getParameter("timezoneNo") == ""){

	}else{
		String Res = (String)request.getParameter("result1");
		String[] array = Res.split("/");
		int time = Integer.parseInt(request.getParameter("timezoneNo"));
		int timem = Integer.parseInt(request.getParameter("timezoneNoM"));
		int count = 0;
		String timeName = (String)request.getParameter("timename");
		String sql = "update TimeZone set TimeZoneName = '" + timeName + "', TimeZoneNo = '" + timem + "', ";
		
		if(request.getParameter("result1").split("/").length==2){
			String StartTimeS1 = request.getParameter("result1").split("/")[0];
			String EndTimeE1 = request.getParameter("result1").split("/")[1];
			sql = sql + "HolSTime2 = '" + StartTimeS1 + "', HolETime2 = '" + EndTimeE1 + "', ";
			count++;
		}
		
		if(request.getParameter("result2").split("/").length==2){
			String StartTimeS2 = request.getParameter("result2").split("/")[0];
			String EndTimeE2 = request.getParameter("result2").split("/")[1];
			sql = sql + "MonSTime = '" + StartTimeS2 + "', MonETime = '" + EndTimeE2 + "', ";
			count++;
		}
		
		if(request.getParameter("result3").split("/").length==2){
			String StartTimeS3 = request.getParameter("result3").split("/")[0];
			String EndTimeE3 = request.getParameter("result3").split("/")[1];
			sql = sql + "TueSTime = '" + StartTimeS3 + "', TueETime = '" + EndTimeE3 + "', ";
			count++;
		}
		
		if(request.getParameter("result4").split("/").length==2){
			String StartTimeS4 = request.getParameter("result4").split("/")[0];
			String EndTimeE4 = request.getParameter("result4").split("/")[1];
			sql = sql + "WedSTime = '" + StartTimeS4 + "', WedETime = '" + EndTimeE4 + "', ";
			count++;
		}
		
		if(request.getParameter("result5").split("/").length==2){
			String StartTimeS5 = request.getParameter("result5").split("/")[0];
			String EndTimeE5 = request.getParameter("result5").split("/")[1];
			sql = sql + "ThuSTime = '" + StartTimeS5 + "', ThuETime = '" + EndTimeE5 + "', ";
			count++;
		}
		
		if(request.getParameter("result6").split("/").length==2){
			String StartTimeS6 = request.getParameter("result6").split("/")[0];
			String EndTimeE6 = request.getParameter("result6").split("/")[1];
			sql = sql + "FriSTime = '" + StartTimeS6 + "', FriETime = '" + EndTimeE6 + "', ";
			count++;
		}
		
		if(request.getParameter("result7").split("/").length==2){
			String StartTimeS7 = request.getParameter("result7").split("/")[0];
			String EndTimeE7 = request.getParameter("result7").split("/")[1];
			sql = sql + "SatSTime = '" + StartTimeS7 + "', SatETime = '" + EndTimeE7 + "', ";
			count++;
		}
		
		if(request.getParameter("result8").split("/").length==2){
			String StartTimeS8 = request.getParameter("result8").split("/")[0];
			String EndTimeE8 = request.getParameter("result8").split("/")[1];
			sql = sql + "HolSTime1 = '" + StartTimeS8 + "', HolETime1 = '" + EndTimeE8 + "' ";
			count++;
		}
		
		
		if(count > 0){
			Connection conn = null;
			sql = sql + " where TimeZoneNo = " + time;
			try {
				Context init = new InitialContext();
				DataSource ds = (DataSource)init.lookup("java:comp/env/jdbc/MssqlDB");
				conn = ds.getConnection();
				Statement pstmt = conn.createStatement();
				
				pstmt.executeUpdate(sql);
				
				conn.close();
			}catch(Exception e){
				out.println("DB error!!.");
				e.printStackTrace();
			}
		}

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\tfunction replace(){\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"Time\").submit();\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body onload=\"replace();\">\r\n");
      out.write("\t\t<form action=\"/TrustWinPro/action/index.jsp\" name=\"Time\" id=\"Time\" method=\"post\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" value=\"");
      out.print(timem );
      out.write("\" name=\"num\" />\r\n");
      out.write("\t\t\t<input type=\"hidden\" value=\"Time\" name=\"left\" />\r\n");
      out.write("\t\t\t<input type=\"hidden\" value=\"Time\" name=\"content\" />\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");

	}

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
