/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2015-12-23 07:37:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.action.page;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import javax.sql.*;
import javax.naming.*;
import com.Trustwin.Admin.Project.Language.*;
import com.Trustwin.Admin.Project.User.*;
import com.Trustwin.Admin.Project.Category.*;
import com.Trustwin.Admin.Project.Access.*;
import com.Trustwin.Admin.Project.Device.*;
import com.Trustwin.Admin.Project.Event.*;

public final class UserInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String ID = (String)request.getParameter("userID");
	
	UserFunc Userfunc = new UserFunc();
	LanguageFunc Lanfunc = new LanguageFunc();
	CategoryFunc Catefunc = new CategoryFunc();
	AccessFunc Accfunc = new AccessFunc();
	DeviceFunc Devfunc = new DeviceFunc();
	EventFunc Evtfunc = new EventFunc();
	
	String lan = (String)session.getAttribute("nation");
	if(ID == null){
		ID = Userfunc.UserTop();
	}
	Connection conn = null;
	String sql = "select FirstName, MiddleName, LastName, UserID, UserClass, ID, Password, CompanyID, Department, "+
	"Position, TelOffice, EngagedDay, LatestPromoted, RetiredDay, License1, License2, License3, HourlyWage, EMail, Sex, "+
	"Married, ResidentRegNo, TelHome, MobilePhone, CarName, ZipCode, Address, CardID, CardType, FacilityCode, CardAttribute, "+
	"TimeZoneNo1, TimeZoneNo2, UserMode, UseSubSensor, UseDuressFinger, photo, DeviceGroup, ReAccessLimitTime from member where UserID = '" + ID + "'";
	try {
	
	Context init = new InitialContext();
	DataSource ds = (DataSource)init.lookup("java:comp/env/jdbc/MssqlDB");
	conn = ds.getConnection();
	Statement pstmt = conn.createStatement();
	ResultSet rs = pstmt.executeQuery(sql);
	if(!rs.next()){

      out.write("\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\talert(\"정보가 없습니다.\");\r\n");
      out.write("\t\t\tlocation.replace(\"index.jsp?left=User\");\r\n");
      out.write("\t\t</script>\r\n");

			}else{

      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("var cardid = 0;\r\n");
      out.write("var companyid = 0;\r\n");
      out.write("function previewImage(targetObj, View_area) {\r\n");
      out.write("\tvar preview = document.getElementById(View_area); //div id\r\n");
      out.write("\tvar ua = window.navigator.userAgent;\r\n");
      out.write("\tvar ImagePrev = document.getElementById(\"prev_\"+View_area);\r\n");
      out.write("\tif(ImagePrev != null){\r\n");
      out.write("\t\tpreview.removeChild(ImagePrev);\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t if (ua.indexOf(\"MSIE\") > -1) {\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("           try {\r\n");
      out.write("               var src = \"\"; // get file full path \r\n");
      out.write("               \r\n");
      out.write("               if (targetObj.value.indexOf(\"\\\\fakepath\\\\\") < 0) {\r\n");
      out.write("            \t   src = targetObj.value;\r\n");
      out.write("               } else {\r\n");
      out.write("            \t  \r\n");
      out.write("               }\r\n");
      out.write("               \r\n");
      out.write("               var ie_preview_error = document\r\n");
      out.write("                       .getElementById(\"ie_preview_error_\" + View_area);\r\n");
      out.write("\r\n");
      out.write("               if (ie_preview_error) {\r\n");
      out.write("                   preview.removeChild(ie_preview_error); \r\n");
      out.write("               }\r\n");
      out.write("               var img = document.getElementById(View_area); \r\n");
      out.write("               img.style.filter = \"progid:DXImageTransform.Microsoft.AlphaImageLoader(src='\" + src + \"', sizingMethod=scale)\"; \r\n");
      out.write("           } catch (e) {\r\n");
      out.write("        \t  \r\n");
      out.write("               if (!document.getElementById(\"ie_preview_error_\" + View_area)) {\r\n");
      out.write("                   var info = document.createElement(\"<p>\");\r\n");
      out.write("                   info.id = \"ie_preview_error_\" + previewId;\r\n");
      out.write("                   info.innerHTML = \"a\";\r\n");
      out.write("                   preview.insertBefore(info, null);\r\n");
      out.write("               }\r\n");
      out.write("           }\r\n");
      out.write("           \r\n");
      out.write("           \r\n");
      out.write("           \r\n");
      out.write("       } else {\r\n");
      out.write("\t\tvar files = targetObj.files;\r\n");
      out.write("\t\tfor ( var i = 0; i < files.length; i++) {\r\n");
      out.write("\t\t\tvar file = files[i];\r\n");
      out.write("\t\t\tvar imageType = /image.*/; \r\n");
      out.write("\t\t\tif (!file.type.match(imageType))\r\n");
      out.write("\t\t\t\tcontinue;\r\n");
      out.write("\t\t\tvar prevImg = document.getElementById(\"prev_\" + View_area); \r\n");
      out.write("\t\t\tif (prevImg) {\r\n");
      out.write("\t\t\t\tpreview.removeChild(prevImg);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tvar img = document.createElement(\"img\"); \r\n");
      out.write("\t\t\timg.id = \"prev_\" + View_area;\r\n");
      out.write("\t\t\timg.classList.add(\"obj\");\r\n");
      out.write("\t\t\timg.file = file;\r\n");
      out.write("\t\t\timg.style.width = '100px'; \r\n");
      out.write("\t\t\timg.style.height = '100px';\r\n");
      out.write("\t\t\tpreview.appendChild(img);\r\n");
      out.write("\t\t\tif (window.FileReader) { // FireFox, Chrome, Opera Ȯ��.\r\n");
      out.write("\t\t\t\tvar reader = new FileReader();\r\n");
      out.write("\t\t\t\treader.onloadend = (function(aImg) {\r\n");
      out.write("\t\t\t\t\treturn function(e) {\r\n");
      out.write("\t\t\t\t\t\taImg.src = e.target.result;\r\n");
      out.write("\t\t\t\t\t};\r\n");
      out.write("\t\t\t\t})(img);\r\n");
      out.write("\t\t\t\treader.readAsDataURL(file);\r\n");
      out.write("\t\t\t} else { // safari is not supported FileReader\r\n");
      out.write("\t\t\t\t//alert('not supported FileReader');\r\n");
      out.write("\t\t\t\tif (!document.getElementById(\"sfr_preview_error_\"\r\n");
      out.write("\t\t\t\t\t\t+ View_area)) {\r\n");
      out.write("\t\t\t\t\tvar info = document.createElement(\"p\");\r\n");
      out.write("\t\t\t\t\tinfo.id = \"sfr_preview_error_\" + View_area;\r\n");
      out.write("\t\t\t\t\tinfo.innerHTML = \"not supported FileReader\";\r\n");
      out.write("\t\t\t\t\tpreview.insertBefore(info, null);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function displayInfo(z){\r\n");
      out.write("\tfor(var i=1;i<7;i++){\r\n");
      out.write("\t\tif(i==z){\r\n");
      out.write("\t\t\tdocument.getElementById(\"tab0\"+i).className = \"here\";\r\n");
      out.write("\t\t\tdocument.getElementById(\"tab\"+i).style.display = \"block\";\t\t\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tdocument.getElementById(\"tab0\"+i).className = \"\";\r\n");
      out.write("\t\t\tdocument.getElementById(\"tab\"+i).style.display = \"none\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function UpdateInfo(){\r\n");
      out.write("\tdocument.getElementById(\"UserInfomation\").submit();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function RedundancyEmployee(num,userid){\r\n");
      out.write("\t$.ajax({      \r\n");
      out.write("\t    type:\"post\",  \r\n");
      out.write("\t    url:\"/TrustWinPro/action/ajax/RedEmp.jsp\",   \r\n");
      out.write("\t    data: \"num=\"+num + \"&userid=\"+userid,\r\n");
      out.write("\t    success:function(args){\r\n");
      out.write("\t    \tif(args > 0){\r\n");
      out.write("\t    \t\talert(\"");
      out.print(Lanfunc.language(lan, 114));
      out.write("\");\r\n");
      out.write("\t    \t\tcompanyid = 0;\r\n");
      out.write("\t    \t}else{\r\n");
      out.write("\t    \t\talert(\"");
      out.print(Lanfunc.language(lan, 115));
      out.write("\");\r\n");
      out.write("\t    \t\tcompanyid = 1;\r\n");
      out.write("\t    \t}\r\n");
      out.write("\t    },   \r\n");
      out.write("\t    error:function(e){  \r\n");
      out.write("\t        alert(e.responseText);  \r\n");
      out.write("\t    }  \r\n");
      out.write("\t}); \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function RedundancyCard(num,userid){\r\n");
      out.write("\t$.ajax({      \r\n");
      out.write("\t    type:\"post\",  \r\n");
      out.write("\t    url:\"/TrustWinPro/action/ajax/RedCard.jsp\",   \r\n");
      out.write("\t    data: \"num=\"+num + \"&userid=\"+userid,\r\n");
      out.write("\t    success:function(args){\r\n");
      out.write("\t    \tif(args > 0){\r\n");
      out.write("\t    \t\talert(\"");
      out.print(Lanfunc.language(lan, 116));
      out.write("\");\r\n");
      out.write("\t    \t\tcardid = 0;\r\n");
      out.write("\t    \t}else{\r\n");
      out.write("\t    \t\talert(\"");
      out.print(Lanfunc.language(lan, 117));
      out.write("\");\r\n");
      out.write("\t    \t\tcardid = 1;\r\n");
      out.write("\t    \t}\r\n");
      out.write("\t    },   \r\n");
      out.write("\t    error:function(e){  \r\n");
      out.write("\t        alert(e.responseText);  \r\n");
      out.write("\t    }  \r\n");
      out.write("\t}); \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function UserInfoSubmit(){\r\n");
      out.write("\t/*if(cardid == 0){\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif(companyid == 0){\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t*/\r\n");
      out.write("\tUserInfomation.submit();\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function UserDelete(){\r\n");
      out.write("\tvar del = confirm(\"");
      out.print(Lanfunc.language(lan, 103));
      out.write("\")\r\n");
      out.write("\tif(del){\r\n");
      out.write("\t\tuserDelete.submit();\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function deviceList(v){\r\n");
      out.write("\tif(v!=0){\r\n");
      out.write("\t\t$.ajax({      \r\n");
      out.write("\t\t    type:\"post\",  \r\n");
      out.write("\t\t    url:\"/TrustWinPro/action/ajax/DeviceList.jsp\",   \r\n");
      out.write("\t\t    data: \"group=\" + v,\r\n");
      out.write("\t\t    success:function(args){   \r\n");
      out.write("\t\t        $(\"#devicelist\").html(args);      \r\n");
      out.write("\t\t    },   \r\n");
      out.write("\t\t    error:function(e){  \r\n");
      out.write("\t\t        alert(e.responseText);  \r\n");
      out.write("\t\t    }  \r\n");
      out.write("\t\t}); \r\n");
      out.write("\t}else{\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function searchEvent(){\r\n");
      out.write("\tvar eventLog = document.getElementById(\"eventLog\");\r\n");
      out.write("\teventLog.start.value = document.getElementById(\"startDate\").value;\r\n");
      out.write("\teventLog.end.value = document.getElementById(\"endDate\").value;\r\n");
      out.write("\teventLog.submit();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");

	Category[] catagory = null;
	

	
	catagory = Catefunc.CategoryDefind();
	
	
	int length = catagory.length;
	Category[] cata = new Category[length];	
	cata = Catefunc.SortCategoryOne(catagory);
	String realFolder = "";
	ServletContext scontext = getServletContext();
	realFolder = request.getContextPath() + "/upload/image/user/";
	realFolder = realFolder + rs.getString(37);

      out.write("\r\n");
      out.write("<div id=\"UserInfo\">\r\n");
      out.write("\t<div class=\"basic\">\r\n");
      out.write("\t\t<form action=\"/TrustWinPro/action/page/UserInfoUpdate.jsp\" name=\"UserInfomation\" id=\"UserInfomation\" method=\"post\"  enctype=\"multipart/form-data\" >\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"userID\" value=\"");
      out.print(LangUtil.Empty(rs.getString(4)) );
      out.write("\">\r\n");
      out.write("\t\t\t<div class=\"titlebar\"> </div>\r\n");
      out.write("\t\t\t<div class=\"basicInfo\">\r\n");
      out.write("\t\t\t\t<div class=\"picture\">\r\n");
      out.write("\t\t\t\t\t<div class =\"left\">\r\n");
      out.write("\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td rowspan=\"3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id='View_area' style='position:relative; width: 100px; height: 100px; color: black; border: 0px solid black; dispaly: inline;float:left;'>\r\n");

	if(rs.getString(37)!=null){

      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"");
      out.print(realFolder );
      out.write("\" alt=\"\" style=\"width:100px;height:100px;\" id=\"prev_View_area\" />\r\n");
		
	}

      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"float:right;top:0;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"shadow\" style=\"position:absolute;z-index:100;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"file\" name=\"saveFile\" id=\"saveFile\"  style=\"filter:alpha(opacity:0);z-index:2;width:30;opacity:0;position: absolute;left:-180px;\" onchange=\"previewImage(this,'View_area');\" value=\"\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"/TrustWinPro/action/image/interface/search.png\"  border='0' align=\"absmiddle\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"right\">\r\n");
      out.write("\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t<tr class=\"block\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"header\">");
      out.print(Lanfunc.language(lan, 26));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"main\"><input class = \"inputt\" type=\"text\" name=\"firstName\" value=\"");
      out.print(LangUtil.Empty(rs.getString(1)) );
      out.write("\" ></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr class=\"block\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"header\">");
      out.print(Lanfunc.language(lan, 27));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"main\"><input type=\"text\" name=\"middleName\" value=\"");
      out.print(LangUtil.Empty(rs.getString(2)) );
      out.write("\" ></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr class=\"block\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"header\">");
      out.print(Lanfunc.language(lan, 28));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"main\"><input type=\"text\" name=\"lastName\" value=\"");
      out.print(LangUtil.Empty(rs.getString(3)) );
      out.write("\" ></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"titlebar\"> </div>\r\n");
      out.write("\t\t\t<div class=\"basicInfo\">\r\n");
      out.write("\t\t\t\t<div class=\"InfoBox\">\r\n");
      out.write("\t\t\t\t\t<div class=\"block\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"header\">");
      out.print(Lanfunc.language(lan, 29));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"main\">");
      out.print(LangUtil.Empty(LangUtil.Empty(rs.getString(4))) );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"block\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"header\">");
      out.print(Lanfunc.language(lan, 30));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"main\">\r\n");
      out.write("\t\t\t\t\t\t\t<select name=\"userClass\" class=\"mainselect\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"1\" ");
if(rs.getString(5)!=null){if(rs.getString(5).equals("1")){out.print("selected");}} 
      out.write('>');
      out.print(Lanfunc.language(lan, 170));
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"128\" ");
if(rs.getString(5)!=null){if(rs.getString(5).equals("128")){out.print("selected");}}  
      out.write('>');
      out.print(Lanfunc.language(lan, 171));
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"block\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"header\">");
      out.print(Lanfunc.language(lan, 2));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"main\"><input type=\"text\" name=\"ID\" value=\"");
      out.print(LangUtil.Empty(rs.getString(6)) );
      out.write("\" size=\"40um\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"block\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"header\">");
      out.print(Lanfunc.language(lan, 5));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"main\"><input type=\"text\" name=\"Password\" value=\"");
      out.print(LangUtil.Empty(rs.getString(7)) );
      out.write("\" size=\"40um\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"tab\">\r\n");
      out.write("\t\t\t\t<ul id=\"globalnav\">\r\n");
      out.write("\t\t\t\t\t<li class=\"tab1\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#a\" onclick=\"displayInfo(1)\" class=\"here\" id=\"tab01\">");
      out.print(Lanfunc.language(lan, 32));
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"tab2\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#a\" onclick=\"displayInfo(2)\" id=\"tab02\">");
      out.print(Lanfunc.language(lan, 33));
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"tab3\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#a\" onclick=\"displayInfo(3)\" id=\"tab03\" >");
      out.print(Lanfunc.language(lan, 34));
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"tab4\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#a\" onclick=\"displayInfo(4)\" id=\"tab04\" >");
      out.print(Lanfunc.language(lan, 35));
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"tab5\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#a\" onclick=\"displayInfo(5)\" id=\"tab05\" >");
      out.print(Lanfunc.language(lan, 36));
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"tab6\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#a\" onclick=\"displayInfo(6)\" id=\"tab06\" >");
      out.print(Lanfunc.language(lan, 37));
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"Official\" id=\"tab1\">\r\n");
      out.write("\t\t\t\t<div class=\"InfoBox\">\r\n");
      out.write("\t\t\t\t\t<div class=\"block\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"header\">");
      out.print(Lanfunc.language(lan, 38));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"main\"><input type=\"text\" name=\"CompanyID\" id=\"CompanyID\" value=\"");
      out.print(LangUtil.Empty(rs.getString(8)) );
      out.write("\" size=\"40um\"><a href=\"#content\" onclick=\"RedundancyEmployee(document.getElementById('CompanyID').value,");
      out.print(LangUtil.Empty(LangUtil.Empty(rs.getString(6))) );
      out.write(")\"><img src=\"/TrustWinPro/action/image/interface/search.png\" class=\"search\"></a></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"block\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"header\">");
      out.print(Lanfunc.language(lan, 39));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t<div >\r\n");
      out.write("\t\t\t\t\t\t<select name=\"Department\" class=\"mainselect\">\r\n");

	for(int i=0;i < cata.length;i++){

      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<option value = \"");
      out.print(cata[i].getIdx());
      out.write('"');
      out.write(' ');
      out.print(cata[i].getIdx() == rs.getInt(9) ? "selected" : "" );
      out.write('>');
      out.print(cata[i].getName() );
      out.write("</option>\r\n");

	}

      out.write("\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"block\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"header\">");
      out.print(Lanfunc.language(lan, 40));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"main\"><input type=\"text\" name=\"Position\" value=\"");
      out.print(LangUtil.Empty(rs.getString(10)) );
      out.write("\" size=\"40um\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"block\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"header\">");
      out.print(Lanfunc.language(lan, 41));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"main\"><input type=\"text\" name=\"TelOffice\" value=\"");
      out.print(LangUtil.Empty(rs.getString(11)) );
      out.write("\" size=\"40um\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"block\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"header\">");
      out.print(Lanfunc.language(lan, 42));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"main\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"EngagedDay\" readonly=\"readOnly\" value=\"");
      out.print(LangUtil.Empty(rs.getString(12)) );
      out.write("\" size=\"40um\" onclick=\"fnPopUpCalendar(EngagedDay,EngagedDay,'yyyy-mm-dd')\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"block\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"header\">");
      out.print(Lanfunc.language(lan, 43) );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"main\"><input type=\"text\" name=\"LatestPromoted\" readonly=\"readOnly\" value=\"");
      out.print(LangUtil.Empty(rs.getString(13)) );
      out.write("\" size=\"40um\" onclick=\"fnPopUpCalendar(LatestPromoted,LatestPromoted,'yyyy-mm-dd')\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"block\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"header\">");
      out.print(Lanfunc.language(lan, 44) );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"main\"><input type=\"text\" name=\"RetiredDay\" readonly=\"readOnly\" value=\"");
      out.print(LangUtil.Empty(rs.getString(14)) );
      out.write("\" size=\"40um\" onclick=\"fnPopUpCalendar(RetiredDay,RetiredDay,'yyyy-mm-dd')\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"block\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"header\">");
      out.print(Lanfunc.language(lan, 45) );
      out.write("1</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"main\"><input type=\"text\" name=\"License1\" value=\"");
      out.print(LangUtil.Empty(rs.getString(15)) );
      out.write("\" size=\"40um\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"block\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"header\">");
      out.print(Lanfunc.language(lan, 45) );
      out.write("2</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"main\"><input type=\"text\" name=\"License2\" value=\"");
      out.print(LangUtil.Empty(rs.getString(16)) );
      out.write("\" size=\"40um\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"block\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"header\">");
      out.print(Lanfunc.language(lan, 45) );
      out.write("3</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"main\"><input type=\"text\" name=\"License3\" value=\"");
      out.print(LangUtil.Empty(rs.getString(17)) );
      out.write("\" size=\"40um\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"block\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"header\">");
      out.print(Lanfunc.language(lan, 46) );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"main\"><input type=\"text\" name=\"HourlyWage\" value=\"");
      out.print(LangUtil.Empty(rs.getString(18)) );
      out.write("\" size=\"40um\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"block\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"header\">");
      out.print(Lanfunc.language(lan, 47) );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"main\"><input type=\"text\" name=\"Email\" value=\"");
      out.print(LangUtil.Empty(rs.getString(19)) );
      out.write("\" size=\"40um\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"Private\" id=\"tab2\">\r\n");
      out.write("\t\t\t\t<div class=\"InfoBox\">\r\n");
      out.write("\t\t\t\t\t<div class=\"block\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"header\">");
      out.print(Lanfunc.language(lan, 48) );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t<div >\r\n");
      out.write("\t\t\t\t\t\t\t<select name=\"Sex\" class=\"mainselect\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value = \"\" >");
      out.print(Lanfunc.language(lan, 172) );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value = \"\" >");
      out.print(Lanfunc.language(lan, 173) );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"block\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"header\">");
      out.print(Lanfunc.language(lan, 49) );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t<div >\r\n");
      out.write("\t\t\t\t\t\t\t<select name=\"Married\" class=\"mainselect\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value = \"\" >");
      out.print(Lanfunc.language(lan, 174) );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value = \"\" >");
      out.print(Lanfunc.language(lan, 175) );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"block\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"header\">");
      out.print(Lanfunc.language(lan, 50) );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"main\"><input type=\"text\" name=\"ResidentRegNo\" value=\"");
      out.print(LangUtil.Empty(rs.getString(22)) );
      out.write("\" size=\"40um\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"block\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"header\">");
      out.print(Lanfunc.language(lan, 51) );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"main\"><input type=\"text\" name=\"TelHome\" value=\"");
      out.print(LangUtil.Empty(rs.getString(23)) );
      out.write("\" size=\"40um\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"block\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"header\">");
      out.print(Lanfunc.language(lan, 52) );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"main\"><input type=\"text\" name=\"MobilePhone\" value=\"");
      out.print(LangUtil.Empty(rs.getString(24)) );
      out.write("\" size=\"40um\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"block\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"header\">");
      out.print(Lanfunc.language(lan, 53) );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"main\"><input type=\"text\" name=\"CarName\" value=\"");
      out.print(LangUtil.Empty(rs.getString(25)) );
      out.write("\" size=\"40um\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"block\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"header\">");
      out.print(Lanfunc.language(lan, 54) );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"main\"><input type=\"text\" name=\"Zipcode\" value=\"");
      out.print(LangUtil.Empty(rs.getString(26)) );
      out.write("\" size=\"40um\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"block\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"header\">");
      out.print(Lanfunc.language(lan, 3) );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"main\"><input type=\"text\" name=\"Address\" value=\"");
      out.print(LangUtil.Empty(rs.getString(27)) );
      out.write("\" size=\"40um\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"Card\" id=\"tab3\">\r\n");
      out.write("\t\t\t\t<div class=\"InfoBox\">\r\n");
      out.write("\t\t\t\t\t<div class=\"block\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"header\">");
      out.print(Lanfunc.language(lan, 55) );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"main\"><input type=\"text\" name=\"CardID\" id=\"CardID\" value=\"");
      out.print(LangUtil.Empty(rs.getString(28)) );
      out.write("\" size=\"40um\"><a href=\"#content\" onclick=\"RedundancyCard(document.getElementById('CardID').value,");
      out.print(LangUtil.Empty(LangUtil.Empty(rs.getString(6))) );
      out.write(")\"><img src=\"/TrustWinPro/action/image/interface/search.png\" class=\"search\"></a></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"block\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"header\">");
      out.print(Lanfunc.language(lan, 56) );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t<div >\r\n");
      out.write("\t\t\t\t\t\t\t<select name=\"CardType\" class=\"mainselect\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value = \"0\" ");
if(rs.getString(29)!=null){if(!rs.getString(29).equals("")){if(Integer.parseInt(rs.getString(29)) == 0){out.println("selected");}}} 
      out.write(">Standard 26 Bit</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value = \"1\" ");
if(rs.getString(29)!=null){if(!rs.getString(29).equals("")){if(Integer.parseInt(rs.getString(29)) == 1){out.println("selected");}}} 
      out.write(">Binary(Mifare 34 Bit)</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value = \"2\" ");
if(rs.getString(29)!=null){if(!rs.getString(29).equals("")){if(Integer.parseInt(rs.getString(29)) == 2){out.println("selected");}}} 
      out.write(">Keico 37bit</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value = \"3\" ");
if(rs.getString(29)!=null){if(!rs.getString(29).equals("")){if(Integer.parseInt(rs.getString(29)) == 3){out.println("selected");}}} 
      out.write(">SSMT 37bit</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value = \"4\" ");
if(rs.getString(29)!=null){if(!rs.getString(29).equals("")){if(Integer.parseInt(rs.getString(29)) == 4){out.println("selected");}}} 
      out.write(">Standard 36bit</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value = \"5\" ");
if(rs.getString(29)!=null){if(!rs.getString(29).equals("")){if(Integer.parseInt(rs.getString(29)) == 5){out.println("selected");}}} 
      out.write(">Corporation-1000 35bit</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value = \"6\" ");
if(rs.getString(29)!=null){if(!rs.getString(29).equals("")){if(Integer.parseInt(rs.getString(29)) == 6){out.println("selected");}}} 
      out.write(">PCSC 37bit</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value = \"7\" ");
if(rs.getString(29)!=null){if(!rs.getString(29).equals("")){if(Integer.parseInt(rs.getString(29)) == 7){out.println("selected");}}} 
      out.write(">Binary(Mifare 32 Bit)</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"block\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"header\">");
      out.print(Lanfunc.language(lan, 57) );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"main\"><input type=\"text\" name=\"FacilityCode\" value=\"");
      out.print(LangUtil.Empty(rs.getString(30)) );
      out.write("\" size=\"40um\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"block\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"header\">");
      out.print(Lanfunc.language(lan, 58) );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t<div >\r\n");
      out.write("\t\t\t\t\t\t\t<select name=\"CardAttribute\" class=\"mainselect\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value = \"0\" ");
if(rs.getString(31)!=null){if(!rs.getString(29).equals("")){if(Integer.parseInt(rs.getString(31)) == 0){out.println("selected");}}} 
      out.write(">Normal</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value = \"1\" ");
if(rs.getString(31)!=null){if(!rs.getString(29).equals("")){if(Integer.parseInt(rs.getString(31)) == 1){out.println("selected");}}} 
      out.write(">Handicapped</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value = \"2\" ");
if(rs.getString(31)!=null){if(!rs.getString(29).equals("")){if(Integer.parseInt(rs.getString(31)) == 2){out.println("selected");}}} 
      out.write(">Lost Card</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"block\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"header\">");
      out.print(Lanfunc.language(lan, 59) );
      out.write("1</div>\r\n");
      out.write("\t\t\t\t\t\t<div >\r\n");
      out.write("\t\t\t\t\t\t\t<select name=\"TimeZoneNo1\" class=\"mainselect\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value = \"0\" >All</option>\r\n");

	AccessGroup[] access = Accfunc.AccessGroupMenu();
	for(int i = 0;access.length>i;i++){	

      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value = \"");
      out.print(access[i].getIdx() );
      out.write('"');
      out.write(' ');
      out.write('>');
      out.print(access[i].getName() );
      out.write("</option>\r\n");

	}

      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value = \"257\" >None Time</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"block\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"header\">");
      out.print(Lanfunc.language(lan, 59) );
      out.write("2</div>\r\n");
      out.write("\t\t\t\t\t\t<div >\r\n");
      out.write("\t\t\t\t\t\t\t<select name=\"TimeZoneNo2\" class=\"mainselect\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value = \"0\" >All</option>\r\n");

	for(int i = 0;access.length>i;i++){	

      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value = \"");
      out.print(access[i].getIdx() );
      out.write('"');
      out.write(' ');
      out.write('>');
      out.print(access[i].getName() );
      out.write("</option>\r\n");

	}

      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value = \"257\" >None Time</option>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"block\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"header\">");
      out.print(Lanfunc.language(lan, 60) );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t<div >\r\n");
      out.write("\t\t\t\t\t\t\t<select name=\"UserMode\" class=\"mainselect\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value = \"0\" >Normal User</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value = \"1\" >AnyOne(ID or Card) User</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value = \"2\" >Black List</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"block\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"header\">");
      out.print(Lanfunc.language(lan, 61) );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t<div >\r\n");
      out.write("\t\t\t\t\t\t\t<select name=\"ReAccessLimitTime\" class=\"mainselect\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value = \"0\" >None</option>\r\n");

	for(int i=1;i<128;i++){

      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value = \"");
      out.print(i );
      out.write('"');
      out.write(' ');
if(rs.getString(39)!=null){if(rs.getString(39).equals(Integer.toString(i))){out.print("selected");}} 
      out.write('>');
      out.print(i);
      out.write("Min</option>\r\n");

	}

      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"block\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"header\">");
      out.print(Lanfunc.language(lan, 62) );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t<div >\r\n");
      out.write("\t\t\t\t\t\t\t<select name=\"UseSubSensor\" class=\"mainselect\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value = \"0\" >No</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value = \"1\" >YES</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"block\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"header\">");
      out.print(Lanfunc.language(lan, 63) );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t<div >\r\n");
      out.write("\t\t\t\t\t\t\t<select name=\"UseDuressFinger\" class=\"mainselect\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value = \"0\" >No</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value = \"1\" >FingerPrint1</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value = \"2\" >FingerPrint2</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"Device\" id=\"tab4\">\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t<col width=\"20%\" align=\"center\" >\r\n");
      out.write("\t\t\t\t\t\t<col width=\"80%\">\r\n");
      out.write("\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t<tr class=\"block\">\r\n");
      out.write("\t\t\t\t\t\t<td class=\"header\">");
      out.print(Lanfunc.language(lan, 64) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"main\">\r\n");
      out.write("\t\t\t\t\t\t\t<select name=\"Device\" onchange=\"deviceList(this.value);\" onload=\"deviceList(this.value);\" style = \"height:28px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value = \"0\" >-- ");
      out.print(Lanfunc.language(lan, 65) );
      out.write(" --</option>\r\n");

	DeviceGroup[] deviceGroup = null;
	deviceGroup = Devfunc.GroupDefind();
	
	int lengthD = deviceGroup.length;
	DeviceGroup[] dev = new DeviceGroup[lengthD];	
	dev = Devfunc.SortGroupOne(deviceGroup);
	for(int i=0;i < dev.length;i++){

      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value = \"");
      out.print(dev[i].getIdx());
      out.write('"');
      out.write(' ');
      out.print(dev[i].getIdx() == rs.getInt(38) ? "selected" : "" );
      out.write('>');
      out.print(dev[i].getGroupname() );
      out.write("</option>\r\n");

	}

      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"devicelist\">\r\n");

	int group= rs.getInt(38);
	int[] num = new int[1000];
	num[0] = group;
	Devfunc.setCount();
	if(group != 0){
		num = Devfunc.DeviceGroupIdx(group,num);

      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<table border=1 cellspacing=\"0\"  class=\"titleEx1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"12%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"12%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"16%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"12%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"14%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"12%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>");
      out.print(Lanfunc.language(lan, 66) );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>");
      out.print(Lanfunc.language(lan, 2) );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>");
      out.print(Lanfunc.language(lan, 3) );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>");
      out.print(Lanfunc.language(lan, 67) );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>");
      out.print(Lanfunc.language(lan, 5) );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>");
      out.print(Lanfunc.language(lan, 6) );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>");
      out.print(Lanfunc.language(lan, 69) );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>");
      out.print(Lanfunc.language(lan, 70) );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t<table class=\"ex1\" cellspacing=\"0\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"12%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"12%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"16%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"12%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"14%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"12%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\r\n");

		for(int i=0;i<num.length;i++){
			Device[] device = Devfunc.DeviceSelect2(num[i]);
			for(int j=0;j<device.length;j++){
				out.println("<tr>");
				out.println("<td>" + device[j].getControllerName() + "</td>");
				out.println("<td>" + device[j].getID() + "</td>");
				out.println("<td>" + device[j].getAddress() + "</td>");
				out.println("<td>" + device[j].getPort() + "</td>");
				out.println("<td>" + device[j].getPassword() + "</td>");
				out.println("<td>" + device[j].getUniqueID() + "</td>");
				out.println("<td>" + device[j].getServerPort() + "</td>");
				out.println("<td>" + device[j].getGroupIdx() + "</td>");
				out.println("</tr>");
			}
		}

      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");

	}else{}

      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");

	Event[] eventG = null;
	
	String start = null;
	String end = null;
	
	if(request.getParameter("start") == null){
		start = "";
	}else{
		start = (String)request.getParameter("start");
	}
	
	if(request.getParameter("end") == null){
		end = "";
	}else{
		end = (String)request.getParameter("end");
	}
	
	
	start = start.replace(" ", "");
	end = end.replace(" ", "");
	eventG = Evtfunc.EventDefind(start, end,ID);

      out.write("\r\n");
      out.write("\t\t\t<div class=\"Event\" id=\"tab5\">\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t<col width=\"20%\" align=\"center\" >\r\n");
      out.write("\t\t\t\t\t\t<col width=\"80%\">\r\n");
      out.write("\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t<tr >\r\n");
      out.write("\t\t\t\t\t\t<td class=\"main\" colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print(Lanfunc.language(lan, 71).trim() );
      out.write(" : <input type=\"text\" name=\"start\" value=\"");
      out.print(start);
      out.write("\" id=\"startDate\"  readonly=\"readOnly\" onclick=\"fnPopUpCalendar(startDate,startDate,'yyyy-mm-dd')\"  /> \r\n");
      out.write("\t\t\t\t\t\t\t~ \r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"end\" value=\"");
      out.print(end);
      out.write("\" id=\"endDate\"  readonly=\"readOnly\" onclick=\"fnPopUpCalendar(endDate,endDate,'yyyy-mm-dd')\"  /> \r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#search\" onclick=\"searchEvent(); \" ><img src=\"/TrustWinPro/action/image/interface/search.png\"></a>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"devicelist\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<table border=1 cellspacing=\"0\"  class=\"titleEx1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"14%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"12%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"12%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>");
      out.print(Lanfunc.language(lan, 72) );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>");
      out.print(Lanfunc.language(lan, 73) );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>");
      out.print(Lanfunc.language(lan, 74) );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>");
      out.print(Lanfunc.language(lan, 75) );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>");
      out.print(Lanfunc.language(lan, 76) );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>");
      out.print(Lanfunc.language(lan, 77) );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>");
      out.print(Lanfunc.language(lan, 78) );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>");
      out.print(Lanfunc.language(lan, 79) );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>");
      out.print(Lanfunc.language(lan, 80) );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t<table class=\"ex1\" cellspacing=\"0\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"14%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"12%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"12%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\r\n");

		for(int i=0;i < eventG.length;i++){
				out.println("<tr>");
				out.println("<td>" + eventG[i].getEventType() + "</td>");
				out.println("<td>" + eventG[i].getEventDate() + "</td>");
				out.println("<td>" + eventG[i].getEventTime() + "</td>");
				out.println("<td>" + eventG[i].getEventPlace() + "</td>");
				out.println("<td>" + eventG[i].getEventName() + "</td>");
				out.println("<td>" + eventG[i].getEventUserid() + "</td>");
				out.println("<td>" + eventG[i].getEventUserName() + "</td>");
				out.println("<td>" + eventG[i].getEventDoorState() + "</td>");
				out.println("<td>" + eventG[i].getEventCompanyId() + "</td>");
				out.println("</tr>");
			}

      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");

		

      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"AccessControl\" id=\"tab6\">\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t<col width=\"20%\" align=\"center\" >\r\n");
      out.write("\t\t\t\t\t\t<col width=\"80%\">\r\n");
      out.write("\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"devicelist\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<table border=1 cellspacing=\"0\"  class=\"titleEx1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>");
      out.print(Lanfunc.language(lan, 81) );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>");
      out.print(Lanfunc.language(lan, 82) );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t<table class=\"ex1\" cellspacing=\"0\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"40%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"60%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\r\n");

		AccessUser[] accessUser = Accfunc.SelAccessUserId(Integer.parseInt(ID));
		for(int j=0;j<accessUser.length;j++){
			AccessGroup accessGroup = Accfunc.SelAccessGroup(accessUser[j].getAccess());
			out.println("<tr>");
			out.println("<td>" + accessGroup.getName() + "</td>");
			out.println("<td>");
			AccessDevice[] ad = Accfunc.SelAccessDevice(accessGroup.getIdx());
			for(int k=0;k<ad.length;k++){
				Device device = Devfunc.selDevice(Integer.parseInt(ad[k].getDevice()));
				out.print("<p style='margin:0;padding:0;'>"+device.getControllerName()+"</p>");
			}
			out.println("</td>");
			out.println("</tr>");
		}

      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"buttonBox\">\r\n");
      out.write("\t\t\t\t<div class=\"bottom\" id=\"web-buttons-idrmij3\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" title=\"Enroll\" onclick=\"Recive('S,U,R,1,");
      out.print(ID);
      out.write(",E');\">");
      out.print(Lanfunc.language(lan, 184));
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" title=\"Delete\" onclick=\"Delete('S,U,D,1,");
      out.print(ID);
      out.write(",E');\">");
      out.print(Lanfunc.language(lan, 88));
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" title=\"Recive\" onclick=\"Enroll('S,U,E,1,");
      out.print(ID);
      out.write(",E');\">");
      out.print(Lanfunc.language(lan, 183));
      out.write("</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"InfoButtom\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#UserInfo\" onclick=\"UserInfoSubmit();\"><img src=\"/TrustWinPro/action/image/interface/submit.png\"></a>\r\n");
      out.write("\t\t\t\t\t<a href=\"#UserInfo\" onclick=\"UserDelete();\" ><img src=\"/TrustWinPro/action/image/interface/delete.png\"></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<form name=\"userDelete\" id=\"userDelete\" method=\"post\" action=\"page/UserInfoDelete.jsp\" >\r\n");
      out.write("\t<input type=\"hidden\" name=\"id\" value=\"");
      out.print(rs.getString(6) );
      out.write("\" />\r\n");
      out.write("</form>\r\n");
      out.write("<form action=\"/TrustWinPro/action/index.jsp\" name=\"eventLog\" id=\"eventLog\" method=\"post\">\r\n");
      out.write("\t<input type=\"hidden\" value=\"User\" name=\"left\" />\r\n");
      out.write("\t<input type=\"hidden\" value=\"UserInfo\" name=\"content\" />\r\n");
      out.write("\t<input type=\"hidden\" value=\"");
      out.print(ID );
      out.write("\" name=\"userID\" />\r\n");
      out.write("\t<input type=\"hidden\" value=\"\" name=\"start\" />\r\n");
      out.write("\t<input type=\"hidden\" value=\"\" name=\"end\" />\r\n");
      out.write("\t<input type=\"hidden\" value=\"1\" name=\"eventValue\" />\r\n");
      out.write("</form>\r\n");

			}
			rs.close();
			pstmt.close();
			conn.close();
		}catch(Exception e){
			out.println("DB error!!.");
			e.printStackTrace();
		}

      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");

if(request.getParameter("eventValue")!=null){
	if(request.getParameter("eventValue").equals("1")){

      out.write("\r\n");
      out.write("\t\tdisplayInfo(5);\r\n");

	}
}

      out.write("\r\n");
      out.write("$(\".Loading\").css(\"display\",\"none\");\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
