/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2015-02-27 15:34:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.action;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.Trustwin.Admin.Project.Dbcheck.*;

public final class Login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=euc-kr");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"/common/error/error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	DBCheck check = new DBCheck();
	check.AccessDeviceCheck();
	check.AccessGroupCheck();
	check.AccessUserCheck();
	check.AlarmTimeCheck();
	check.AutoDoorCheck();
	check.AutoKeyCheck();
	check.DepartCheck();
	check.DeviceGroupCheck();
	check.EventOptionCheck();
	check.History2Check();
	check.HistoryCheck();
	check.HistoryTempCheck();
	check.HolidaysCheck();
	check.LanguageCheck();
	check.ManageModeCheck();
	check.MemberCheck();
	check.NoActKeyCheck();
	check.SetupSerialCheck();
	check.SetupTcpipCheck();
	check.SunshineCheck();
	check.Table_1Check();
	check.TimezoneCheck();

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/TrustWinPro/action/css/common.css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"/TrustWinPro/action/js/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/TrustWinPro/action/js/jquery.ezmark.min.js\"></script>\r\n");
      out.write("<title>Login Page</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");

	String Id = (String)session.getAttribute("id");
	if(Id != null ){
		if(!Id.equals("")){

      out.write("\r\n");
      out.write("\tlocation.href=\"index.jsp\";\r\n");

		}
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\tfunction init(id){\r\n");
      out.write("\t\tdocument.getElementById(id).value = \"\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction indexSubmit(){\r\n");
      out.write("\t\tmember.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$(document).ready(\r\n");
      out.write("\t\tfunction(){\r\n");
      out.write("\t\t\t$(\"input[type=radio]\").ezMark();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t);\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"wrap\">\r\n");
      out.write("\t<div class=\"start\">\r\n");
      out.write("\t\t<div class=\"login\">\r\n");
      out.write("\t\t\t<form name=\"member\" method=\"post\" action=\"LoginProc.jsp\">\r\n");
      out.write("\t\t\t\t<div class=\"loginImage\"><img src=\"/TrustWinPro/action/image/interface/login01.png\" /></div>\r\n");
      out.write("\t\t\t\t<div class=\"loginLogo\"><img src=\"/TrustWinPro/action/image/interface/login02.png\" /></div>\r\n");
      out.write("\t\t\t\t<div class=\"inputBox\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"id\" class=\"id\" value=\"ID\" size=\"28\" id=\"id\" onclick=\"init('id');\"  onfocus=\"init(id);\"/>\r\n");
      out.write("\t\t\t\t\t<input type=\"password\" name=\"passwd\" class=\"password\" value=\"1111\" size=\"30\" id=\"pw\" onfocus=\"init('pw');\" onkeypress=\"if(event.keyCode==13){member.submit();}\"  />\r\n");
      out.write("\t\t\t\t\t<div class=\"radioBox\">\r\n");
      out.write("\t\t\t\t\t\t<label>en</label> <input type=\"radio\" value=\"en\" name=\"language\" checked />\r\n");
      out.write("\t\t\t\t\t\t<label>ko</label> <input type=\"radio\" value=\"ko\" name=\"language\" />\r\n");
      out.write("\t\t\t\t\t\t<label>etc</label> <input type=\"radio\" value=\"etc\" name=\"language\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"LoginButtom\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#in\" onclick=\"indexSubmit();\"><img src=\"/TrustWinPro/action/image/login/enter.png\" /></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"loginlogo\">\r\n");
      out.write("\t\t\t<img src=\"/TrustWinPro/action/image/interface/loginlogo.png\" />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
