/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2015-02-27 15:37:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.action.include;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import javax.sql.*;
import javax.naming.*;
import com.Trustwin.Admin.Project.Timezone.*;
import com.Trustwin.Admin.Project.Language.*;
import com.Trustwin.Admin.Project.Access.*;

public final class left_005ftime_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=euc-kr");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	LanguageFunc Lanfunc = new LanguageFunc();
	TimeZoneFunc Timefunc = new TimeZoneFunc();
	AccessFunc Accfunc = new AccessFunc();
	
	TimeZone[] times = Timefunc.TimeMenu();	
	String Num = "";
	AccessGroup[] access = Accfunc.AccessGroupMenu();
	if(request.getParameter("num") != null){
		Num = (String)request.getParameter("num");
	}
	String lan = (String)session.getAttribute("nation");

      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function InsertTime(){\r\n");
      out.write("\t$.ajax({      \r\n");
      out.write("\t    type:\"post\",  \r\n");
      out.write("\t    url:\"/TrustWinPro/action/ajax/InsertTimeZone.jsp\",   \r\n");
      out.write("\t    success:function(args){\r\n");
      out.write("\t    \tlocation.href = \"/TrustWinPro/action/index.jsp?left=Time&content=Time\";\r\n");
      out.write("\t    },   \r\n");
      out.write("\t    error:function(e){  \r\n");
      out.write("\t        alert(e.responseText);  \r\n");
      out.write("\t    }  \r\n");
      out.write("\t}); \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function InsertAccess(){\r\n");
      out.write("\t$.ajax({      \r\n");
      out.write("\t    type:\"post\",  \r\n");
      out.write("\t    url:\"/TrustWinPro/action/ajax/InsertAccessGroup.jsp\",   \r\n");
      out.write("\t    success:function(args){\r\n");
      out.write("\t    \tlocation.href = \"/TrustWinPro/action/index.jsp?left=Time&content=AccessGroup\";\r\n");
      out.write("\t    },   \r\n");
      out.write("\t    error:function(e){  \r\n");
      out.write("\t        alert(e.responseText);  \r\n");
      out.write("\t    }  \r\n");
      out.write("\t}); \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function Timesubmit(v){\r\n");
      out.write("\tvar form = document.getElementById(\"Time\");\r\n");
      out.write("\tform.num.value = v;\r\n");
      out.write("\tform.submit();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function Holidaysubmit(){\r\n");
      out.write("\tvar form = document.getElementById(\"Holiday\");\r\n");
      out.write("\tform.submit();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function Accesssubmit(v){\r\n");
      out.write("\tvar form = document.getElementById(\"AccessGroup\");\r\n");
      out.write("\tform.num.value = v;\r\n");
      out.write("\tform.submit();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function TimeAdd(){\r\n");
      out.write("\tif(document.getElementById(\"TimeAcess\").value == 1){\r\n");
      out.write("\t\t$.ajax({      \r\n");
      out.write("\t\t    type:\"post\",  \r\n");
      out.write("\t\t    url:\"/TrustWinPro/action/ajax/InsertTimeZone.jsp\",   \r\n");
      out.write("\t\t    success:function(args){\r\n");
      out.write("\t\t    \tlocation.href = \"/TrustWinPro/action/index.jsp?left=Time&content=Time\";\r\n");
      out.write("\t\t    },   \r\n");
      out.write("\t\t    error:function(e){  \r\n");
      out.write("\t\t        alert(e.responseText);  \r\n");
      out.write("\t\t    }  \r\n");
      out.write("\t\t}); \r\n");
      out.write("\t}else if(document.getElementById(\"TimeAcess\").value == 2){\r\n");
      out.write("\t\t$.ajax({      \r\n");
      out.write("\t\t    type:\"post\",  \r\n");
      out.write("\t\t    url:\"/TrustWinPro/action/ajax/InsertAccessGroup.jsp\",   \r\n");
      out.write("\t\t    success:function(args){\r\n");
      out.write("\t\t    \tlocation.href = \"/TrustWinPro/action/index.jsp?left=Time&content=AccessGroup\";\r\n");
      out.write("\t\t    },   \r\n");
      out.write("\t\t    error:function(e){  \r\n");
      out.write("\t\t        alert(e.responseText);  \r\n");
      out.write("\t\t    }  \r\n");
      out.write("\t\t}); \r\n");
      out.write("\t}else{\r\n");
      out.write("\t\talert(\"");
      out.print(Lanfunc.language(lan, 181) );
      out.write("\");\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function TimeDelete(v){\r\n");
      out.write("\tif(document.getElementById(\"TimeAcess\").value == 1){\r\n");
      out.write("\t\t$.ajax({      \r\n");
      out.write("\t\t    type:\"post\",  \r\n");
      out.write("\t\t    url:\"/TrustWinPro/action/ajax/DelTimeZone.jsp\",   \r\n");
      out.write("\t\t    data: \"num=\"+v,\r\n");
      out.write("\t\t    success:function(args){\r\n");
      out.write("\t\t    \tlocation.href = \"/TrustWinPro/action/index.jsp?left=Time&content=Time\";\r\n");
      out.write("\t\t    },   \r\n");
      out.write("\t\t    error:function(e){  \r\n");
      out.write("\t\t        alert(e.responseText);  \r\n");
      out.write("\t\t    }  \r\n");
      out.write("\t\t}); \r\n");
      out.write("\t}else if(document.getElementById(\"TimeAcess\").value == 2){\r\n");
      out.write("\t\t$.ajax({      \r\n");
      out.write("\t\t    type:\"post\",  \r\n");
      out.write("\t\t    url:\"/TrustWinPro/action/ajax/DelAccessGroup.jsp\",   \r\n");
      out.write("\t\t    data: \"num=\"+v,\r\n");
      out.write("\t\t    success:function(args){\r\n");
      out.write("\t\t    \tlocation.href = \"/TrustWinPro/action/index.jsp?left=Time&content=AccessGroup\";\r\n");
      out.write("\t\t    },   \r\n");
      out.write("\t\t    error:function(e){  \r\n");
      out.write("\t\t        alert(e.responseText);  \r\n");
      out.write("\t\t    }  \r\n");
      out.write("\t\t}); \r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<div class=\"Time\">\r\n");
      out.write("\t<ul>\r\n");
      out.write("\t\t<li><img src=\"/TrustWinPro/action/image/interface/accessgroup.png\" style=\"width:15px;\" alt=\"\"> ");
      out.print(Lanfunc.language(lan, 133) );
      out.write(" <a href=\"#a\" onclick=\"InsertAccess();\" >+</a>\r\n");
      out.write("\t\t\t<ul>\r\n");

		for(int i = 0;access.length>i;i++){	

      out.write("\r\n");
      out.write("\t\t\t\t<li id=\"access");
      out.print(access[i].getIdx());
      out.write("\"><img src=\"/TrustWinPro/action/image/interface/TimeZone-2.png\" style=\"width:13px;\"><a href=\"#content\" onclick=\"Accesssubmit('");
      out.print(access[i].getIdx() );
      out.write("');\" onkeypress=\"Accesssubmit('");
      out.print(access[i].getIdx() );
      out.write("');\" id=\"access");
      out.print(access[i].getIdx());
      out.write("a\" >");
      out.print(access[i].getName() );
      out.write("</a></li>\r\n");

		}

      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li><img src=\"/TrustWinPro/action/image/interface/TimeZone.png\" style=\"width:13px;\" alt=\"\"> ");
      out.print(Lanfunc.language(lan, 111) );
      out.write(" <a href=\"#a\" onclick=\"InsertTime();\" >+</a>\r\n");
      out.write("\t\t\t<ul>\r\n");

		for(int i = 0;times.length>i;i++){

      out.write("\r\n");
      out.write("\t\t\t\t<li id=\"time");
      out.print(times[i].getTimeZoneNo());
      out.write("\"><img src=\"/TrustWinPro/action/image/interface/TimeZone-2.png\" style=\"width:13px;\"><a href=\"#content\" onclick=\"Timesubmit('");
      out.print(times[i].getTimeZoneNo() );
      out.write("');\" onkeypress=\"Timesubmit('");
      out.print(times[i].getTimeZoneNo() );
      out.write("');\" id=\"time");
      out.print(times[i].getTimeZoneNo());
      out.write("a\" >");
      out.print(times[i].getTimeZoneName() );
      out.write("</a></li>\r\n");

		}

      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li><img src=\"/TrustWinPro/action/image/interface/Holiday.png\" alt=\"\" style=\"width:13px;\"> <a href=\"#\" onclick=\"Holidaysubmit();\" onkeypress=\"Holidaysubmit();\">Holiday</a></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"UserButtom\">\r\n");
      out.write("\t<a href=\"#in\" onclick=\"TimeAdd();\"><img src=\"/TrustWinPro/action/image/interface/add.jpg\" /></a>\r\n");
      out.write("\t<a href=\"#in\" onclick=\"TimeDelete(");
      out.print(Num);
      out.write(");\"><img src=\"/TrustWinPro/action/image/interface/del.png\" /></a>\r\n");
      out.write("</div>\r\n");
      out.write("<form action=\"/TrustWinPro/action/index.jsp\" name=\"Time\" id=\"Time\" method=\"post\">\r\n");
      out.write("\t<input type=\"hidden\" value=\"\" name=\"num\" />\r\n");
      out.write("\t<input type=\"hidden\" value=\"Time\" name=\"left\" />\r\n");
      out.write("\t<input type=\"hidden\" value=\"Time\" name=\"content\" />\r\n");
      out.write("\t<input type=\"hidden\" value=\"\" name=\"division\" id=\"division\" />\r\n");
      out.write("\t<input type=\"hidden\" value=\"\" name=\"numValue\" id=\"numValue\" />\r\n");
      out.write("\t<input type=\"hidden\" value=\"\" name=\"TimeAcess\" id=\"TimeAcess\" />\r\n");
      out.write("</form>\r\n");
      out.write("<form action=\"/TrustWinPro/action/index.jsp\" name=\"Holiday\" id=\"Holiday\" method=\"post\">\r\n");
      out.write("\t<input type=\"hidden\" value=\"\" name=\"num\" />\r\n");
      out.write("\t<input type=\"hidden\" value=\"Time\" name=\"left\" />\r\n");
      out.write("\t<input type=\"hidden\" value=\"Holiday\" name=\"content\" />\r\n");
      out.write("</form>\r\n");
      out.write("<form action=\"/TrustWinPro/action/index.jsp\" name=\"AccessGroup\" id=\"AccessGroup\" method=\"post\">\r\n");
      out.write("\t<input type=\"hidden\" value=\"\" name=\"num\" />\r\n");
      out.write("\t<input type=\"hidden\" value=\"Time\" name=\"left\" />\r\n");
      out.write("\t<input type=\"hidden\" value=\"AccessGroup\" name=\"content\" />\r\n");
      out.write("</form>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function SpanTimeClass(idx){\r\n");
      out.write("\tdocument.getElementById(\"time\"+idx).className = \"userspan\";\r\n");
      out.write("\tdocument.getElementById(\"time\"+idx+\"a\").style.color = \"#ffffff\";\r\n");
      out.write("\tdocument.getElementById(\"numValue\").value = idx;\r\n");
      out.write("\tdocument.getElementById(\"TimeAcess\").value = \"1\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function SpanAccessClass(idx){\r\n");
      out.write("\tdocument.getElementById(\"access\"+idx).className = \"userspan\";\r\n");
      out.write("\tdocument.getElementById(\"access\"+idx+\"a\").style.color = \"#ffffff\";\r\n");
      out.write("\tdocument.getElementById(\"numValue\").value = idx;\r\n");
      out.write("\tdocument.getElementById(\"TimeAcess\").value = \"2\";\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("if('");
      out.print(request.getParameter("content"));
      out.write("'=='Time'){\r\n");
      out.write("\tSpanTimeClass(");
      out.print(Num);
      out.write(");\r\n");
      out.write("}else{\r\n");
      out.write("\tSpanAccessClass(");
      out.print(Num);
      out.write(");\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
