/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2015-02-27 15:36:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.action.include;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import javax.sql.*;
import javax.naming.*;
import com.Trustwin.Admin.Project.Language.*;
import com.Trustwin.Admin.Project.Map.*;

public final class left_005fMonitoring_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=euc-kr");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	LanguageFunc Lanfunc = new LanguageFunc();
	MapFunc mapFunc = new MapFunc();
	
	Map map = mapFunc.topMap();
	Map[] maps = mapFunc.mapList();
	
	String lan = (String)session.getAttribute("nation");

      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction addMap(){\r\n");
      out.write("\t\t$.ajax({      \r\n");
      out.write("\t\t    type:\"post\",  \r\n");
      out.write("\t\t    url:\"/TrustWinPro/action/ajax/AddMap.jsp\",   \r\n");
      out.write("\t\t    success:function(args){\r\n");
      out.write("\t\t    \tlocation.href = \"/TrustWinPro/action/index.jsp?left=Monitoring&content=Map\";\r\n");
      out.write("\t\t    },   \r\n");
      out.write("\t\t    error:function(e){  \r\n");
      out.write("\t\t        alert(e.responseText);  \r\n");
      out.write("\t\t    }  \r\n");
      out.write("\t\t}); \t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction mapSubmit(v){\r\n");
      out.write("\t\tdocument.getElementById(\"Monitoring\").mapID.value = v;\r\n");
      out.write("\t\tdocument.getElementById(\"Monitoring\").submit();\r\n");
      out.write("\t}\t\t\r\n");
      out.write("</script>\r\n");
      out.write("<div class=\"Monitoring\">\r\n");
      out.write("\t<ul>\r\n");
      out.write("\t\t<li>Map <a href=\"#a\" onclick=\"addMap();\" onkeypress=\"addMap();\">+</a>\r\n");
      out.write("\t\t\t<ul>\r\n");

		for(int i = 0;i<maps.length;i++){

      out.write("\r\n");
      out.write("\t\t\t\t<li><a href=\"#a\" onclick=\"mapSubmit(");
      out.print(maps[i].getIdx() );
      out.write(")\" onkeypress=\"mapSubmit(");
      out.print(maps[i].getIdx() );
      out.write(')');
      out.write('"');
      out.write('>');
      out.print(maps[i].getName() );
      out.write("</a></li>\r\n");

		}

      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("</div>\r\n");
      out.write("<form action=\"/TrustWinPro/action/index.jsp\" name=\"Monitoring\" id=\"Monitoring\" method=\"post\">\r\n");
      out.write("\t<input type=\"hidden\" value=\"\" name=\"mapID\" />\r\n");
      out.write("\t<input type=\"hidden\" value=\"Monitoring\" name=\"left\" />\r\n");
      out.write("\t<input type=\"hidden\" value=\"Map\" name=\"content\" />\r\n");
      out.write("</form>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
