/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2015-11-16 05:36:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.action.include;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import javax.sql.*;
import javax.naming.*;
import com.Trustwin.Admin.Project.Category.*;
import com.Trustwin.Admin.Project.Language.*;
import com.Trustwin.Admin.Project.Device.*;
import com.Trustwin.Admin.Project.User.*;

public final class left_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	CategoryFunc Catefunc = new CategoryFunc();
	LanguageFunc Lanfunc = new LanguageFunc();
	UserFunc Userfunc = new UserFunc();
	DeviceFunc Devfunc = new DeviceFunc();
	
	String lan = (String)session.getAttribute("nation");

      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\tfunction UserAdd(num){\r\n");
      out.write("\t\t$.ajax({      \r\n");
      out.write("\t\t    type:\"post\",  \r\n");
      out.write("\t\t    url:\"/TrustWinPro/action/ajax/AddUser.jsp\",   \r\n");
      out.write("\t\t    data: \"depart=\"+num,\r\n");
      out.write("\t\t    success:function(args){\r\n");
      out.write("\t\t    \tlocation.href = \"/TrustWinPro/action/index.jsp?left=User&content=AllUser\";\r\n");
      out.write("\t\t    },   \r\n");
      out.write("\t\t    error:function(e){  \r\n");
      out.write("\t\t        alert(e.responseText);  \r\n");
      out.write("\t\t    }  \r\n");
      out.write("\t\t}); \r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction UserDelete(id){\r\n");
      out.write("\t\tvar del = confirm(\"");
      out.print(Lanfunc.language(lan, 103));
      out.write("\");\r\n");
      out.write("\t\tif(del){\r\n");
      out.write("\t\t\t$.ajax({      \r\n");
      out.write("\t\t\t    type:\"post\",  \r\n");
      out.write("\t\t\t    url:\"/TrustWinPro/action/ajax/DeleteUser.jsp\",   \r\n");
      out.write("\t\t\t    data: \"id=\"+id,\r\n");
      out.write("\t\t\t    success:function(args){\r\n");
      out.write("\t\t\t    \tlocation.href = \"/TrustWinPro/action/index.jsp?left=User&content=AllUser\";\r\n");
      out.write("\t\t\t    },   \r\n");
      out.write("\t\t\t    error:function(e){  \r\n");
      out.write("\t\t\t        alert(e.responseText);  \r\n");
      out.write("\t\t\t    }  \r\n");
      out.write("\t\t\t}); \r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction DepartAdd(){\r\n");
      out.write("\t\t$.ajax({      \r\n");
      out.write("\t\t    type:\"post\",  \r\n");
      out.write("\t\t    url:\"/TrustWinPro/action/ajax/AddDepart.jsp\",   \r\n");
      out.write("\t\t    data: \"num=\"+document.getElementById(\"GroupN\").value+\"&dep=\"+document.getElementById(\"GroupD\").value,\r\n");
      out.write("\t\t    success:function(args){   \r\n");
      out.write("\t\t    \tlocation.href = \"/TrustWinPro/action/index.jsp?left=User&content=AllUser\";\r\n");
      out.write("\t\t    },   \r\n");
      out.write("\t\t    error:function(e){  \r\n");
      out.write("\t\t        alert(e.responseText);  \r\n");
      out.write("\t\t    }  \r\n");
      out.write("\t\t}); \r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction DepartDelete(){\r\n");
      out.write("\t\tvar del = confirm(\"정말 삭제하시겠습니까?\");\r\n");
      out.write("\t\t$(\".Loading\").css(\"display\",\"block\");\r\n");
      out.write("\t\tif(del){\r\n");
      out.write("\t\t\t$.ajax({      \r\n");
      out.write("\t\t\t    type:\"post\",  \r\n");
      out.write("\t\t\t    url:\"/TrustWinPro/action/ajax/DeleteDepart.jsp\",   \r\n");
      out.write("\t\t\t    data: \"idx=\"+document.getElementById(\"GroupN\").value,\r\n");
      out.write("\t\t\t    success:function(args){   \r\n");
      out.write("\t\t\t    \tlocation.href = \"/TrustWinPro/action/index.jsp?left=User&content=AllUser\";\r\n");
      out.write("\t\t\t    },   \r\n");
      out.write("\t\t\t    error:function(e){  \r\n");
      out.write("\t\t\t        alert(e.responseText);  \r\n");
      out.write("\t\t\t    }  \r\n");
      out.write("\t\t\t}); \r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//device\r\n");
      out.write("\tfunction DeviceAdd(num){\r\n");
      out.write("\t\t$(\".Loading\").css(\"display\",\"block\");\r\n");
      out.write("\t\t$.ajax({      \r\n");
      out.write("\t\t    type:\"post\",  \r\n");
      out.write("\t\t    url:\"/TrustWinPro/action/ajax/AddDevice.jsp\",   \r\n");
      out.write("\t\t    data: \"group=\"+num,\r\n");
      out.write("\t\t    success:function(args){\r\n");
      out.write("\t\t    \targs = check(args);\r\n");
      out.write("\t\t    \tif(args != null && args != \"\"){\r\n");
      out.write("\t\t    \t\talert(args);\r\n");
      out.write("\t\t    \t}\r\n");
      out.write("\t\t    \t\r\n");
      out.write("\t\t    \tlocation.href = \"/TrustWinPro/action/index.jsp?left=Device&content=AllDevice\";\r\n");
      out.write("\t\t    },   \r\n");
      out.write("\t\t    error:function(e){  \r\n");
      out.write("\t\t        alert(e.responseText);  \r\n");
      out.write("\t\t    }  \r\n");
      out.write("\t\t}); \r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction GroupAdd(){\r\n");
      out.write("\t\t$.ajax({      \r\n");
      out.write("\t\t    type:\"post\",  \r\n");
      out.write("\t\t    url:\"/TrustWinPro/action/ajax/AddGroup.jsp\",   \r\n");
      out.write("\t\t    data: \"num=\"+document.getElementById(\"GroupN\").value+\"&dep=\"+document.getElementById(\"GroupD\").value,\r\n");
      out.write("\t\t    success:function(args){   \r\n");
      out.write("\t\t    \tlocation.href = \"/TrustWinPro/action/index.jsp?left=Device&content=AllDevice\";\r\n");
      out.write("\t\t    },   \r\n");
      out.write("\t\t    error:function(e){  \r\n");
      out.write("\t\t        alert(e.responseText);  \r\n");
      out.write("\t\t    }  \r\n");
      out.write("\t\t}); \r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction GroupDelete(){\r\n");
      out.write("\t\t$(\".Loading\").css(\"display\",\"block\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar del = confirm('");
      out.print(Lanfunc.language(lan, 103));
      out.write("');\r\n");
      out.write("\t\tvar idx = \"\";\r\n");
      out.write("\t\tvar Didx = \"\";\r\n");
      out.write("\t\tif(document.getElementById(\"GroupN\").value==\"\"){\r\n");
      out.write("\t\t\tDidx = ");
      out.print(request.getParameter("deviceID"));
      out.write(";\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tidx =  document.getElementById(\"GroupN\").value;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(del){\r\n");
      out.write("\t\t\t$.ajax({      \r\n");
      out.write("\t\t\t    type:\"post\",  \r\n");
      out.write("\t\t\t    url:\"/TrustWinPro/action/ajax/DeleteGroup.jsp\",   \r\n");
      out.write("\t\t\t    data: \"idx=\"+idx + \"&Didx=\" + Didx,\r\n");
      out.write("\t\t\t    success:function(args){   \r\n");
      out.write("\t\t\t    \tlocation.href = \"/TrustWinPro/action/index.jsp?left=Device&content=AllDevice\";\r\n");
      out.write("\t\t\t    },   \r\n");
      out.write("\t\t\t    error:function(e){  \r\n");
      out.write("\t\t\t        alert(e.responseText);  \r\n");
      out.write("\t\t\t    }  \r\n");
      out.write("\t\t\t}); \r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("<div id=\"left\">\r\n");
      out.write("\t<div class=\"left_bottom\">\r\n");
      out.write("\t\t<div class=\"left_buttom\">\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<a href=\"/TrustWinPro/action/index.jsp?left=Device&content=AllDevice\"><img src=\"/TrustWinPro/action/image/interface/device icon.png\" style=\"position:absolute;top:11px;left:30px;\"><img src=\"/TrustWinPro/action/image/interface/leftButtom_off.png\" id=\"deviceButtom\" style=\"width:100%;height:41px;\"><img src=\"/TrustWinPro/action/image/interface/leftarrow.png\" style=\"position:absolute;top:15px;right:20px;\"></a>\r\n");
      out.write("\t\t\t\t<div class=\"Device\">\r\n");
      out.write("\t\t\t\t\t<a href=\"/TrustWinPro/action/index.jsp?left=Device&content=AllDevice\">DEVICE</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\t\r\n");
      out.write("\t\t\t\t<a href=\"/TrustWinPro/action/index.jsp?left=User&content=AllUser\"><img src=\"/TrustWinPro/action/image/interface/user icon.png\" style=\"position:absolute;top:50px;left:30px;\"><img src=\"/TrustWinPro/action/image/interface/leftButtom_off.png\" id=\"userButtom\" style=\"width:100%;height:41px;\"><img src=\"/TrustWinPro/action/image/interface/leftarrow.png\" style=\"position:absolute;top:55px;right:20px;\"></a>\r\n");
      out.write("\t\t\t\t<div class=\"User\">\r\n");
      out.write("\t\t\t\t\t<a href=\"/TrustWinPro/action/index.jsp?left=User&content=AllUser\">USER</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\t\r\n");
      out.write("\t\t\t\t<a href=\"/TrustWinPro/action/index.jsp?left=Event\"><img src=\"/TrustWinPro/action/image/interface/event icon.png\" style=\"position:absolute;top:92px;left:30px;\"><img src=\"/TrustWinPro/action/image/interface/leftButtom_off.png\" id=\"eventButtom\" style=\"width:100%;height:41px;\"><img src=\"/TrustWinPro/action/image/interface/leftarrow.png\" style=\"position:absolute;top:92px;right:20px;\"></a>\r\n");
      out.write("\t\t\t\t<div class=\"Event\">\r\n");
      out.write("\t\t\t\t\t<a href=\"/TrustWinPro/action/index.jsp?left=Event\">EVENT</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<a href=\"/TrustWinPro/action/index.jsp?left=Time&content=AccessGroup\"><img src=\"/TrustWinPro/action/image/interface/time icon.png\" style=\"position:absolute;top:132px;left:30px;width:22px;\"><img src=\"/TrustWinPro/action/image/interface/leftButtom_off.png\" id=\"timeButtom\" style=\"width:100%;height:41px;\"><img src=\"/TrustWinPro/action/image/interface/leftarrow.png\" style=\"position:absolute;top:132px;right:20px;\"></a>\r\n");
      out.write("\t\t\t\t<div class=\"Time\">\r\n");
      out.write("\t\t\t\t\t<a href=\"/TrustWinPro/action/index.jsp?left=Time&content=AccessGroup\">ACCESS CONTROL</a>\r\n");
      out.write("\t\t\t\t</div>\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<a href=\"/TrustWinPro/action/index.jsp?left=Monitoring&content=Map\"><img src=\"/TrustWinPro/action/image/interface/time icon.png\" style=\"position:absolute;top:172px;left:30px;width:22px;\"><img src=\"/TrustWinPro/action/image/interface/leftButtom_off.png\" id=\"monitoringButtom\" style=\"width:100%;height:41px;\"><img src=\"/TrustWinPro/action/image/interface/leftarrow.png\" style=\"position:absolute;top:172px;right:20px;\"></a>\r\n");
      out.write("\t\t\t\t<div class=\"Monitoring\">\r\n");
      out.write("\t\t\t\t\t<a href=\"/TrustWinPro/action/index.jsp?left=Monitoring&content=Map\">MONITORING</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"left_top\">\r\n");

	// userInfo
	Category[] category = null;
	
	category = Catefunc.CategoryDefind();

	int length = category.length;
	Category[] cata = new Category[length];	
	cata = Catefunc.SortCategoryOne(category);

	//DeviceInfo
	DeviceGroup[] device = null;
	device = Devfunc.GroupDefind();
	
	int lengthD = device.length;
	DeviceGroup[] dev = new DeviceGroup[lengthD];	
	dev = Devfunc.SortGroupOne(device);
	
	String left = "";
	if(request.getParameter("left")!=null){
		left = request.getParameter("left");
	}else{
		left = "Event";
	}
	if(left.equals("Device")){

      out.write("\r\n");
      out.write("\t\t<div class=\"Device\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<span><img src=\"/TrustWinPro/action/image/interface/device.png\" alt=\"\"></span>\r\n");
      out.write("\t\t\t\t\t<span onclick=\"changeSpanDev(0,");
      out.print(lengthD );
      out.write(',');
      out.print(dev[0].getDepth() );
      out.write(',');
      out.print(dev[0].getIdx() );
      out.write(',');
      out.print(request.getParameter("deviceID"));
      out.write(")\" id=\"span0\" >");
      out.print(dev[0].getGroupname() );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t<span onclick=\"changeInputBox(0)\" id=\"text0\" class=\"span\">");
      out.print(dev[0].getGroupname() );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t<span id=\"input0\" class=\"spanInput\"><input type=\"text\" name=\"GroupName\" id=\"GroupName0\" class=\"inputText\" value=\"");
      out.print(dev[0].getGroupname() );
      out.write("\" size=\"5\" onkeypress=\"if(event.keyCode == 13) return UpdateDevice(this.value,'");
      out.print(dev[0].getIdx());
      out.write("')\" onblur=\"return UpdateDevice(this.value,'");
      out.print(dev[0].getIdx());
      out.write("')\" /></span>\r\n");
      out.write("\t\t\t\t\t<span><a href=\"#UserInfo\" onclick=\"submit('AllDevice');\" >All</a></span>\r\n");
      out.write("\t\t\t\t</li>\r\n");

		int padding = 0;
		int[] depth;
		int LastDepth = 0;
		int LastDepth2 = 0;
		depth = new int[100];
		
		int devcot = -1;
		for(int i=1;i<lengthD;i++){
			padding = dev[i].getDepth() * 20;
			
			if(i!= lengthD-1){
				if(dev[i].getDepth()<dev[i+1].getDepth()){
					devcot++;
					depth[devcot] = dev[i].getIdx();
				}
			}else{
				LastDepth = dev[i].getIdx();
				LastDepth2 = dev[i].getDepth();
			}
			
			Device[] dev2 = Devfunc.DeviceSelect(dev[i].getIdx());

      out.write("\r\n");
      out.write("\t\t\t\t<li style=\"padding-left:");
      out.print(padding);
      out.write("px\" >\r\n");
      out.write("\t\t\t\t\t<span><img src=\"/TrustWinPro/action/image/interface/device.png\" /></span>\r\n");
      out.write("\t\t\t\t\t<span id=\"span");
      out.print(i );
      out.write("\" >\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#in\" onclick=\"changeSpanDev(");
      out.print(i );
      out.write(',');
      out.print(lengthD );
      out.write(',');
      out.print(dev[i].getDepth() );
      out.write(',');
      out.print(dev[i].getIdx() );
      out.write(',');
      out.print(request.getParameter("deviceID"));
      out.write(')');
      out.write('"');
      out.write('>');
      out.print(dev[i].getGroupname() );
      out.write("</a><a href=\"#in\" onclick=\"swich('0");
      out.print(i);
      out.write('\'');
      out.write(',');
      out.print(i);
      out.write(")\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"/TrustWinPro/action/image/interface/close.png\" class=\"close");
      out.print(i );
      out.write("\" id=\"close0");
      out.print(i );
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"/TrustWinPro/action/image/interface/open.png\" class=\"open");
      out.print(i );
      out.write("\" id=\"open0");
      out.print(i );
      out.write("\" style=\"display:none;\" />\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t<span id=\"text");
      out.print(i);
      out.write("\" class=\"span\" >\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#in\" onclick=\"changeInputBox(");
      out.print(i);
      out.write(')');
      out.write('"');
      out.write('>');
      out.print(dev[i].getGroupname() );
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#in\" onclick=\"swich(");
      out.print(i);
      out.write(',');
      out.print(i);
      out.write(")\"><img src=\"/TrustWinPro/action/image/interface/close.png\" class=\"close");
      out.print(i );
      out.write("\" id=\"close");
      out.print(i );
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t<img src=\"/TrustWinPro/action/image/interface/open.png\" class=\"open");
      out.print(i );
      out.write("\" id=\"open");
      out.print(i );
      out.write("\" style=\"display:none;\" /></a></span>\r\n");
      out.write("\t\t\t\t\t<span id=\"input");
      out.print(i);
      out.write("\" class=\"spanInput\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"GroupName\" id=\"GroupName");
      out.print(i);
      out.write("\" class=\"inputText\" value=\"");
      out.print(dev[i].getGroupname() );
      out.write("\" size=\"5\" onkeypress=\"if(event.keyCode == 13) return UpdateDevice(this.value,'");
      out.print(dev[i].getIdx());
      out.write("')\" onblur=\"return UpdateDevice(this.value,'");
      out.print(dev[i].getIdx());
      out.write("')\"  />\r\n");

			if(dev2.length>0){

      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#in\" onclick=\"swich(");
      out.print(i);
      out.write(")\">-</a>\r\n");

			}

      out.write("\r\n");
      out.write("\t\t\t\t\t</span> \r\n");

			
			if(dev2.length != 0){
				if(i!=lengthD-1){
					if(dev2!=null&&dev[i+1].getUpnumber() != dev[i].getIdx()){
						padding = (dev[i].getDepth()+1) * 30;
						if(0<dev2.length){

      out.write("\r\n");
      out.write("\t\t\t\t\t<ul id=\"");
      out.print(i);
      out.write("\">\r\n");

						}
						for(int j=0;j<dev2.length;j++){

      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li id=\"dev");
      out.print(dev2[j].getID() );
      out.write("\" style=\"padding-left:15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"/TrustWinPro/action/image/interface/deviceIcon.png\"><a href=\"#content\" onclick=\"submitDevice('Device','");
      out.print(dev2[j].getID() );
      out.write("');\" onkeypress=\"submitDevice('Device','");
      out.print(dev2[j].getID() );
      out.write("');\" id=\"dev");
      out.print(dev2[j].getID() );
      out.write('a');
      out.write('"');
      out.write('>');
      out.print(dev2[j].getControllerName() );
      out.write("</a>\r\n");

						if(j==dev2.length-1){

      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#in\" onclick=\"DeviceAdd(");
      out.print(dev2[j].getGroupIdx() );
      out.write(");\"><img src=\"/TrustWinPro/action/image/interface/plus.png\"></a>\r\n");
							
						}

      out.write("\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");

						}
						if(0<dev2.length){

      out.write("\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");

						}
					}
				}
			}else if(i!= lengthD-1){
				if(dev[i].getDepth()>dev[i+1].getDepth()){
					if(dev[i+1].getDepth()<dev[i].getDepth()){

      out.write("\r\n");
      out.write("\t\t\t\t\t<ul id=\"");
      out.print(i);
      out.write("\">\r\n");

					}
					for(int k=dev[i+1].getDepth();k<dev[i].getDepth();k++){
						Device[] dev1 = Devfunc.DeviceSelect(depth[devcot]);
						padding = (devcot+2) * 30;
						for(int j=0;j<dev1.length;j++){

      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li id=\"dev");
      out.print(dev1[j].getID() );
      out.write("\" style=\"padding-left:15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"/TrustWinPro/action/image/interface/deviceIcon.png\"><a href=\"#content\" onclick=\"submitDevice('Device','");
      out.print(dev1[j].getID() );
      out.write("');\" onkeypress=\"submitDevice('Device','");
      out.print(dev1[j].getID() );
      out.write("');\" id=\"dev");
      out.print(dev1[j].getID() );
      out.write('a');
      out.write('"');
      out.write('>');
      out.print(dev1[j].getControllerName() );
      out.write("</a>\r\n");

						if(j==dev1.length-1){

      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#in\" onclick=\"DeviceAdd(");
      out.print(dev1[j].getGroupIdx() );
      out.write(");\"><img src=\"/TrustWinPro/action/image/interface/plus.png\"></a>\r\n");
							
						}

      out.write("\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
 
						}
						devcot--;
					}
					if(dev[i+1].getDepth()<dev[i].getDepth()){

      out.write("\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");

					}
				}
			}

      out.write("\r\n");
      out.write("\t\t\t\t\r\n");

		}
		
		for(int i = 0;i<=LastDepth2;i++){
			if(i>0){
				LastDepth = Devfunc.GroupUpNum(LastDepth);
			}
			Device[] dev1 = Devfunc.DeviceSelect(LastDepth);
			if(0<dev1.length){

      out.write("\r\n");
      out.write("\t\t\t\t\t<ul id=\"");
      out.print(lengthD-1);
      out.write("\">\r\n");
				
			}
			for(int j=0;j<dev1.length;j++){

      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li id=\"dev");
      out.print(dev1[j].getID() );
      out.write("\" style=\"padding-left:15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"/TrustWinPro/action/image/interface/deviceIcon.png\"><a href=\"#content\" onclick=\"submitDevice('Device','");
      out.print(dev1[j].getID() );
      out.write("');\" onkeypress=\"submitDevice('Device','");
      out.print(dev1[j].getID() );
      out.write("');\" id=\"dev");
      out.print(dev1[j].getID() );
      out.write('a');
      out.write('"');
      out.write('>');
      out.print(dev1[j].getControllerName() );
      out.write("</a>\r\n");

						if(j==dev1.length-1){

      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#in\" onclick=\"DeviceAdd(");
      out.print(dev1[j].getGroupIdx() );
      out.write(");\"><img src=\"/TrustWinPro/action/image/interface/plus.png\"></a>\r\n");
							
						}

      out.write("\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
 
			}
			if(0<dev1.length){

      out.write("\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");

			}
		}

      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"DeviceButtom\">\r\n");
      out.write("\t\t\t<a href=\"#in\" onclick=\"GroupAdd();\"><img src=\"/TrustWinPro/action/image/interface/add.jpg\" /></a>\r\n");
      out.write("\t\t\t<a href=\"#in\" onclick=\"GroupDelete();\"><img src=\"/TrustWinPro/action/image/interface/del.png\" /></a>\r\n");
      out.write("\t\t\t<a href=\"#in\" onclick=\"DeviceAdd(document.getElementById('GroupN').value)\"><img src=\"/TrustWinPro/action/image/interface/modify.png\" /></a>\r\n");
      out.write("\t\t</div>\r\n");

	}else if(left.equals("User")){

      out.write("\r\n");
      out.write("\t\t<div class=\"User\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<span><img src=\"/TrustWinPro/action/image/interface/user.png\" /></span>\r\n");
      out.write("\t\t\t\t\t<span onclick=\"changeSpanUser(0,");
      out.print(length );
      out.write(',');
      out.print(cata[0].getDepth() );
      out.write(',');
      out.print(cata[0].getIdx() );
      out.write(',');
      out.print(request.getParameter("userID"));
      out.write(")\" id=\"span0\" >");
      out.print(cata[0].getName() );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t<span onclick=\"changeInputBox(0)\" id=\"text0\" class=\"span\">");
      out.print(cata[0].getName());
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t<span id=\"input0\" class=\"spanInput\"><input type=\"text\" name=\"name\" id=\"name\" class=\"inputText\" value=\"");
      out.print(cata[0].getName());
      out.write("\" size=\"10\" onkeypress=\"if(event.keyCode == 13) return UpdateDepart(this.value,'");
      out.print(cata[0].getIdx());
      out.write("')\" onblur=\"UpdateDepart(this.value,'");
      out.print(cata[0].getIdx());
      out.write("');\"  /></span>\r\n");
      out.write("\t\t\t\t\t<span><a href=\"#UserInfo\" onclick=\"submit('AllUser');\" >All</a></span> \r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\r\n");

		int padding = 0;
		int[] depth;
		int LastDepth = 0;
		int LastDepth2 = 0;
		depth = new int[100];
		
		int depcot = -1;
		for(int i=1;i<length;i++){
			padding = cata[i].getDepth() * 30;
			
			if(i!= length-1){
				if(cata[i].getDepth()<cata[i+1].getDepth()){
					depcot++;
					depth[depcot] = cata[i].getIdx();
				}
			}else{
				LastDepth = cata[i].getIdx();
				LastDepth2 = cata[i].getDepth();	
			}

      out.write("\r\n");
      out.write("\t\t\t\t<li style=\"padding-left:");
      out.print(padding);
      out.write("px\">\r\n");
      out.write("\t\t\t\t\t<span><img src=\"/TrustWinPro/action/image/interface/user.png\" /></span>\r\n");
      out.write("\t\t\t\t\t<span id=\"span");
      out.print(i );
      out.write("\" ><a href=\"#in\" onclick=\"changeSpanUser(");
      out.print(i );
      out.write(',');
      out.print(length );
      out.write(',');
      out.print(cata[i].getDepth() );
      out.write(',');
      out.print(cata[i].getIdx() );
      out.write(',');
      out.print(request.getParameter("userID"));
      out.write(')');
      out.write('"');
      out.write('>');
      out.print(cata[i].getName() );
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#in\" onclick=\"swich('0");
      out.print(i);
      out.write('\'');
      out.write(',');
      out.print(i);
      out.write(")\"><img src=\"/TrustWinPro/action/image/interface/close.png\" class=\"close");
      out.print(i );
      out.write("\" id=\"close0");
      out.print(i );
      out.write("\" /></a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#in\" onclick=\"swich('0");
      out.print(i);
      out.write('\'');
      out.write(',');
      out.print(i);
      out.write(")\"><img src=\"/TrustWinPro/action/image/interface/open.png\" class=\"open");
      out.print(i );
      out.write("\" id=\"open0");
      out.print(i );
      out.write("\" style=\"display:none;\" /></a>\r\n");
      out.write("\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t<span id=\"text");
      out.print(i);
      out.write("\" class=\"span\" >\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#in\" onclick=\"changeInputBox(");
      out.print(i);
      out.write(")\" >");
      out.print(cata[i].getName() );
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#in\" onclick=\"swich(");
      out.print(i);
      out.write(',');
      out.print(i);
      out.write(")\"><img src=\"/TrustWinPro/action/image/interface/close.png\" class=\"close");
      out.print(i );
      out.write("\" id=\"close");
      out.print(i );
      out.write("\" /></a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#in\" onclick=\"swich(");
      out.print(i);
      out.write(',');
      out.print(i);
      out.write(")\"><img src=\"/TrustWinPro/action/image/interface/close.png\" class=\"open");
      out.print(i );
      out.write("\" id=\"open");
      out.print(i );
      out.write("\" style=\"display:none;\" /></a>\r\n");
      out.write("\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t<span id=\"input");
      out.print(i);
      out.write("\" class=\"spanInput\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"name\" id=\"name\" class=\"inputText\" value=\"");
      out.print(cata[i].getName() );
      out.write("\" size=\"10\" onkeypress=\"if(event.keyCode == 13) return UpdateDepart(this.value,'");
      out.print(cata[i].getIdx());
      out.write("');\" onblur=\"UpdateDepart(this.value,'");
      out.print(cata[i].getIdx());
      out.write("');\" />\r\n");
      out.write("\t\t\t\t\t</span> \r\n");

			User[] user2 = Userfunc.UserSelect(cata[i].getIdx());

			
			if(i!=length-1){
				if(user2!=null&&cata[i+1].getUpnumber() != cata[i].getIdx()){
					if(user2.length>0){

      out.write("\r\n");
      out.write("\t\t\t\t<ul id=\"");
      out.print(i);
      out.write("\">\r\n");

					}
					for(int j=0;j<user2.length;j++){

      out.write("\r\n");
      out.write("\t\t\t\t\t<li id=\"user");
      out.print(user2[j].getId());
      out.write("\" style=\"padding-left:15px;\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"/TrustWinPro/action/image/interface/leftusericon.png\"><a href=\"#content\" onclick=\"submitUser('User','");
      out.print(user2[j].getUserId() );
      out.write("');\" onkeypress=\"submit('User','");
      out.print(user2[j].getUserId() );
      out.write("');\" >");
      out.print(user2[j].getName() );
      out.write("</a>\r\n");

						if(j==user2.length-1){

      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#in\" onclick=\"UserAdd(");
      out.print(user2[j].getDepartment() );
      out.write(");\"><img src=\"/TrustWinPro/action/image/interface/plus.png\"></a>\r\n");
							
						}

      out.write("\r\n");
      out.write("\t\t\t\t\t</li>\r\n");

					}
					if(user2.length>0){

      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");

					}
				}

				if(cata[i].getDepth()>cata[i+1].getDepth()){
					for(int k=cata[i+1].getDepth();k<cata[i].getDepth();k++){
						User[] user1 = Userfunc.UserSelect(depth[depcot]);
						if(user1.length>0){

      out.write("\r\n");
      out.write("\t\t\t\t<ul id=\"");
      out.print(i);
      out.write("\">\r\n");

						}
						for(int j=0;j<user1.length;j++){

      out.write("\r\n");
      out.write("\t\t\t\t\t<li id=\"user");
      out.print(user1[j].getId());
      out.write("\" style=\"padding-left:15px;\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"/TrustWinPro/action/image/interface/leftusericon.png\"><a href=\"#content\" onclick=\"submitUser('User','");
      out.print(user1[j].getUserId() );
      out.write("');\" onkeypress=\"submit('User','");
      out.print(user1[j].getUserId() );
      out.write("');\" >");
      out.print(user1[j].getName() );
      out.write("</a>\r\n");

							if(j==user1.length-1){

      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#in\" onclick=\"UserAdd(");
      out.print(user1[j].getDepartment() );
      out.write(");\"><img src=\"/TrustWinPro/action/image/interface/plus.png\"></a>\r\n");
							
							}

      out.write("\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
 
						}
						depcot--;
						if(user1.length>0){

      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");

						}
					}
				}
			}

		}
		for(int i = 0;i<=LastDepth2;i++){
			if(i>0){
				LastDepth = Catefunc.CataUpNum(LastDepth);
			}
			User[] user1 = Userfunc.UserSelect(LastDepth);
			if(user1.length>0){

      out.write("\r\n");
      out.write("\t\t\t\t<ul id=\"");
      out.print(length-1);
      out.write("\">\r\n");

			}
			for(int j=0;j<user1.length;j++){

      out.write("\r\n");
      out.write("\t\t\t\t\t<li id=\"user");
      out.print(user1[j].getId());
      out.write("\" style=\"padding-left:15px;\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"/TrustWinPro/action/image/interface/leftusericon.png\"><a href=\"#content\" onclick=\"submitUser('User','");
      out.print(user1[j].getUserId() );
      out.write("');\" onkeypress=\"submit('User','");
      out.print(user1[j].getUserId() );
      out.write("');\" >");
      out.print(user1[j].getName() );
      out.write("</a>\r\n");

						if(j==user1.length-1){

      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#in\" onclick=\"UserAdd(");
      out.print(user1[j].getDepartment() );
      out.write(");\"><img src=\"/TrustWinPro/action/image/interface/plus.png\"></a>\r\n");
							
						}

      out.write("\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
 
			}
			if(user1.length>0){

      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");

			}
			
		}

      out.write("\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"UserButtom\">\r\n");
      out.write("\t\t\t<a href=\"#in\" onclick=\"DepartAdd();\"><img src=\"/TrustWinPro/action/image/interface/add.jpg\" /></a>\r\n");
      out.write("\t\t\t<a href=\"#in\" onclick=\"DepartDelete();\"><img src=\"/TrustWinPro/action/image/interface/del.png\" /></a>\r\n");
      out.write("\t\t\t<a href=\"#in\" onclick=\"UserAdd(document.getElementById('GroupN').value)\"><img src=\"/TrustWinPro/action/image/interface/modify.png\" /></a>\r\n");
      out.write("\t\t</div>\r\n");

	}else if(left.equals("Event")){

      out.write("\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "left_event.jsp", out, false);
      out.write('\r');
      out.write('\n');

	}else if(left.equals("Monitoring")){

      out.write("\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "left_Monitoring.jsp", out, false);
      out.write('\r');
      out.write('\n');

	}else{

      out.write("\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "left_time.jsp", out, false);
      out.write('\r');
      out.write('\n');

	}
		

      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<form>\r\n");
      out.write("\t<input type=\"hidden\" value=\"\" name=\"deviceName\" id=\"deviceName\" />\r\n");
      out.write("\t<input type=\"hidden\" value=\"\" name=\"GroupN\" id=\"GroupN\" />\r\n");
      out.write("\t<input type=\"hidden\" value=\"\" name=\"GroupD\" id=\"GroupD\" />\r\n");
      out.write("</form>\r\n");
      out.write("<form action=\"/TrustWinPro/action/index.jsp\" name=\"realLog\" id=\"realLog\" method=\"post\">\r\n");
      out.write("\t<input type=\"hidden\" value=\"realLog\"  name=\"logtype\" />\r\n");
      out.write("\t<input type=\"hidden\" value=\"Event\" name=\"left\" />\r\n");
      out.write("\t<input type=\"hidden\" value=\"Log\" name=\"content\" />\r\n");
      out.write("</form>\r\n");
      out.write("<form action=\"/TrustWinPro/action/index.jsp\" name=\"searchLog\" id=\"searchLog\" method=\"post\">\r\n");
      out.write("\t<input type=\"hidden\" value=\"searchLog\" name=\"logtype\" />\r\n");
      out.write("\t<input type=\"hidden\" value=\"Event\" name=\"left\" />\r\n");
      out.write("\t<input type=\"hidden\" value=\"Log\" name=\"content\" />\r\n");
      out.write("</form>\r\n");
      out.write("<form action=\"/TrustWinPro/action/index.jsp\" name=\"User\" id=\"User\" method=\"post\">\r\n");
      out.write("\t<input type=\"hidden\" value=\"User\" name=\"left\" />\r\n");
      out.write("\t<input type=\"hidden\" value=\"\" name=\"userID\" />\r\n");
      out.write("\t<input type=\"hidden\" value=\"UserInfo\" name=\"content\" />\r\n");
      out.write("</form>\r\n");
      out.write("<form action=\"/TrustWinPro/action/index.jsp\" name=\"AllUser\" id=\"AllUser\" method=\"post\">\r\n");
      out.write("\t<input type=\"hidden\" value=\"User\" name=\"left\" />\r\n");
      out.write("\t<input type=\"hidden\" value=\"AllUser\" name=\"content\" />\r\n");
      out.write("</form>\r\n");
      out.write("<form action=\"/TrustWinPro/action/index.jsp\" name=\"AllDevice\" id=\"AllDevice\" method=\"post\">\r\n");
      out.write("\t<input type=\"hidden\" value=\"Device\" name=\"left\" />\r\n");
      out.write("\t<input type=\"hidden\" value=\"AllDevice\" name=\"content\" />\r\n");
      out.write("</form>\r\n");
      out.write("<form action=\"/TrustWinPro/action/index.jsp\" name=\"Device\" id=\"Device\" method=\"post\">\r\n");
      out.write("\t<input type=\"hidden\" value=\"Device\" name=\"left\" />\r\n");
      out.write("\t<input type=\"hidden\" value=\"\" name=\"deviceID\" />\r\n");
      out.write("\t<input type=\"hidden\" value=\"DeviceInfo\" name=\"content\" />\r\n");
      out.write("</form>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction SpanDeviceClass(idx){\r\n");
      out.write("\t\tdocument.getElementById(\"dev\"+idx).className = \"userspan\";\r\n");
      out.write("\t\tdocument.getElementById(\"dev\"+idx+\"a\").style.color = \"#ffffff\";\r\n");
      out.write("\t}\r\n");
      out.write("\tif(");
      out.print(request.getParameter("deviceID"));
      out.write("!=null){\r\n");
      out.write("\t\tSpanDeviceClass(");
      out.print(request.getParameter("deviceID"));
      out.write(");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction SpanUserClass(idx){\r\n");
      out.write("\t\tdocument.getElementById(\"user\"+idx).className = \"userspan\";\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif(");
      out.print(request.getParameter("userID"));
      out.write("!=null){\r\n");
      out.write("\t\tSpanUserClass(");
      out.print(request.getParameter("userID"));
      out.write(");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction swich(num,num2){\r\n");
      out.write("\t\tif(document.getElementById(num2).style.display != \"none\"){\r\n");
      out.write("\t\t\tdocument.getElementById(\"open\"+num).style.display = \"inline\";\r\n");
      out.write("\t\t\tdocument.getElementById(\"close\"+num).style.display = \"none\";\r\n");
      out.write("\t\t\tdocument.getElementById(num2).style.display = \"none\";\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tdocument.getElementById(\"open\"+num).style.display = \"none\";\r\n");
      out.write("\t\t\tdocument.getElementById(\"close\"+num).style.display = \"inline\";\r\n");
      out.write("\t\t\tdocument.getElementById(num2).style.display = \"block\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction Buttom(val){\r\n");
      out.write("\t\tif(val == \"User\"){\r\n");
      out.write("\t\t\tdocument.getElementById(\"userButtom\").src = \"/TrustWinPro/action/image/interface/leftButtom_on.png\";\r\n");
      out.write("\t\t\tdocument.getElementById(\"deviceButtom\").src = \"/TrustWinPro/action/image/interface/leftButtom_off.png\";\r\n");
      out.write("\t\t\tdocument.getElementById(\"eventButtom\").src = \"/TrustWinPro/action/image/interface/leftButtom_off.png\";\r\n");
      out.write("\t\t\tdocument.getElementById(\"timeButtom\").src = \"/TrustWinPro/action/image/interface/leftButtom_off.png\";\r\n");
      out.write("\t\t\tdocument.getElementById(\"monitoringButtom\").src = \"/TrustWinPro/action/image/interface/leftButtom_off.png\";\r\n");
      out.write("\t\t}else if(val == \"Device\"){\r\n");
      out.write("\t\t\tdocument.getElementById(\"userButtom\").src = \"/TrustWinPro/action/image/interface/leftButtom_off.png\";\r\n");
      out.write("\t\t\tdocument.getElementById(\"deviceButtom\").src = \"/TrustWinPro/action/image/interface/leftButtom_on.png\";\r\n");
      out.write("\t\t\tdocument.getElementById(\"eventButtom\").src = \"/TrustWinPro/action/image/interface/leftButtom_off.png\";\r\n");
      out.write("\t\t\tdocument.getElementById(\"timeButtom\").src = \"/TrustWinPro/action/image/interface/leftButtom_off.png\";\r\n");
      out.write("\t\t\tdocument.getElementById(\"monitoringButtom\").src = \"/TrustWinPro/action/image/interface/leftButtom_off.png\";\r\n");
      out.write("\t\t}else if(val == \"Event\"){\r\n");
      out.write("\t\t\tdocument.getElementById(\"userButtom\").src = \"/TrustWinPro/action/image/interface/leftButtom_off.png\";\r\n");
      out.write("\t\t\tdocument.getElementById(\"deviceButtom\").src = \"/TrustWinPro/action/image/interface/leftButtom_off.png\";\r\n");
      out.write("\t\t\tdocument.getElementById(\"eventButtom\").src = \"/TrustWinPro/action/image/interface/leftButtom_on.png\";\r\n");
      out.write("\t\t\tdocument.getElementById(\"timeButtom\").src = \"/TrustWinPro/action/image/interface/leftButtom_off.png\";\r\n");
      out.write("\t\t\tdocument.getElementById(\"monitoringButtom\").src = \"/TrustWinPro/action/image/interface/leftButtom_off.png\";\r\n");
      out.write("\t\t}else if(val == \"Time\"){\r\n");
      out.write("\t\t\tdocument.getElementById(\"userButtom\").src = \"/TrustWinPro/action/image/interface/leftButtom_off.png\";\r\n");
      out.write("\t\t\tdocument.getElementById(\"deviceButtom\").src = \"/TrustWinPro/action/image/interface/leftButtom_off.png\";\r\n");
      out.write("\t\t\tdocument.getElementById(\"eventButtom\").src = \"/TrustWinPro/action/image/interface/leftButtom_off.png\";\r\n");
      out.write("\t\t\tdocument.getElementById(\"timeButtom\").src = \"/TrustWinPro/action/image/interface/leftButtom_on.png\";\r\n");
      out.write("\t\t\tdocument.getElementById(\"monitoringButtom\").src = \"/TrustWinPro/action/image/interface/leftButtom_off.png\";\r\n");
      out.write("\t\t}else if(val == \"Monitoring\"){\r\n");
      out.write("\t\t\tdocument.getElementById(\"userButtom\").src = \"/TrustWinPro/action/image/interface/leftButtom_off.png\";\r\n");
      out.write("\t\t\tdocument.getElementById(\"deviceButtom\").src = \"/TrustWinPro/action/image/interface/leftButtom_off.png\";\r\n");
      out.write("\t\t\tdocument.getElementById(\"eventButtom\").src = \"/TrustWinPro/action/image/interface/leftButtom_off.png\";\r\n");
      out.write("\t\t\tdocument.getElementById(\"timeButtom\").src = \"/TrustWinPro/action/image/interface/leftButtom_off.png\";\r\n");
      out.write("\t\t\tdocument.getElementById(\"monitoringButtom\").src = \"/TrustWinPro/action/image/interface/leftButtom_on.png\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tButtom('");
      out.print(request.getParameter("left"));
      out.write("')\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
